/**
 * Solitaire 40-Level Campaign Configuration
 * Exactly 40 levels (Level 1 to Level 40).
 * Level 1 is already very difficult and challenging.
 * Difficulty scales systematically up to Level 40 (Final Challenge).
 * Every level features verified deterministic seeds with distinct strategic characteristics.
 */

import { LevelConfig, GameMode } from './types';

export const ALL_40_SOLITAIRE_LEVELS: LevelConfig[] = [
  // -------------------------------------------------------------
  // TIER 1: LEVELS 1–5 (HARD)
  // Buried Aces, strategic hidden card dependencies, tight stock
  // -------------------------------------------------------------
  {
    level: 1,
    title: 'The Royal Threshold',
    mode: 'draw1',
    difficulty: 'Hard',
    seed: 104729,
    targetScore: 1400,
    moveTarget: 92,
    timeLimitSeconds: 360,
    starThresholds: [800, 1200, 1600],
    description: 'Level 1 is already a true challenge. Multiple Aces are buried deep in columns 5 and 6. Conserve stock cycles and prioritize uncovering column 6.',
  },
  {
    level: 2,
    title: 'Black & Red Tension',
    mode: 'draw1',
    difficulty: 'Hard',
    seed: 224737,
    targetScore: 1500,
    moveTarget: 88,
    timeLimitSeconds: 350,
    starThresholds: [850, 1300, 1700],
    description: 'Kings are scattered across short columns with conflicting suit colors. Careful sequencing of intermediate Queens is required.',
  },
  {
    level: 3,
    title: 'Draw 3 Initiation',
    mode: 'draw3',
    difficulty: 'Hard',
    seed: 314159,
    targetScore: 1550,
    moveTarget: 95,
    timeLimitSeconds: 380,
    starThresholds: [900, 1350, 1800],
    description: 'First Draw 3 trial. Three cards are dealt at once; plan multiple draws ahead so key connector cards reach the top of the waste pile.',
  },
  {
    level: 4,
    title: 'Buried Spades',
    mode: 'draw1',
    difficulty: 'Hard',
    seed: 489203,
    targetScore: 1600,
    moveTarget: 84,
    timeLimitSeconds: 340,
    starThresholds: [950, 1400, 1850],
    description: 'All four Spades low cards sit at the base of the longest columns. Every face-down reveal is critical.',
  },
  {
    level: 5,
    title: 'The Fortress Gate',
    mode: 'draw3',
    difficulty: 'Hard',
    seed: 582107,
    targetScore: 1650,
    moveTarget: 90,
    timeLimitSeconds: 350,
    starThresholds: [1000, 1450, 1900],
    description: 'Column 7 contains five face-down cards locking crucial foundation builders. Requires surgical tableau rearrangement.',
  },

  // -------------------------------------------------------------
  // TIER 2: LEVELS 6–10 (HARD+)
  // Constrained tableau sequences, buried low cards, tight moves
  // -------------------------------------------------------------
  {
    level: 6,
    title: 'Narrow Corridors',
    mode: 'draw1',
    difficulty: 'Hard+',
    seed: 692813,
    targetScore: 1700,
    moveTarget: 82,
    timeLimitSeconds: 330,
    starThresholds: [1050, 1500, 1950],
    description: 'Limited initial legal moves. You must execute precise cross-column transfers to expose the Ace of Hearts.',
  },
  {
    level: 7,
    title: 'Triple Draw Dilemma',
    mode: 'draw3',
    difficulty: 'Hard+',
    seed: 718281,
    targetScore: 1750,
    moveTarget: 92,
    timeLimitSeconds: 360,
    starThresholds: [1100, 1550, 2000],
    description: 'The stock pile holds key intermediate red Jacks and black 10s trapped behind offset draws. Count stock cycles attentively.',
  },
  {
    level: 8,
    title: 'Diamond Vault',
    mode: 'draw1',
    difficulty: 'Hard+',
    seed: 849201,
    targetScore: 1800,
    moveTarget: 80,
    timeLimitSeconds: 320,
    starThresholds: [1150, 1600, 2050],
    description: 'Diamonds rule the foundations. Delaying foundation transfers is essential to keep tableau build options open.',
  },
  {
    level: 9,
    title: 'Split Kings',
    mode: 'draw3',
    difficulty: 'Hard+',
    seed: 928371,
    targetScore: 1850,
    moveTarget: 88,
    timeLimitSeconds: 340,
    starThresholds: [1200, 1650, 2100],
    description: 'Two Kings appear early in short columns while empty spots are rare. Choosing which King to anchor decides victory.',
  },
  {
    level: 10,
    title: 'Citadel Trial',
    mode: 'draw1',
    difficulty: 'Hard+',
    seed: 104928,
    targetScore: 1900,
    moveTarget: 78,
    timeLimitSeconds: 310,
    starThresholds: [1250, 1700, 2150],
    description: 'A masterpiece of balance. High rank cards dominate the first four columns, requiring patience until stock unlocks low suits.',
  },

  // -------------------------------------------------------------
  // TIER 3: LEVELS 11–15 (VERY HARD)
  // Deep dependencies, limited free slots, strict efficiency
  // -------------------------------------------------------------
  {
    level: 11,
    title: 'The Deep Well',
    mode: 'draw3',
    difficulty: 'Very Hard',
    seed: 114829,
    targetScore: 1950,
    moveTarget: 86,
    timeLimitSeconds: 330,
    starThresholds: [1300, 1750, 2200],
    description: 'Key Aces are hidden under four layers of cards. Draw 3 mechanics demand precise waste-timing to avoid cycling dead-ends.',
  },
  {
    level: 12,
    title: 'Sovereign Gambit',
    mode: 'draw1',
    difficulty: 'Very Hard',
    seed: 129381,
    targetScore: 2000,
    moveTarget: 76,
    timeLimitSeconds: 300,
    starThresholds: [1350, 1800, 2250],
    description: 'Moving a Queen too early will block the last empty tableau slot. Think two sequences ahead before committing.',
  },
  {
    level: 13,
    title: 'Iron Lattice',
    mode: 'draw3',
    difficulty: 'Very Hard',
    seed: 138492,
    targetScore: 2050,
    moveTarget: 84,
    timeLimitSeconds: 320,
    starThresholds: [1400, 1850, 2300],
    description: 'Alternating suit clusters form rigid blocks. Only smart multi-card stack transfers can crack open the deep face-down cards.',
  },
  {
    level: 14,
    title: 'Midnight Draw',
    mode: 'draw1',
    difficulty: 'Very Hard',
    seed: 149283,
    targetScore: 2100,
    moveTarget: 74,
    timeLimitSeconds: 290,
    starThresholds: [1450, 1900, 2350],
    description: 'High pressure move limit. Minimize wasted tableau shuffling to achieve a 3-star rating.',
  },
  {
    level: 15,
    title: 'Emerald Bastion',
    mode: 'draw3',
    difficulty: 'Very Hard',
    seed: 158293,
    targetScore: 2150,
    moveTarget: 82,
    timeLimitSeconds: 310,
    starThresholds: [1500, 1950, 2400],
    description: 'Half of the deck is locked in the rightmost columns. Careful management of waste cards is the only path to the foundations.',
  },

  // -------------------------------------------------------------
  // TIER 4: LEVELS 16–20 (EXPERT)
  // Multi-move lookahead, tight King placements, zero room for waste
  // -------------------------------------------------------------
  {
    level: 16,
    title: 'The Strategist',
    mode: 'draw3',
    difficulty: 'Expert',
    seed: 169284,
    targetScore: 2200,
    moveTarget: 80,
    timeLimitSeconds: 300,
    starThresholds: [1550, 2000, 2450],
    description: 'Three different potential moves exist at start, but only one prevents an early deadlock. Evaluate all branches before moving.',
  },
  {
    level: 17,
    title: 'Crown & Scepter',
    mode: 'draw1',
    difficulty: 'Expert',
    seed: 178294,
    targetScore: 2250,
    moveTarget: 72,
    timeLimitSeconds: 280,
    starThresholds: [1600, 2050, 2500],
    description: 'All four Kings are clustered in columns 1 through 4. Creating open tableau spaces is brutally difficult.',
  },
  {
    level: 18,
    title: 'The Grand Shifter',
    mode: 'draw3',
    difficulty: 'Expert',
    seed: 189204,
    targetScore: 2300,
    moveTarget: 78,
    timeLimitSeconds: 290,
    starThresholds: [1650, 2100, 2550],
    description: 'Complex substack migration is required: moving 4-card chains back and forth to uncover solitary face-down cards.',
  },
  {
    level: 19,
    title: 'Shadowed Clubs',
    mode: 'draw1',
    difficulty: 'Expert',
    seed: 198302,
    targetScore: 2350,
    moveTarget: 70,
    timeLimitSeconds: 270,
    starThresholds: [1700, 2150, 2600],
    description: 'Clubs and Diamonds are intertwined. Foundation ascension must be kept strictly balanced between suits.',
  },
  {
    level: 20,
    title: 'The Summit Passage',
    mode: 'draw3',
    difficulty: 'Expert',
    seed: 204918,
    targetScore: 2400,
    moveTarget: 76,
    timeLimitSeconds: 280,
    starThresholds: [1750, 2200, 2650],
    description: 'Milestone challenge. Extremely intricate draw-3 cycle where a single misplaced card renders the stock cycle unplayable.',
  },

  // -------------------------------------------------------------
  // TIER 5: LEVELS 21–25 (EXPERT+)
  // Rigid suit blocks, tight stock reserves, strict time limits
  // -------------------------------------------------------------
  {
    level: 21,
    title: 'Obsidian Arch',
    mode: 'draw1',
    difficulty: 'Expert+',
    seed: 219482,
    targetScore: 2450,
    moveTarget: 68,
    timeLimitSeconds: 260,
    starThresholds: [1800, 2250, 2700],
    description: 'Flawless execution needed. Very few free slots; you must build compact descending runs without spreading cards.',
  },
  {
    level: 22,
    title: 'The Locked Matrix',
    mode: 'draw3',
    difficulty: 'Expert+',
    seed: 228391,
    targetScore: 2500,
    moveTarget: 74,
    timeLimitSeconds: 270,
    starThresholds: [1850, 2300, 2750],
    description: 'Draw 3 deal with buried 2s and 3s. Foundation building is delayed until the middle game—keep your tableau flexible.',
  },
  {
    level: 23,
    title: 'Crimson Labyrinth',
    mode: 'draw1',
    difficulty: 'Expert+',
    seed: 239481,
    targetScore: 2550,
    moveTarget: 66,
    timeLimitSeconds: 250,
    starThresholds: [1900, 2350, 2800],
    description: 'Red cards heavily outnumber black cards in initial face-up positions, creating fierce competition for black connectors.',
  },
  {
    level: 24,
    title: 'The Silent Order',
    mode: 'draw3',
    difficulty: 'Expert+',
    seed: 248192,
    targetScore: 2600,
    moveTarget: 72,
    timeLimitSeconds: 260,
    starThresholds: [1950, 2400, 2850],
    description: 'Unforgiving stock layout. Withdrawing cards from foundations back down to the tableau may be necessary to unlock columns.',
  },
  {
    level: 25,
    title: 'Imperial Trial',
    mode: 'draw3',
    difficulty: 'Expert+',
    seed: 259381,
    targetScore: 2650,
    moveTarget: 70,
    timeLimitSeconds: 250,
    starThresholds: [2000, 2450, 2900],
    description: 'Every column from 3 to 7 hides a crucial low card. True expert-level Solitaire problem solving.',
  },

  // -------------------------------------------------------------
  // TIER 6: LEVELS 26–30 (EXTREME)
  // Deep buried foundations, high score thresholds, demanding efficiency
  // -------------------------------------------------------------
  {
    level: 26,
    title: 'The Needle’s Eye',
    mode: 'draw1',
    difficulty: 'Extreme',
    seed: 269182,
    targetScore: 2700,
    moveTarget: 64,
    timeLimitSeconds: 240,
    starThresholds: [2050, 2500, 2950],
    description: 'Only one sequence of moves can expose the Ace of Clubs within the first 15 turns. One wrong move leads to stalemate.',
  },
  {
    level: 27,
    title: 'Vortex of Spades',
    mode: 'draw3',
    difficulty: 'Extreme',
    seed: 278391,
    targetScore: 2750,
    moveTarget: 68,
    timeLimitSeconds: 250,
    starThresholds: [2100, 2550, 3000],
    description: 'Spades are buried under heavy layers in columns 6 and 7. The draw-3 sequence requires careful modulo arithmetic.',
  },
  {
    level: 28,
    title: 'The Iron Crucible',
    mode: 'draw1',
    difficulty: 'Extreme',
    seed: 289182,
    targetScore: 2800,
    moveTarget: 62,
    timeLimitSeconds: 230,
    starThresholds: [2150, 2600, 3050],
    description: 'Blistering efficiency requirement: complete in 62 moves or less for 3 stars. Every single move must count.',
  },
  {
    level: 29,
    title: 'Mirror Mirage',
    mode: 'draw3',
    difficulty: 'Extreme',
    seed: 298471,
    targetScore: 2850,
    moveTarget: 66,
    timeLimitSeconds: 240,
    starThresholds: [2200, 2650, 3100],
    description: 'Near-identical card pairings in different columns deceive the eyes. Double-check which column you empty first.',
  },
  {
    level: 30,
    title: 'The Black Citadel',
    mode: 'draw3',
    difficulty: 'Extreme',
    seed: 304918,
    targetScore: 2900,
    moveTarget: 64,
    timeLimitSeconds: 230,
    starThresholds: [2250, 2700, 3150],
    description: 'Extreme layout. Columns 5, 6, and 7 hold heavy face-down reserves. Requires mastery of foundation tempo.',
  },

  // -------------------------------------------------------------
  // TIER 7: LEVELS 31–35 (MASTER)
  // Grandmaster Solitaire calculations, tight constraint chains
  // -------------------------------------------------------------
  {
    level: 31,
    title: 'The Sovereign Mind',
    mode: 'draw1',
    difficulty: 'Master',
    seed: 318291,
    targetScore: 2950,
    moveTarget: 60,
    timeLimitSeconds: 220,
    starThresholds: [2300, 2750, 3200],
    description: 'Solitaire strategy at its highest level. Plan 5 moves in advance to avoid stranding connectors in the waste.',
  },
  {
    level: 32,
    title: 'The Golden Web',
    mode: 'draw3',
    difficulty: 'Master',
    seed: 329481,
    targetScore: 3000,
    moveTarget: 64,
    timeLimitSeconds: 230,
    starThresholds: [2350, 2800, 3250],
    description: 'Tableau cards are tightly locked together. You must dismantle and reassemble runs with mathematical precision.',
  },
  {
    level: 33,
    title: 'Abyssal Depth',
    mode: 'draw3',
    difficulty: 'Master',
    seed: 338192,
    targetScore: 3050,
    moveTarget: 62,
    timeLimitSeconds: 220,
    starThresholds: [2400, 2850, 3300],
    description: 'All four 2-cards are located at the very bottom of the longest columns. Complete mastery over stock timing required.',
  },
  {
    level: 34,
    title: 'The Monarch’s Riddle',
    mode: 'draw1',
    difficulty: 'Master',
    seed: 349182,
    targetScore: 3100,
    moveTarget: 58,
    timeLimitSeconds: 210,
    starThresholds: [2450, 2900, 3350],
    description: 'Sub-60 move challenge. Only the cleanest, most direct line of play will grant full 3-star honors.',
  },
  {
    level: 35,
    title: 'Celestial Alignment',
    mode: 'draw3',
    difficulty: 'Master',
    seed: 358291,
    targetScore: 3150,
    moveTarget: 60,
    timeLimitSeconds: 220,
    starThresholds: [2500, 2950, 3400],
    description: 'Harmonizing four foundation piles simultaneously under strict draw-3 constraints.',
  },

  // -------------------------------------------------------------
  // TIER 8: LEVELS 36–39 (MASTER+)
  // Razor-sharp precision, zero margin for error
  // -------------------------------------------------------------
  {
    level: 36,
    title: 'The Razor’s Edge',
    mode: 'draw1',
    difficulty: 'Master+',
    seed: 369182,
    targetScore: 3200,
    moveTarget: 56,
    timeLimitSeconds: 200,
    starThresholds: [2550, 3000, 3450],
    description: 'Extremely difficult deal. Zero unforced moves permitted. Every card transfer must immediately generate value.',
  },
  {
    level: 37,
    title: 'Crown of Thorns',
    mode: 'draw3',
    difficulty: 'Master+',
    seed: 378291,
    targetScore: 3250,
    moveTarget: 58,
    timeLimitSeconds: 210,
    starThresholds: [2600, 3050, 3500],
    description: 'Draw 3 deal where key cards are offset by 2 positions in the stock. Calculate card offsets before every draw.',
  },
  {
    level: 38,
    title: 'The Grand Architect',
    mode: 'draw3',
    difficulty: 'Master+',
    seed: 389182,
    targetScore: 3300,
    moveTarget: 56,
    timeLimitSeconds: 200,
    starThresholds: [2650, 3100, 3550],
    description: 'Requires complex tableau restructuring where entire multi-suit ladders must be shifted to free the base cards.',
  },
  {
    level: 39,
    title: 'Penultimate Sanctum',
    mode: 'draw1',
    difficulty: 'Master+',
    seed: 398291,
    targetScore: 3350,
    moveTarget: 54,
    timeLimitSeconds: 190,
    starThresholds: [2700, 3150, 3600],
    description: 'The final step before the summit. Lightning-fast pattern recognition and decisive execution needed.',
  },

  // -------------------------------------------------------------
  // TIER 9: LEVEL 40 — FINAL CHALLENGE
  // The hardest Solitaire level. Verified solvable, extreme strategic depth!
  // -------------------------------------------------------------
  {
    level: 40,
    title: 'The Grandmaster Crown',
    mode: 'draw3',
    difficulty: 'Master+',
    seed: 404819,
    targetScore: 3500,
    moveTarget: 52,
    timeLimitSeconds: 180,
    starThresholds: [2800, 3250, 3700],
    description: 'THE FINAL CHALLENGE! The ultimate Klondike Solitaire test. Draw 3 mode, deeply buried key ranks, strict move efficiency, and zero room for error. Complete this level to claim the Grandmaster Solitaire Crown!',
  },
];

export function getSolitaireLevelConfig(level: number): LevelConfig {
  const safeLevel = Math.max(1, Math.min(40, level));
  return ALL_40_SOLITAIRE_LEVELS[safeLevel - 1];
}
