/**
 * Puzzle Block 40-Level Campaign Configuration
 * Authentic Block Puzzle progression with clear objectives and strategic puzzle design.
 * Level 1 unlocked by default, levels 2-40 unlock progressively.
 */

import { LevelDefinition } from './types';

export const PUZZLE_BLOCK_LEVELS: LevelDefinition[] = [
  // ===================== LEVELS 1 - 5: STARTER & FOUNDATION =====================
  {
    id: 1,
    title: 'First Steps',
    difficulty: 'starter',
    targetScore: 600,
    targetLines: 3,
    description: 'Place pieces to complete full rows or columns. Clear 3 lines to finish the level!',
    reshuffleLimit: 3,
    starThresholds: [600, 1000, 1500],
  },
  {
    id: 2,
    title: 'Line Builder',
    difficulty: 'starter',
    targetScore: 1000,
    targetLines: 5,
    description: 'Build horizontal rows and vertical columns. Clear multiple lines at once for bonus points!',
    reshuffleLimit: 3,
    starThresholds: [1000, 1500, 2200],
  },
  {
    id: 3,
    title: 'Corner Craft',
    difficulty: 'easy',
    targetScore: 1400,
    targetLines: 6,
    description: 'Place corners and small blocks strategically to keep the center of the board clear.',
    reshuffleLimit: 3,
    starThresholds: [1400, 2000, 2800],
  },
  {
    id: 4,
    title: 'Tetromino Drop',
    difficulty: 'easy',
    targetScore: 1800,
    targetLines: 8,
    description: 'Tetrominoes arrive! Clear intersecting rows and columns simultaneously for combo scores.',
    reshuffleLimit: 2,
    starThresholds: [1800, 2500, 3400],
  },
  {
    id: 5,
    title: 'Combo Streak',
    difficulty: 'medium',
    targetScore: 2200,
    targetLines: 10,
    description: 'Perform consecutive line clears to trigger combo multipliers and reach the target score.',
    reshuffleLimit: 2,
    starThresholds: [2200, 3000, 4000],
  },

  // ===================== LEVELS 6 - 10: MEDIUM & STRATEGY =====================
  {
    id: 6,
    title: 'Square Harmony',
    difficulty: 'medium',
    targetScore: 2600,
    targetLines: 11,
    description: 'Integrate 2x2 squares and long lines efficiently. Maintain open spaces for new trays.',
    reshuffleLimit: 2,
    starThresholds: [2600, 3500, 4600],
  },
  {
    id: 7,
    title: 'Cross Clears',
    difficulty: 'medium',
    targetScore: 3000,
    targetLines: 12,
    description: 'Simultaneously clear a row AND a column with a single piece to earn the Cross Clear bonus.',
    reshuffleLimit: 2,
    starThresholds: [3000, 4000, 5200],
  },
  {
    id: 8,
    title: 'Grid Balance',
    difficulty: 'medium',
    targetScore: 3400,
    targetLines: 13,
    description: 'Distribute pieces across quadrants evenly so that no single corner fills up too quickly.',
    reshuffleLimit: 2,
    starThresholds: [3400, 4500, 5800],
  },
  {
    id: 9,
    title: 'Polyomino Rush',
    difficulty: 'hard',
    targetScore: 3800,
    targetLines: 14,
    description: 'Fast-paced polyomino placement. Use your reshuffle strategically when tight on space.',
    reshuffleLimit: 2,
    starThresholds: [3800, 5000, 6500],
  },
  {
    id: 10,
    title: 'Grand Mastery I',
    difficulty: 'hard',
    targetScore: 4200,
    targetLines: 15,
    description: 'The first major milestone! Showcase your multi-line clearing mastery across all shapes.',
    reshuffleLimit: 2,
    starThresholds: [4200, 5500, 7200],
  },

  // ===================== LEVELS 11 - 15: ADVANCED & TACTICS =====================
  {
    id: 11,
    title: 'Edge Precision',
    difficulty: 'hard',
    targetScore: 4600,
    targetLines: 16,
    description: 'Use outer edges to absorb long bars and L-pieces, saving the center for combo triggers.',
    reshuffleLimit: 2,
    starThresholds: [4600, 6000, 7800],
  },
  {
    id: 12,
    title: 'Double Trouble',
    difficulty: 'hard',
    targetScore: 5000,
    targetLines: 17,
    description: 'Aim for double and triple line clears on every placement cycle to maximize efficiency.',
    reshuffleLimit: 2,
    starThresholds: [5000, 6500, 8400],
  },
  {
    id: 13,
    title: 'Center Stage',
    difficulty: 'hard',
    targetScore: 5400,
    targetLines: 18,
    description: 'Keep the 4x4 central zone empty as long as possible to safely accommodate larger pieces.',
    reshuffleLimit: 2,
    starThresholds: [5400, 7000, 9000],
  },
  {
    id: 14,
    title: 'T-Shape Dynamics',
    difficulty: 'hard',
    targetScore: 5800,
    targetLines: 19,
    description: 'T-shapes and S-shapes require smart placement. Slot them into natural interlocking pockets.',
    reshuffleLimit: 2,
    starThresholds: [5800, 7500, 9600],
  },
  {
    id: 15,
    title: 'Pentomino Frontier',
    difficulty: 'very_hard',
    targetScore: 6200,
    targetLines: 20,
    description: 'Large 5-cell shapes enter the pool! Clear space rapidly before they arrive in the tray.',
    reshuffleLimit: 2,
    starThresholds: [6200, 8000, 10200],
  },

  // ===================== LEVELS 16 - 20: VERY HARD =====================
  {
    id: 16,
    title: 'Cascade Theory',
    difficulty: 'very_hard',
    targetScore: 6600,
    targetLines: 21,
    description: 'Setup multiple rows that are one block away from completion for devastating combo cascades.',
    reshuffleLimit: 2,
    starThresholds: [6600, 8500, 10800],
  },
  {
    id: 17,
    title: 'The Great Wall',
    difficulty: 'very_hard',
    targetScore: 7000,
    targetLines: 22,
    description: 'Do not let tall walls build up on the edges. Dissolve them with quick perpendicular lines.',
    reshuffleLimit: 2,
    starThresholds: [7000, 9000, 11500],
  },
  {
    id: 18,
    title: 'Color Symphony',
    difficulty: 'very_hard',
    targetScore: 7500,
    targetLines: 23,
    description: 'Sustain uninterrupted combo clears to build massive score multipliers.',
    reshuffleLimit: 2,
    starThresholds: [7500, 9600, 12200],
  },
  {
    id: 19,
    title: 'Vortex Grid',
    difficulty: 'very_hard',
    targetScore: 8000,
    targetLines: 24,
    description: 'Spiral your placements inward to create simultaneous 3-line and 4-line clear opportunities.',
    reshuffleLimit: 2,
    starThresholds: [8000, 10200, 13000],
  },
  {
    id: 20,
    title: 'Grand Mastery II',
    difficulty: 'expert',
    targetScore: 8500,
    targetLines: 25,
    description: 'Halfway through the gauntlet! Clear 25 full lines and score 8,500 points to prove your rank.',
    reshuffleLimit: 2,
    starThresholds: [8500, 10800, 13800],
  },

  // ===================== LEVELS 21 - 25: EXPERT =====================
  {
    id: 21,
    title: 'Triple Threat',
    difficulty: 'expert',
    targetScore: 9000,
    targetLines: 26,
    description: 'Every tray requires careful foresight. Analyze all 3 pieces before placing the first one.',
    reshuffleLimit: 2,
    starThresholds: [9000, 11500, 14600],
  },
  {
    id: 22,
    title: 'Clean Slate',
    difficulty: 'expert',
    targetScore: 9500,
    targetLines: 27,
    description: 'High score targets demand massive multi-line clears. Chain combos to hit 9,500 points.',
    reshuffleLimit: 2,
    starThresholds: [9500, 12100, 15400],
  },
  {
    id: 23,
    title: 'Spatial Rhythm',
    difficulty: 'expert',
    targetScore: 10000,
    targetLines: 28,
    description: 'Break into the five-figure score club! Keep lines clear and avoid isolated single holes.',
    reshuffleLimit: 2,
    starThresholds: [10000, 12800, 16200],
  },
  {
    id: 24,
    title: 'Diagonal Focus',
    difficulty: 'expert',
    targetScore: 10500,
    targetLines: 29,
    description: 'Balance diagonal distribution of empty corridors so any polyomino orientation fits smoothly.',
    reshuffleLimit: 2,
    starThresholds: [10500, 13400, 17000],
  },
  {
    id: 25,
    title: 'S-Tier Challenge',
    difficulty: 'expert+',
    targetScore: 11000,
    targetLines: 30,
    description: 'Reach 30 cleared lines. Save your reshuffle charges for emergency lockouts only.',
    reshuffleLimit: 2,
    starThresholds: [11000, 14000, 17800],
  },

  // ===================== LEVELS 26 - 30: EXTREME =====================
  {
    id: 26,
    title: 'High Velocity',
    difficulty: 'extreme',
    targetScore: 11600,
    targetLines: 31,
    description: 'Fast-paced board cycles. Keep the pace high and convert every tray into clean line drops.',
    reshuffleLimit: 2,
    starThresholds: [11600, 14800, 18800],
  },
  {
    id: 27,
    title: 'Zenith Grid',
    difficulty: 'extreme',
    targetScore: 12200,
    targetLines: 32,
    description: 'Clear lines without ever allowing the board to become more than 60% full.',
    reshuffleLimit: 2,
    starThresholds: [12200, 15500, 19600],
  },
  {
    id: 28,
    title: 'Combo Catalyst',
    difficulty: 'extreme',
    targetScore: 12800,
    targetLines: 33,
    description: 'Execute consecutive multi-clears to earn massive combo multipliers across 33 lines.',
    reshuffleLimit: 2,
    starThresholds: [12800, 16200, 20500],
  },
  {
    id: 29,
    title: 'Precision Architect',
    difficulty: 'extreme',
    targetScore: 13500,
    targetLines: 34,
    description: 'Every block counts. Sculpt the board like a masterpiece to prepare for the Grand Master tier.',
    reshuffleLimit: 2,
    starThresholds: [13500, 17000, 21500],
  },
  {
    id: 30,
    title: 'Grand Mastery III',
    difficulty: 'master',
    targetScore: 14200,
    targetLines: 35,
    description: 'Level 30 milestone! Defeat the extreme tier by clearing 35 lines and scoring 14,200 points.',
    reshuffleLimit: 2,
    starThresholds: [14200, 18000, 22600],
  },

  // ===================== LEVELS 31 - 35: MASTER =====================
  {
    id: 31,
    title: 'Iron Focus',
    difficulty: 'master',
    targetScore: 15000,
    targetLines: 36,
    description: 'Master-level endurance test. Keep composure across dozens of placement rounds.',
    reshuffleLimit: 2,
    starThresholds: [15000, 19000, 23800],
  },
  {
    id: 32,
    title: 'Apex Matrix',
    difficulty: 'master',
    targetScore: 15800,
    targetLines: 37,
    description: 'Balance high-density polyomino shapes with constant dual-axis line clearances.',
    reshuffleLimit: 2,
    starThresholds: [15800, 20000, 25000],
  },
  {
    id: 33,
    title: 'Hyper Clears',
    difficulty: 'master',
    targetScore: 16600,
    targetLines: 38,
    description: 'Chain triple and quad clears. High line points are mandatory to reach 16,600 points.',
    reshuffleLimit: 2,
    starThresholds: [16600, 21000, 26200],
  },
  {
    id: 34,
    title: 'Omni Flow',
    difficulty: 'master',
    targetScore: 17500,
    targetLines: 39,
    description: 'Smooth, unbroken rhythm of block drops. Clear rows and columns effortlessly.',
    reshuffleLimit: 2,
    starThresholds: [17500, 22000, 27500],
  },
  {
    id: 35,
    title: 'Grand Mastery IV',
    difficulty: 'master+',
    targetScore: 18500,
    targetLines: 40,
    description: 'Clear 40 full lines! Only elite puzzle tacticians reach the final 5 levels.',
    reshuffleLimit: 2,
    starThresholds: [18500, 23200, 29000],
  },

  // ===================== LEVELS 36 - 40: GRAND FINALE =====================
  {
    id: 36,
    title: 'Titan Grid',
    difficulty: 'master+',
    targetScore: 19500,
    targetLines: 42,
    description: 'Unrelenting polyomino challenge. Maintain flawless spatial organization.',
    reshuffleLimit: 2,
    starThresholds: [19500, 24500, 30500],
  },
  {
    id: 37,
    title: 'Eclipse Board',
    difficulty: 'master+',
    targetScore: 20500,
    targetLines: 44,
    description: 'Score 20,500 points! Rely on cross clears and combo multipliers to triumph.',
    reshuffleLimit: 2,
    starThresholds: [20500, 25800, 32000],
  },
  {
    id: 38,
    title: 'Cosmic Spectrum',
    difficulty: 'master+',
    targetScore: 21600,
    targetLines: 46,
    description: 'All polyomino shapes and colors in full harmony. Prepare for the penultimate test.',
    reshuffleLimit: 2,
    starThresholds: [21600, 27000, 33600],
  },
  {
    id: 39,
    title: 'Penultimate Ascent',
    difficulty: 'master+',
    targetScore: 23000,
    targetLines: 48,
    description: 'The gate to the summit! Clear 48 lines with impeccable block placement.',
    reshuffleLimit: 2,
    starThresholds: [23000, 28800, 35500],
  },
  {
    id: 40,
    title: 'Grand Master Sovereign',
    difficulty: 'master+',
    targetScore: 25000,
    targetLines: 50,
    description: 'The Ultimate Block Puzzle Challenge! Clear 50 lines and score 25,000 points to become a Block Legend!',
    reshuffleLimit: 3,
    starThresholds: [25000, 31000, 38000],
  },
];
