/**
 * Pop Balloon - 40 Progressive Tournament Levels
 * 
 * Strict Directives:
 * - Exactly 40 internally balanced, highly demanding, tournament-grade levels.
 * - Level 1: High difficulty baseline - MINIMUM 100 BALLOONS TO PASS.
 * - Progressive difficulty through Level 40:
 *   - Increasing balloon counts (100 to 230)
 *   - Increasing velocities (290 px/s up to 840 px/s)
 *   - Increasing simultaneous active balloons (4 up to 7)
 *   - Tightening touch tolerances (3.5px down to 0.0px exact hit)
 *   - Decreasing radii (36px micro orbs down to 17px)
 *   - Decreasing spawn intervals (420ms down to 145ms)
 *   - Dual color quotas, combo milestones, and complex wave patterns
 * - Guaranteed solvability: Smart spawning ensures required quota colors appear abundantly.
 */

export type LevelObjectiveType = 
  | 'pop_all'        // Pop all required balloons in wave (100+)
  | 'target_color'   // Pop designated color quota while managing falling screen
  | 'dual_color'     // Pop dual color quotas (e.g. Red + Blue)
  | 'combo_target'   // Pop required balloons AND achieve designated combo milestone
  | 'precision'      // Micro radius balloons with tight/zero touch margin
  | 'speed_rush';    // High velocity bursts

export interface PopBalloonLevelConfig {
  level: number;
  name: string;                 // Level title
  objectiveType: LevelObjectiveType;
  description: string;          // Player-facing goal
  targetPops: number;           // Total pops required (100+ for Level 1, up to 230)
  targetColor?: string;         // Target color hex
  targetColorName?: string;     // Color name e.g. 'RED'
  targetColorCount?: number;    // Required count of targetColor
  targetColor2?: string;        // Second color hex
  targetColor2Name?: string;
  targetColor2Count?: number;
  requiredCombo?: number;       // Required combo milestone
  targetActive: number;         // Maximum simultaneous unpopped balloons
  minSpeed: number;             // px/s
  maxSpeed: number;             // px/s
  minRadius: number;            // px
  maxRadius: number;            // px
  spawnIntervalMs: number;      // Spawn cooldown
  tierMultiplier: number;       // Score scaling multiplier (1.0 up to 3.5)
  initialBalloonsCount: number; // Staggered balloons on GO
  touchTolerance: number;       // Extra touch padding px (3.5px down to 0.0px)
  wavePattern?: 'standard' | 'tandem' | 'cascade' | 'speed_contrast' | 'burst';
}

export const POP_BALLOON_LEVELS: PopBalloonLevelConfig[] = [
  // -------------------------------------------------------------
  // TIER 1: TOURNAMENT QUALIFIERS (LEVELS 1 - 8)
  // Level 1: MINIMUM 100 BALLOONS TO PASS (High baseline difficulty)
  // -------------------------------------------------------------
  {
    level: 1,
    name: 'Championship Qualifier',
    objectiveType: 'pop_all',
    description: 'Pop 100 Balloons to Qualify',
    targetPops: 100,
    targetActive: 4,
    minSpeed: 290,
    maxSpeed: 340,
    minRadius: 31,
    maxRadius: 36,
    spawnIntervalMs: 410,
    tierMultiplier: 1.0,
    initialBalloonsCount: 3,
    touchTolerance: 3.5,
    wavePattern: 'standard',
  },
  {
    level: 2,
    name: 'Target Crimson',
    objectiveType: 'target_color',
    description: 'Pop 28 Red Balloons (104 Total)',
    targetPops: 104,
    targetColor: '#FF3B30',
    targetColorName: 'RED',
    targetColorCount: 28,
    targetActive: 4,
    minSpeed: 305,
    maxSpeed: 355,
    minRadius: 30,
    maxRadius: 35,
    spawnIntervalMs: 395,
    tierMultiplier: 1.06,
    initialBalloonsCount: 3,
    touchTolerance: 3.2,
    wavePattern: 'standard',
  },
  {
    level: 3,
    name: 'Twin Cascade',
    objectiveType: 'pop_all',
    description: 'Pop 108 Tandem Balloons',
    targetPops: 108,
    targetActive: 4,
    minSpeed: 320,
    maxSpeed: 370,
    minRadius: 29,
    maxRadius: 34,
    spawnIntervalMs: 380,
    tierMultiplier: 1.12,
    initialBalloonsCount: 4,
    touchTolerance: 3.0,
    wavePattern: 'tandem',
  },
  {
    level: 4,
    name: 'Cobalt Focus',
    objectiveType: 'target_color',
    description: 'Pop 30 Blue Balloons (110 Total)',
    targetPops: 110,
    targetColor: '#007AFF',
    targetColorName: 'BLUE',
    targetColorCount: 30,
    targetActive: 5,
    minSpeed: 335,
    maxSpeed: 385,
    minRadius: 29,
    maxRadius: 33,
    spawnIntervalMs: 370,
    tierMultiplier: 1.18,
    initialBalloonsCount: 4,
    touchTolerance: 2.8,
    wavePattern: 'standard',
  },
  {
    level: 5,
    name: 'Streak Novice',
    objectiveType: 'combo_target',
    description: 'Reach 10x Combo & Pop 114 Balloons',
    targetPops: 114,
    requiredCombo: 10,
    targetActive: 5,
    minSpeed: 350,
    maxSpeed: 400,
    minRadius: 28,
    maxRadius: 32,
    spawnIntervalMs: 360,
    tierMultiplier: 1.25,
    initialBalloonsCount: 4,
    touchTolerance: 2.6,
    wavePattern: 'standard',
  },
  {
    level: 6,
    name: 'Dual Clash: Red & Blue',
    objectiveType: 'dual_color',
    description: 'Pop 24 Red & 24 Blue (118 Total)',
    targetPops: 118,
    targetColor: '#FF3B30',
    targetColorName: 'RED',
    targetColorCount: 24,
    targetColor2: '#007AFF',
    targetColor2Name: 'BLUE',
    targetColor2Count: 24,
    targetActive: 5,
    minSpeed: 365,
    maxSpeed: 420,
    minRadius: 27,
    maxRadius: 32,
    spawnIntervalMs: 350,
    tierMultiplier: 1.32,
    initialBalloonsCount: 4,
    touchTolerance: 2.5,
    wavePattern: 'standard',
  },
  {
    level: 7,
    name: 'Emerald Ascent',
    objectiveType: 'target_color',
    description: 'Pop 32 Green Balloons (120 Total)',
    targetPops: 120,
    targetColor: '#34C759',
    targetColorName: 'GREEN',
    targetColorCount: 32,
    targetActive: 5,
    minSpeed: 380,
    maxSpeed: 435,
    minRadius: 27,
    maxRadius: 31,
    spawnIntervalMs: 340,
    tierMultiplier: 1.38,
    initialBalloonsCount: 4,
    touchTolerance: 2.4,
    wavePattern: 'cascade',
  },
  {
    level: 8,
    name: 'Cascade Torrent',
    objectiveType: 'pop_all',
    description: 'Pop 124 Cascade Balloons',
    targetPops: 124,
    targetActive: 5,
    minSpeed: 395,
    maxSpeed: 450,
    minRadius: 26,
    maxRadius: 31,
    spawnIntervalMs: 330,
    tierMultiplier: 1.45,
    initialBalloonsCount: 5,
    touchTolerance: 2.2,
    wavePattern: 'cascade',
  },

  // -------------------------------------------------------------
  // TIER 2: ADVANCED CONTENDERS (LEVELS 9 - 16)
  // Higher velocity, tighter margins, dual quotas
  // -------------------------------------------------------------
  {
    level: 9,
    name: 'Solar Yellow Rush',
    objectiveType: 'target_color',
    description: 'Pop 34 Yellow Balloons (126 Total)',
    targetPops: 126,
    targetColor: '#FFD60A',
    targetColorName: 'YELLOW',
    targetColorCount: 34,
    targetActive: 5,
    minSpeed: 410,
    maxSpeed: 465,
    minRadius: 26,
    maxRadius: 30,
    spawnIntervalMs: 320,
    tierMultiplier: 1.52,
    initialBalloonsCount: 5,
    touchTolerance: 2.0,
    wavePattern: 'standard',
  },
  {
    level: 10,
    name: 'Purple & Orange Quota',
    objectiveType: 'dual_color',
    description: 'Pop 26 Purple & 26 Orange (128 Total)',
    targetPops: 128,
    targetColor: '#AF52DE',
    targetColorName: 'PURPLE',
    targetColorCount: 26,
    targetColor2: '#FF9500',
    targetColor2Name: 'ORANGE',
    targetColor2Count: 26,
    targetActive: 5,
    minSpeed: 425,
    maxSpeed: 480,
    minRadius: 25,
    maxRadius: 30,
    spawnIntervalMs: 310,
    tierMultiplier: 1.6,
    initialBalloonsCount: 5,
    touchTolerance: 2.0,
    wavePattern: 'standard',
  },
  {
    level: 11,
    name: 'Micro Precision',
    objectiveType: 'precision',
    description: 'Pop 130 Micro Balloons',
    targetPops: 130,
    targetActive: 5,
    minSpeed: 440,
    maxSpeed: 495,
    minRadius: 24,
    maxRadius: 28,
    spawnIntervalMs: 300,
    tierMultiplier: 1.68,
    initialBalloonsCount: 5,
    touchTolerance: 1.8,
    wavePattern: 'standard',
  },
  {
    level: 12,
    name: 'Speed Vortex',
    objectiveType: 'speed_rush',
    description: 'Pop 134 High-Speed Balloons',
    targetPops: 134,
    targetActive: 6,
    minSpeed: 455,
    maxSpeed: 515,
    minRadius: 24,
    maxRadius: 28,
    spawnIntervalMs: 290,
    tierMultiplier: 1.75,
    initialBalloonsCount: 5,
    touchTolerance: 1.8,
    wavePattern: 'speed_contrast',
  },
  {
    level: 13,
    name: 'Streak Master',
    objectiveType: 'combo_target',
    description: 'Reach 14x Combo & Pop 136 Balloons',
    targetPops: 136,
    requiredCombo: 14,
    targetActive: 6,
    minSpeed: 470,
    maxSpeed: 530,
    minRadius: 23,
    maxRadius: 27,
    spawnIntervalMs: 280,
    tierMultiplier: 1.82,
    initialBalloonsCount: 5,
    touchTolerance: 1.6,
    wavePattern: 'standard',
  },
  {
    level: 14,
    name: 'Crimson & Gold Wave',
    objectiveType: 'dual_color',
    description: 'Pop 28 Red & 28 Yellow (140 Total)',
    targetPops: 140,
    targetColor: '#FF3B30',
    targetColorName: 'RED',
    targetColorCount: 28,
    targetColor2: '#FFD60A',
    targetColor2Name: 'YELLOW',
    targetColor2Count: 28,
    targetActive: 6,
    minSpeed: 485,
    maxSpeed: 545,
    minRadius: 23,
    maxRadius: 27,
    spawnIntervalMs: 270,
    tierMultiplier: 1.9,
    initialBalloonsCount: 5,
    touchTolerance: 1.5,
    wavePattern: 'standard',
  },
  {
    level: 15,
    name: 'Burst Torrent',
    objectiveType: 'pop_all',
    description: 'Pop 142 Rapid Burst Balloons',
    targetPops: 142,
    targetActive: 6,
    minSpeed: 500,
    maxSpeed: 560,
    minRadius: 22,
    maxRadius: 26,
    spawnIntervalMs: 265,
    tierMultiplier: 1.98,
    initialBalloonsCount: 5,
    touchTolerance: 1.4,
    wavePattern: 'burst',
  },
  {
    level: 16,
    name: 'Pink Orchid Focus',
    objectiveType: 'target_color',
    description: 'Pop 36 Pink Balloons (145 Total)',
    targetPops: 145,
    targetColor: '#FF2D55',
    targetColorName: 'PINK',
    targetColorCount: 36,
    targetActive: 6,
    minSpeed: 515,
    maxSpeed: 575,
    minRadius: 22,
    maxRadius: 26,
    spawnIntervalMs: 255,
    tierMultiplier: 2.05,
    initialBalloonsCount: 5,
    touchTolerance: 1.3,
    wavePattern: 'standard',
  },

  // -------------------------------------------------------------
  // TIER 3: PRO TOURNAMENT CIRCUIT (LEVELS 17 - 24)
  // Expert reflex tests, 530-640 px/s, sub-second decisions
  // -------------------------------------------------------------
  {
    level: 17,
    name: 'Cascade Blitz',
    objectiveType: 'pop_all',
    description: 'Pop 148 Blitz Balloons',
    targetPops: 148,
    targetActive: 6,
    minSpeed: 530,
    maxSpeed: 590,
    minRadius: 21,
    maxRadius: 25,
    spawnIntervalMs: 250,
    tierMultiplier: 2.12,
    initialBalloonsCount: 5,
    touchTolerance: 1.2,
    wavePattern: 'cascade',
  },
  {
    level: 18,
    name: 'Green & Azure Symphony',
    objectiveType: 'dual_color',
    description: 'Pop 30 Green & 30 Blue (152 Total)',
    targetPops: 152,
    targetColor: '#34C759',
    targetColorName: 'GREEN',
    targetColorCount: 30,
    targetColor2: '#007AFF',
    targetColor2Name: 'BLUE',
    targetColor2Count: 30,
    targetActive: 6,
    minSpeed: 545,
    maxSpeed: 605,
    minRadius: 21,
    maxRadius: 25,
    spawnIntervalMs: 240,
    tierMultiplier: 2.2,
    initialBalloonsCount: 6,
    touchTolerance: 1.1,
    wavePattern: 'standard',
  },
  {
    level: 19,
    name: 'Hyper Streak',
    objectiveType: 'combo_target',
    description: 'Reach 18x Combo & Pop 156 Balloons',
    targetPops: 156,
    requiredCombo: 18,
    targetActive: 6,
    minSpeed: 560,
    maxSpeed: 620,
    minRadius: 20,
    maxRadius: 24,
    spawnIntervalMs: 235,
    tierMultiplier: 2.28,
    initialBalloonsCount: 6,
    touchTolerance: 1.0,
    wavePattern: 'standard',
  },
  {
    level: 20,
    name: 'Sonic Stream',
    objectiveType: 'speed_rush',
    description: 'Survive 160 Ultra-Speed Balloons',
    targetPops: 160,
    targetActive: 6,
    minSpeed: 575,
    maxSpeed: 640,
    minRadius: 20,
    maxRadius: 24,
    spawnIntervalMs: 225,
    tierMultiplier: 2.35,
    initialBalloonsCount: 6,
    touchTolerance: 0.9,
    wavePattern: 'speed_contrast',
  },
  {
    level: 21,
    name: 'Violet Storm',
    objectiveType: 'target_color',
    description: 'Pop 40 Purple Balloons (164 Total)',
    targetPops: 164,
    targetColor: '#AF52DE',
    targetColorName: 'PURPLE',
    targetColorCount: 40,
    targetActive: 6,
    minSpeed: 590,
    maxSpeed: 655,
    minRadius: 20,
    maxRadius: 23.5,
    spawnIntervalMs: 220,
    tierMultiplier: 2.42,
    initialBalloonsCount: 6,
    touchTolerance: 0.8,
    wavePattern: 'standard',
  },
  {
    level: 22,
    name: 'Dual Crucible: Pink & Red',
    objectiveType: 'dual_color',
    description: 'Pop 32 Pink & 32 Red (168 Total)',
    targetPops: 168,
    targetColor: '#FF2D55',
    targetColorName: 'PINK',
    targetColorCount: 32,
    targetColor2: '#FF3B30',
    targetColor2Name: 'RED',
    targetColor2Count: 32,
    targetActive: 6,
    minSpeed: 605,
    maxSpeed: 670,
    minRadius: 19,
    maxRadius: 23,
    spawnIntervalMs: 215,
    tierMultiplier: 2.5,
    initialBalloonsCount: 6,
    touchTolerance: 0.7,
    wavePattern: 'standard',
  },
  {
    level: 23,
    name: 'Needle Eye Precision',
    objectiveType: 'precision',
    description: 'Pop 172 Needle-Point Micro Orbs',
    targetPops: 172,
    targetActive: 7,
    minSpeed: 620,
    maxSpeed: 685,
    minRadius: 19,
    maxRadius: 22.5,
    spawnIntervalMs: 210,
    tierMultiplier: 2.58,
    initialBalloonsCount: 6,
    touchTolerance: 0.6,
    wavePattern: 'standard',
  },
  {
    level: 24,
    name: 'Tandem Barrage',
    objectiveType: 'pop_all',
    description: 'Pop 176 Tandem High-Speed Balloons',
    targetPops: 176,
    targetActive: 7,
    minSpeed: 635,
    maxSpeed: 700,
    minRadius: 19,
    maxRadius: 22,
    spawnIntervalMs: 205,
    tierMultiplier: 2.65,
    initialBalloonsCount: 6,
    touchTolerance: 0.5,
    wavePattern: 'tandem',
  },

  // -------------------------------------------------------------
  // TIER 4: MASTER ARENA (LEVELS 25 - 32)
  // Very high difficulty, 650-750 px/s, zero-margin precision
  // -------------------------------------------------------------
  {
    level: 25,
    name: 'Mastery Onslaught',
    objectiveType: 'pop_all',
    description: 'Pop 180 Intense Waves',
    targetPops: 180,
    targetActive: 7,
    minSpeed: 650,
    maxSpeed: 715,
    minRadius: 18.5,
    maxRadius: 22,
    spawnIntervalMs: 200,
    tierMultiplier: 2.72,
    initialBalloonsCount: 6,
    touchTolerance: 0.5,
    wavePattern: 'burst',
  },
  {
    level: 26,
    name: 'Solar Flare: Yellow & Orange',
    objectiveType: 'dual_color',
    description: 'Pop 35 Yellow & 35 Orange (184 Total)',
    targetPops: 184,
    targetColor: '#FFD60A',
    targetColorName: 'YELLOW',
    targetColorCount: 35,
    targetColor2: '#FF9500',
    targetColor2Name: 'ORANGE',
    targetColor2Count: 35,
    targetActive: 7,
    minSpeed: 665,
    maxSpeed: 730,
    minRadius: 18.5,
    maxRadius: 21.5,
    spawnIntervalMs: 195,
    tierMultiplier: 2.8,
    initialBalloonsCount: 6,
    touchTolerance: 0.4,
    wavePattern: 'standard',
  },
  {
    level: 27,
    name: 'Iron Grip Combo',
    objectiveType: 'combo_target',
    description: 'Reach 20x Combo & Pop 188 Balloons',
    targetPops: 188,
    requiredCombo: 20,
    targetActive: 7,
    minSpeed: 680,
    maxSpeed: 745,
    minRadius: 18,
    maxRadius: 21,
    spawnIntervalMs: 190,
    tierMultiplier: 2.88,
    initialBalloonsCount: 6,
    touchTolerance: 0.3,
    wavePattern: 'standard',
  },
  {
    level: 28,
    name: 'Cobalt Flash',
    objectiveType: 'target_color',
    description: 'Pop 45 Blue Balloons (192 Total)',
    targetPops: 192,
    targetColor: '#007AFF',
    targetColorName: 'BLUE',
    targetColorCount: 45,
    targetActive: 7,
    minSpeed: 695,
    maxSpeed: 760,
    minRadius: 18,
    maxRadius: 21,
    spawnIntervalMs: 185,
    tierMultiplier: 2.95,
    initialBalloonsCount: 6,
    touchTolerance: 0.3,
    wavePattern: 'speed_contrast',
  },
  {
    level: 29,
    name: 'The Crucible',
    objectiveType: 'pop_all',
    description: 'Survive & Pop 196 Crucible Balloons',
    targetPops: 196,
    targetActive: 7,
    minSpeed: 710,
    maxSpeed: 775,
    minRadius: 18,
    maxRadius: 20.5,
    spawnIntervalMs: 180,
    tierMultiplier: 3.02,
    initialBalloonsCount: 6,
    touchTolerance: 0.2,
    wavePattern: 'cascade',
  },
  {
    level: 30,
    name: 'Emerald & Crimson Clash',
    objectiveType: 'dual_color',
    description: 'Pop 38 Green & 38 Red (200 Total)',
    targetPops: 200,
    targetColor: '#34C759',
    targetColorName: 'GREEN',
    targetColorCount: 38,
    targetColor2: '#FF3B30',
    targetColor2Name: 'RED',
    targetColor2Count: 38,
    targetActive: 7,
    minSpeed: 720,
    maxSpeed: 785,
    minRadius: 17.5,
    maxRadius: 20.5,
    spawnIntervalMs: 175,
    tierMultiplier: 3.1,
    initialBalloonsCount: 6,
    touchTolerance: 0.2,
    wavePattern: 'standard',
  },
  {
    level: 31,
    name: 'Zero Margin Micro',
    objectiveType: 'precision',
    description: 'Pop 204 Zero-Tolerance Balloons',
    targetPops: 204,
    targetActive: 7,
    minSpeed: 730,
    maxSpeed: 795,
    minRadius: 17.5,
    maxRadius: 20,
    spawnIntervalMs: 170,
    tierMultiplier: 3.16,
    initialBalloonsCount: 6,
    touchTolerance: 0.1,
    wavePattern: 'standard',
  },
  {
    level: 32,
    name: 'Supernova Storm',
    objectiveType: 'speed_rush',
    description: 'Pop 208 Hypersonic Balloons',
    targetPops: 208,
    targetActive: 7,
    minSpeed: 740,
    maxSpeed: 805,
    minRadius: 17.5,
    maxRadius: 20,
    spawnIntervalMs: 165,
    tierMultiplier: 3.22,
    initialBalloonsCount: 6,
    touchTolerance: 0.1,
    wavePattern: 'burst',
  },

  // -------------------------------------------------------------
  // TIER 5: ELITE & GRANDMASTER (LEVELS 33 - 40)
  // Maximum championship difficulty, 750-840 px/s, Level 40 Gauntlet
  // -------------------------------------------------------------
  {
    level: 33,
    name: 'Titan Combo',
    objectiveType: 'combo_target',
    description: 'Reach 22x Combo & Pop 212 Balloons',
    targetPops: 212,
    requiredCombo: 22,
    targetActive: 7,
    minSpeed: 745,
    maxSpeed: 810,
    minRadius: 17,
    maxRadius: 20,
    spawnIntervalMs: 160,
    tierMultiplier: 3.28,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'standard',
  },
  {
    level: 34,
    name: 'Purple & Azure Apex',
    objectiveType: 'dual_color',
    description: 'Pop 42 Purple & 42 Blue (215 Total)',
    targetPops: 215,
    targetColor: '#AF52DE',
    targetColorName: 'PURPLE',
    targetColorCount: 42,
    targetColor2: '#007AFF',
    targetColor2Name: 'BLUE',
    targetColor2Count: 42,
    targetActive: 7,
    minSpeed: 750,
    maxSpeed: 815,
    minRadius: 17,
    maxRadius: 19.5,
    spawnIntervalMs: 158,
    tierMultiplier: 3.32,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'standard',
  },
  {
    level: 35,
    name: 'Vortex Tempest',
    objectiveType: 'pop_all',
    description: 'Pop 218 Tempest Balloons',
    targetPops: 218,
    targetActive: 7,
    minSpeed: 755,
    maxSpeed: 820,
    minRadius: 17,
    maxRadius: 19.5,
    spawnIntervalMs: 155,
    tierMultiplier: 3.36,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'cascade',
  },
  {
    level: 36,
    name: 'Crimson Fury',
    objectiveType: 'target_color',
    description: 'Pop 50 Red Balloons (220 Total)',
    targetPops: 220,
    targetColor: '#FF3B30',
    targetColorName: 'RED',
    targetColorCount: 50,
    targetActive: 7,
    minSpeed: 755,
    maxSpeed: 825,
    minRadius: 17,
    maxRadius: 19.5,
    spawnIntervalMs: 152,
    tierMultiplier: 3.4,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'standard',
  },
  {
    level: 37,
    name: 'Tandem Vortex',
    objectiveType: 'pop_all',
    description: 'Pop 222 Tandem Apex Balloons',
    targetPops: 222,
    targetActive: 7,
    minSpeed: 758,
    maxSpeed: 830,
    minRadius: 17,
    maxRadius: 19.5,
    spawnIntervalMs: 150,
    tierMultiplier: 3.43,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'tandem',
  },
  {
    level: 38,
    name: 'Gold & Pink Dual Apex',
    objectiveType: 'dual_color',
    description: 'Pop 45 Yellow & 45 Pink (225 Total)',
    targetPops: 225,
    targetColor: '#FFD60A',
    targetColorName: 'YELLOW',
    targetColorCount: 45,
    targetColor2: '#FF2D55',
    targetColor2Name: 'PINK',
    targetColor2Count: 45,
    targetActive: 7,
    minSpeed: 760,
    maxSpeed: 835,
    minRadius: 17,
    maxRadius: 19,
    spawnIntervalMs: 148,
    tierMultiplier: 3.46,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'standard',
  },
  {
    level: 39,
    name: 'Penultimate Crucible',
    objectiveType: 'speed_rush',
    description: 'Pop 228 Lightning-Fast Balloons',
    targetPops: 228,
    targetActive: 7,
    minSpeed: 762,
    maxSpeed: 838,
    minRadius: 17,
    maxRadius: 19,
    spawnIntervalMs: 146,
    tierMultiplier: 3.48,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'burst',
  },
  {
    level: 40,
    name: 'Grandmaster Gauntlet',
    objectiveType: 'dual_color',
    description: 'The Ultimate Gauntlet: Pop 50 Red & 50 Blue, 25x Combo (230 Total)',
    targetPops: 230,
    targetColor: '#FF3B30',
    targetColorName: 'RED',
    targetColorCount: 50,
    targetColor2: '#007AFF',
    targetColor2Name: 'BLUE',
    targetColor2Count: 50,
    requiredCombo: 25,
    targetActive: 7,
    minSpeed: 765,
    maxSpeed: 840,
    minRadius: 17,
    maxRadius: 19,
    spawnIntervalMs: 145,
    tierMultiplier: 3.5,
    initialBalloonsCount: 6,
    touchTolerance: 0.0,
    wavePattern: 'burst',
  },
];

/**
 * Safely retrieve level configuration by 1-indexed level number (1 to 40)
 */
export function getPopBalloonLevel(levelNum: number): PopBalloonLevelConfig {
  const index = Math.max(0, Math.min(levelNum - 1, POP_BALLOON_LEVELS.length - 1));
  return POP_BALLOON_LEVELS[index];
}

