/**
 * SOCCER PING PONG - 40 Progressive Levels Configuration
 * Deterministic, Non-Random Difficulty Progression with Multiple Independent Constraints:
 * 
 * DIFFICULTY GROUPS:
 * - LEVEL 1–5: Foundation (Grassroots Training)
 * - LEVEL 6–10: Increasing ball speed and target variation (City Stadium)
 * - LEVEL 11–15: Faster attacks and smaller timing windows (National Complex)
 * - LEVEL 16–20: Stronger AI and more unpredictable targeting (Continental Arena)
 * - LEVEL 21–25: Advanced rallies and faster ball movement (Premier Ground)
 * - LEVEL 26–30: High defensive pressure (Elite Arena)
 * - LEVEL 31–35: Expert-level reaction and targeting (International Grand Dome)
 * - LEVEL 36–40: Elite difficulty (World Championship Grand Stadium)
 * 
 * STRICT PROGRESSION:
 * Level 1 is UNLOCKED by default (requiredCumulativeScore: 0).
 * Levels 2–40 are LOCKED until previous level is completed AND cumulative score is met.
 */

import { SoccerLevelConfig } from './types';

const RAW_SOCCER_LEVELS: Omit<SoccerLevelConfig, 'targetGoals'>[] = [
  // =========================================================================
  // GROUP 1: FOUNDATION (Levels 1–5) - Grassroots Training Ground
  // =========================================================================
  {
    level: 1,
    title: 'First Touch Kickoff',
    subtitle: 'Grassroots Pitch • Daylight',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Complex',
    difficultyTier: 'Foundation',
    difficultyStars: 1,
    targetScore: 1000,
    targetRally: 4,
    targetPerfectHits: 1,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.12,
    opponentSkill: 'NOVICE',
    opponentAccuracy: 0.60,
    opponentSpeed: 3.2,
    spinFactor: 0.06,
    timingWindow: 0.26,
    livesAllowed: 3,
    requiredCumulativeScore: 0, // Unlocked by default!
    aiAttackDirectionBias: 0.45,
    aiReactionDelay: 0.12,
    specialRule: 'Swipe horizontally to reposition and defend. Swipe into strike zone to return the ball.',
    specialBallType: 'NONE',
    description: 'Master one-handed horizontal swipe mechanics: defend both wings and strike the ball cleanly.',
  },
  {
    level: 2,
    title: 'Rhythm & Placement',
    subtitle: 'Grassroots Pitch • Morning Sun',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Complex',
    difficultyTier: 'Foundation',
    difficultyStars: 1,
    targetScore: 1500,
    targetRally: 5,
    targetPerfectHits: 2,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.05,
    opponentSkill: 'NOVICE',
    opponentAccuracy: 0.56,
    opponentSpeed: 3.2,
    spinFactor: 0.06,
    timingWindow: 0.28,
    livesAllowed: 3,
    requiredCumulativeScore: 800,
    aiAttackDirectionBias: 0.35,
    aiReactionDelay: 0.14,
    specialRule: 'Swipe left to angle ball left; swipe right to angle ball right.',
    specialBallType: 'NONE',
    description: 'Use directional swipe timing to place returns away from the center of the pitch.',
  },
  {
    level: 3,
    title: 'Wing Guarding',
    subtitle: 'Grassroots Pitch • High Noon',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Complex',
    difficultyTier: 'Foundation',
    difficultyStars: 1,
    targetScore: 2200,
    targetRally: 6,
    targetPerfectHits: 2,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.10,
    opponentSkill: 'NOVICE',
    opponentAccuracy: 0.60,
    opponentSpeed: 3.4,
    spinFactor: 0.08,
    timingWindow: 0.26,
    livesAllowed: 3,
    requiredCumulativeScore: 1800,
    aiAttackDirectionBias: 0.40,
    aiReactionDelay: 0.12,
    specialRule: 'Opponent begins testing the left and right touchlines. Reposition swiftly.',
    specialBallType: 'PRECISION',
    description: 'Keep your paddle active. Anticipate wing returns and block edge angles.',
  },
  {
    level: 4,
    title: 'Center Volley Drill',
    subtitle: 'Grassroots Pitch • Afternoon Light',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Complex',
    difficultyTier: 'Foundation',
    difficultyStars: 2,
    targetScore: 3000,
    targetRally: 7,
    targetPerfectHits: 3,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.15,
    opponentSkill: 'NOVICE',
    opponentAccuracy: 0.63,
    opponentSpeed: 3.6,
    spinFactor: 0.09,
    timingWindow: 0.25,
    livesAllowed: 3,
    requiredCumulativeScore: 3200,
    aiAttackDirectionBias: 0.42,
    aiReactionDelay: 0.11,
    specialRule: 'Time contact when ball is at peak strike height for power shots.',
    specialBallType: 'POWER',
    description: 'Perfect strikes travel with extra velocity, making it tougher for the AI to react.',
  },
  {
    level: 5,
    title: 'Grassroots Final Challenge',
    subtitle: 'Grassroots Pitch • Late Sun',
    stadiumTier: 'training',
    stadiumName: 'Grassroots Training Complex',
    difficultyTier: 'Foundation',
    difficultyStars: 2,
    targetScore: 4000,
    targetRally: 8,
    targetPerfectHits: 3,
    ballSpeed: 'NORMAL',
    ballSpeedMultiplier: 1.20,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.66,
    opponentSpeed: 3.8,
    spinFactor: 0.10,
    timingWindow: 0.24,
    livesAllowed: 3,
    requiredCumulativeScore: 5000,
    aiAttackDirectionBias: 0.45,
    aiReactionDelay: 0.10,
    specialRule: 'Final grassroots test: maintain an 8-hit rally to graduate to City Stadium.',
    specialBallType: 'NONE',
    description: 'Demonstrate solid defense and clean returns to unlock Tier 2.',
  },

  // =========================================================================
  // GROUP 2: INCREASING BALL SPEED & TARGET VARIATION (Levels 6–10) - City Stadium
  // =========================================================================
  {
    level: 6,
    title: 'City Lights Kickoff',
    subtitle: 'City Stadium • Dusk Glow',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Stadium',
    difficultyTier: 'Moderate',
    difficultyStars: 2,
    targetScore: 5200,
    targetRally: 8,
    targetPerfectHits: 3,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.25,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.68,
    opponentSpeed: 4.0,
    spinFactor: 0.12,
    timingWindow: 0.23,
    livesAllowed: 3,
    requiredCumulativeScore: 7200,
    aiAttackDirectionBias: 0.48,
    aiReactionDelay: 0.09,
    specialRule: 'Ball speed increases. React promptly to incoming drives.',
    specialBallType: 'NONE',
    description: 'City floodlights illuminate a faster ball with sharper touchline rebounds.',
  },
  {
    level: 7,
    title: 'Flank Diversion',
    subtitle: 'City Stadium • Twilight',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Stadium',
    difficultyTier: 'Moderate',
    difficultyStars: 2,
    targetScore: 6600,
    targetRally: 9,
    targetPerfectHits: 4,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.28,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.70,
    opponentSpeed: 4.2,
    spinFactor: 0.13,
    timingWindow: 0.22,
    livesAllowed: 3,
    requiredCumulativeScore: 9800,
    aiAttackDirectionBias: 0.52,
    aiReactionDelay: 0.09,
    specialRule: 'AI targets flanks with higher frequency. Watch for abrupt directional switches.',
    specialBallType: 'SPIN',
    description: 'Swipe quickly across the full width to prevent the ball slipping past.',
  },
  {
    level: 8,
    title: 'Angle & Deflection',
    subtitle: 'City Stadium • Evening Match',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Stadium',
    difficultyTier: 'Moderate',
    difficultyStars: 3,
    targetScore: 8200,
    targetRally: 10,
    targetPerfectHits: 4,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.32,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.72,
    opponentSpeed: 4.4,
    spinFactor: 0.15,
    timingWindow: 0.21,
    livesAllowed: 3,
    requiredCumulativeScore: 13000,
    aiAttackDirectionBias: 0.55,
    aiReactionDelay: 0.08,
    specialRule: 'Wall deflections come off at steeper angles.',
    specialBallType: 'NONE',
    description: 'Read the ball bounce off the touchlines before committing your swipe.',
  },
  {
    level: 9,
    title: 'Pace Acceleration',
    subtitle: 'City Stadium • Night Under Lights',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Stadium',
    difficultyTier: 'Moderate',
    difficultyStars: 3,
    targetScore: 10000,
    targetRally: 11,
    targetPerfectHits: 5,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.36,
    opponentSkill: 'INTERMEDIATE',
    opponentAccuracy: 0.74,
    opponentSpeed: 4.6,
    spinFactor: 0.16,
    timingWindow: 0.20,
    livesAllowed: 3,
    requiredCumulativeScore: 16800,
    aiAttackDirectionBias: 0.58,
    aiReactionDelay: 0.08,
    specialRule: 'Rally acceleration triggers earlier during sustained exchanges.',
    specialBallType: 'POWER',
    description: 'Each return adds speed. Stay focused during extended volleys.',
  },
  {
    level: 10,
    title: 'City Derby Championship',
    subtitle: 'City Stadium • Derby Atmosphere',
    stadiumTier: 'city',
    stadiumName: 'Metropolitan City Stadium',
    difficultyTier: 'Moderate',
    difficultyStars: 3,
    targetScore: 12000,
    targetRally: 12,
    targetPerfectHits: 5,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.40,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.76,
    opponentSpeed: 4.8,
    spinFactor: 0.18,
    timingWindow: 0.20,
    livesAllowed: 3,
    requiredCumulativeScore: 21200,
    aiAttackDirectionBias: 0.60,
    aiReactionDelay: 0.07,
    specialRule: 'Derby rival AI: rapid wing switches and disciplined returns.',
    specialBallType: 'BONUS',
    description: 'Win the city derby to earn promotion to the National Sports Complex.',
  },

  // =========================================================================
  // GROUP 3: FASTER ATTACKS & SMALLER TIMING WINDOWS (Levels 11–15) - National Complex
  // =========================================================================
  {
    level: 11,
    title: 'National Stage Debut',
    subtitle: 'National Complex • Floodlights',
    stadiumTier: 'national',
    stadiumName: 'National Sports Complex',
    difficultyTier: 'Challenging',
    difficultyStars: 3,
    targetScore: 14500,
    targetRally: 12,
    targetPerfectHits: 5,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.44,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.78,
    opponentSpeed: 5.0,
    spinFactor: 0.20,
    timingWindow: 0.19,
    livesAllowed: 2, // Lives reduced to 2 for tighter competition
    requiredCumulativeScore: 26200,
    aiAttackDirectionBias: 0.62,
    aiReactionDelay: 0.07,
    specialRule: 'Lives reduced to 2. Timing sweet spot is narrower.',
    specialBallType: 'NONE',
    description: 'National arena atmosphere. Strikes must be timed cleanly to avoid weak returns.',
  },
  {
    level: 12,
    title: 'Curving Trajectory',
    subtitle: 'National Complex • Electric Atmosphere',
    stadiumTier: 'national',
    stadiumName: 'National Sports Complex',
    difficultyTier: 'Challenging',
    difficultyStars: 3,
    targetScore: 17200,
    targetRally: 13,
    targetPerfectHits: 6,
    ballSpeed: 'FAST',
    ballSpeedMultiplier: 1.48,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.80,
    opponentSpeed: 5.2,
    spinFactor: 0.22,
    timingWindow: 0.18,
    livesAllowed: 2,
    requiredCumulativeScore: 32000,
    aiAttackDirectionBias: 0.65,
    aiReactionDelay: 0.06,
    specialRule: 'AI strikes with subtle spin, altering bounce angle.',
    specialBallType: 'SPIN',
    description: 'Anticipate the curving spin. Align your swipe with the ball line of flight.',
  },
  {
    level: 13,
    title: 'Reflex Threshold',
    subtitle: 'National Complex • High Stakes',
    stadiumTier: 'national',
    stadiumName: 'National Sports Complex',
    difficultyTier: 'Challenging',
    difficultyStars: 4,
    targetScore: 20200,
    targetRally: 14,
    targetPerfectHits: 6,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.52,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.82,
    opponentSpeed: 5.4,
    spinFactor: 0.24,
    timingWindow: 0.18,
    livesAllowed: 2,
    requiredCumulativeScore: 38600,
    aiAttackDirectionBias: 0.68,
    aiReactionDelay: 0.06,
    specialRule: 'Ball speed transitions into VERY FAST range.',
    specialBallType: 'POWER',
    description: 'Short reaction time requires holding defensive readiness on both touchlines.',
  },
  {
    level: 14,
    title: 'Tight Angle Defense',
    subtitle: 'National Complex • Full House',
    stadiumTier: 'national',
    stadiumName: 'National Sports Complex',
    difficultyTier: 'Challenging',
    difficultyStars: 4,
    targetScore: 23500,
    targetRally: 15,
    targetPerfectHits: 7,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.55,
    opponentSkill: 'ADVANCED',
    opponentAccuracy: 0.83,
    opponentSpeed: 5.6,
    spinFactor: 0.25,
    timingWindow: 0.17,
    livesAllowed: 2,
    requiredCumulativeScore: 46000,
    aiAttackDirectionBias: 0.70,
    aiReactionDelay: 0.05,
    specialRule: 'Extreme wing shots test maximum paddle reach.',
    specialBallType: 'PRECISION',
    description: 'Execute edge saves with full lateral swipes to protect the post corners.',
  },
  {
    level: 15,
    title: 'National Cup Semi-Final',
    subtitle: 'National Complex • Championship Eve',
    stadiumTier: 'national',
    stadiumName: 'National Sports Complex',
    difficultyTier: 'Challenging',
    difficultyStars: 4,
    targetScore: 27000,
    targetRally: 16,
    targetPerfectHits: 7,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.58,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.85,
    opponentSpeed: 5.8,
    spinFactor: 0.26,
    timingWindow: 0.17,
    livesAllowed: 2,
    requiredCumulativeScore: 54200,
    aiAttackDirectionBias: 0.72,
    aiReactionDelay: 0.05,
    specialRule: 'AI dynamically counters your favored return direction.',
    specialBallType: 'NONE',
    description: 'Vary your attack angles. Repetitive returns will be intercepted and punished.',
  },

  // =========================================================================
  // GROUP 4: STRONGER AI & UNPREDICTABLE TARGETING (Levels 16–20) - Continental Arena
  // =========================================================================
  {
    level: 16,
    title: 'Continental Kickoff',
    subtitle: 'Continental Arena • European Night',
    stadiumTier: 'continental',
    stadiumName: 'Continental Championship Arena',
    difficultyTier: 'Advanced',
    difficultyStars: 4,
    targetScore: 31000,
    targetRally: 16,
    targetPerfectHits: 8,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.62,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.86,
    opponentSpeed: 6.0,
    spinFactor: 0.28,
    timingWindow: 0.16,
    livesAllowed: 2,
    requiredCumulativeScore: 63200,
    aiAttackDirectionBias: 0.75,
    aiReactionDelay: 0.04,
    specialRule: 'AI adapts its attack dynamically to your position.',
    specialBallType: 'POWER',
    description: 'Guard the center while remaining poised to spring toward either flank.',
  },
  {
    level: 17,
    title: 'Tactical Deception',
    subtitle: 'Continental Arena • Spotlight Focus',
    stadiumTier: 'continental',
    stadiumName: 'Continental Championship Arena',
    difficultyTier: 'Advanced',
    difficultyStars: 4,
    targetScore: 35500,
    targetRally: 17,
    targetPerfectHits: 8,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.65,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.88,
    opponentSpeed: 6.2,
    spinFactor: 0.30,
    timingWindow: 0.16,
    livesAllowed: 2,
    requiredCumulativeScore: 73000,
    aiAttackDirectionBias: 0.78,
    aiReactionDelay: 0.04,
    specialRule: 'AI disguises attack direction until late in the swing.',
    specialBallType: 'SPIN',
    description: 'Watch the ball trajectory directly, not just the opponent striker.',
  },
  {
    level: 18,
    title: 'Speed & Resilience',
    subtitle: 'Continental Arena • Roaring Stadium',
    stadiumTier: 'continental',
    stadiumName: 'Continental Championship Arena',
    difficultyTier: 'Advanced',
    difficultyStars: 4,
    targetScore: 40500,
    targetRally: 18,
    targetPerfectHits: 9,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.68,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.89,
    opponentSpeed: 6.4,
    spinFactor: 0.32,
    timingWindow: 0.15,
    livesAllowed: 2,
    requiredCumulativeScore: 83800,
    aiAttackDirectionBias: 0.80,
    aiReactionDelay: 0.03,
    specialRule: 'Sustained rallies require continuous repositioning.',
    specialBallType: 'NONE',
    description: 'Endurance and sharp timing define the continental tournament standard.',
  },
  {
    level: 19,
    title: 'Apex Pressure',
    subtitle: 'Continental Arena • High Tension',
    stadiumTier: 'continental',
    stadiumName: 'Continental Championship Arena',
    difficultyTier: 'Advanced',
    difficultyStars: 5,
    targetScore: 46000,
    targetRally: 19,
    targetPerfectHits: 9,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.72,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.90,
    opponentSpeed: 6.6,
    spinFactor: 0.34,
    timingWindow: 0.15,
    livesAllowed: 2,
    requiredCumulativeScore: 95500,
    aiAttackDirectionBias: 0.82,
    aiReactionDelay: 0.03,
    specialRule: 'Timing window decreases to 0.15s. Clean strikes required.',
    specialBallType: 'PRECISION',
    description: 'Precision timing generates power shots capable of breaking through the AI.',
  },
  {
    level: 20,
    title: 'Continental Cup Final',
    subtitle: 'Continental Arena • Trophy Night',
    stadiumTier: 'continental',
    stadiumName: 'Continental Championship Arena',
    difficultyTier: 'Advanced',
    difficultyStars: 5,
    targetScore: 52000,
    targetRally: 20,
    targetPerfectHits: 10,
    ballSpeed: 'VERY FAST',
    ballSpeedMultiplier: 1.75,
    opponentSkill: 'EXPERT',
    opponentAccuracy: 0.91,
    opponentSpeed: 6.8,
    spinFactor: 0.35,
    timingWindow: 0.14,
    livesAllowed: 2,
    requiredCumulativeScore: 108200,
    aiAttackDirectionBias: 0.84,
    aiReactionDelay: 0.02,
    specialRule: '20-rally target. Lift the Continental Trophy upon victory.',
    specialBallType: 'BONUS',
    description: 'Defeat the continental elite to unlock the Premier division.',
  },

  // =========================================================================
  // GROUP 5: ADVANCED RALLIES & FASTER BALL MOVEMENT (Levels 21–25) - Premier Ground
  // =========================================================================
  {
    level: 21,
    title: 'Premier Ground Kickoff',
    subtitle: 'Premier Stadium • Golden Turf',
    stadiumTier: 'premier',
    stadiumName: 'Premier Championship Grounds',
    difficultyTier: 'Pressure',
    difficultyStars: 5,
    targetScore: 58500,
    targetRally: 20,
    targetPerfectHits: 10,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.78,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.92,
    opponentSpeed: 7.0,
    spinFactor: 0.36,
    timingWindow: 0.14,
    livesAllowed: 2,
    requiredCumulativeScore: 122000,
    aiAttackDirectionBias: 0.85,
    aiReactionDelay: 0.02,
    specialRule: 'EXTREME ball speed begins. Rapid swipe reaction is paramount.',
    specialBallType: 'POWER',
    description: 'Welcome to the Premier division. Ball velocities exceed all prior tiers.',
  },
  {
    level: 22,
    title: 'Rapid Fire Volleys',
    subtitle: 'Premier Stadium • High Velocity',
    stadiumTier: 'premier',
    stadiumName: 'Premier Championship Grounds',
    difficultyTier: 'Pressure',
    difficultyStars: 5,
    targetScore: 65500,
    targetRally: 21,
    targetPerfectHits: 10,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.82,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.92,
    opponentSpeed: 7.2,
    spinFactor: 0.38,
    timingWindow: 0.13,
    livesAllowed: 2,
    requiredCumulativeScore: 136800,
    aiAttackDirectionBias: 0.86,
    aiReactionDelay: 0.02,
    specialRule: 'Sustained fast returns across both flanks without pause.',
    specialBallType: 'NONE',
    description: 'Keep your thumb moving smoothly across the swipe line for responsive interception.',
  },
  {
    level: 23,
    title: 'Corner Pinhole',
    subtitle: 'Premier Stadium • Precision Stakes',
    stadiumTier: 'premier',
    stadiumName: 'Premier Championship Grounds',
    difficultyTier: 'Pressure',
    difficultyStars: 5,
    targetScore: 73000,
    targetRally: 22,
    targetPerfectHits: 11,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.85,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.93,
    opponentSpeed: 7.4,
    spinFactor: 0.40,
    timingWindow: 0.13,
    livesAllowed: 2,
    requiredCumulativeScore: 152800,
    aiAttackDirectionBias: 0.88,
    aiReactionDelay: 0.01,
    specialRule: 'AI places drives within centimeters of the goal corners.',
    specialBallType: 'PRECISION',
    description: 'Defend with maximum extension to tip shots away from the net.',
  },
  {
    level: 24,
    title: 'Spin Mastery',
    subtitle: 'Premier Stadium • Swerving Ball',
    stadiumTier: 'premier',
    stadiumName: 'Premier Championship Grounds',
    difficultyTier: 'Pressure',
    difficultyStars: 5,
    targetScore: 81000,
    targetRally: 23,
    targetPerfectHits: 11,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.88,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.94,
    opponentSpeed: 7.6,
    spinFactor: 0.42,
    timingWindow: 0.12,
    livesAllowed: 2,
    requiredCumulativeScore: 170000,
    aiAttackDirectionBias: 0.89,
    aiReactionDelay: 0.01,
    specialRule: 'High spin factor curves ball sharply after wall contact.',
    specialBallType: 'SPIN',
    description: 'Calculate touchline deflections in real time before executing your swipe.',
  },
  {
    level: 25,
    title: 'Premier Division Shield',
    subtitle: 'Premier Stadium • Shield Defense',
    stadiumTier: 'premier',
    stadiumName: 'Premier Championship Grounds',
    difficultyTier: 'Pressure',
    difficultyStars: 5,
    targetScore: 89500,
    targetRally: 24,
    targetPerfectHits: 12,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.92,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.94,
    opponentSpeed: 7.8,
    spinFactor: 0.44,
    timingWindow: 0.12,
    livesAllowed: 2,
    requiredCumulativeScore: 188500,
    aiAttackDirectionBias: 0.90,
    aiReactionDelay: 0.01,
    specialRule: '24-rally benchmark to secure the Premier Championship Shield.',
    specialBallType: 'POWER',
    description: 'Mastery of rapid one-hand swiping and directional placement is required.',
  },

  // =========================================================================
  // GROUP 6: HIGH DEFENSIVE PRESSURE (Levels 26–30) - Elite Arena
  // =========================================================================
  {
    level: 26,
    title: 'Elite Arena Trial',
    subtitle: 'Elite Arena • Midnight Blue',
    stadiumTier: 'elite',
    stadiumName: 'Elite Arena Stadium',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 98500,
    targetRally: 24,
    targetPerfectHits: 12,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.95,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.95,
    opponentSpeed: 8.0,
    spinFactor: 0.45,
    timingWindow: 0.12,
    livesAllowed: 1, // Reduced to 1 life: sudden death pressure!
    requiredCumulativeScore: 208500,
    aiAttackDirectionBias: 0.91,
    aiReactionDelay: 0.0,
    specialRule: '1 LIFE ONLY: A single missed ball concludes the match.',
    specialBallType: 'NONE',
    description: 'Zero margin for error. Absolute defensive concentration is required.',
  },
  {
    level: 27,
    title: 'Cross-Pitch Barrage',
    subtitle: 'Elite Arena • Rapid Alternation',
    stadiumTier: 'elite',
    stadiumName: 'Elite Arena Stadium',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 108000,
    targetRally: 25,
    targetPerfectHits: 13,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 1.98,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.95,
    opponentSpeed: 8.2,
    spinFactor: 0.46,
    timingWindow: 0.11,
    livesAllowed: 1,
    requiredCumulativeScore: 230000,
    aiAttackDirectionBias: 0.92,
    aiReactionDelay: 0.0,
    specialRule: 'AI alternates extreme left and extreme right returns continuously.',
    specialBallType: 'POWER',
    description: 'Full width sprints across the pitch with each volley.',
  },
  {
    level: 28,
    title: 'Counter-Strike Matrix',
    subtitle: 'Elite Arena • Intense Rhythm',
    stadiumTier: 'elite',
    stadiumName: 'Elite Arena Stadium',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 118000,
    targetRally: 26,
    targetPerfectHits: 13,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.02,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.96,
    opponentSpeed: 8.4,
    spinFactor: 0.47,
    timingWindow: 0.11,
    livesAllowed: 1,
    requiredCumulativeScore: 253000,
    aiAttackDirectionBias: 0.93,
    aiReactionDelay: 0.0,
    specialRule: 'Ball speed multiplier exceeds 2.0x base physics scale.',
    specialBallType: 'SPIN',
    description: 'Instant reflex reactions required on every single ball flight.',
  },
  {
    level: 29,
    title: 'Wing Ambush',
    subtitle: 'Elite Arena • High Precision',
    stadiumTier: 'elite',
    stadiumName: 'Elite Arena Stadium',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 129000,
    targetRally: 27,
    targetPerfectHits: 14,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.05,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.96,
    opponentSpeed: 8.5,
    spinFactor: 0.48,
    timingWindow: 0.11,
    livesAllowed: 1,
    requiredCumulativeScore: 277500,
    aiAttackDirectionBias: 0.94,
    aiReactionDelay: 0.0,
    specialRule: 'AI attacks strike zone corners with 94% direction bias.',
    specialBallType: 'PRECISION',
    description: 'Never get caught flat-footed in the center. Anticipate flank rushes.',
  },
  {
    level: 30,
    title: 'Elite Arena Masters Cup',
    subtitle: 'Elite Arena • Championship Gold',
    stadiumTier: 'elite',
    stadiumName: 'Elite Arena Stadium',
    difficultyTier: 'Expert',
    difficultyStars: 5,
    targetScore: 140500,
    targetRally: 28,
    targetPerfectHits: 14,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.08,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.97,
    opponentSpeed: 8.6,
    spinFactor: 0.49,
    timingWindow: 0.10,
    livesAllowed: 1,
    requiredCumulativeScore: 303500,
    aiAttackDirectionBias: 0.94,
    aiReactionDelay: 0.0,
    specialRule: '28 sustained rallies under 1-life sudden death conditions.',
    specialBallType: 'BONUS',
    description: 'Triumph over the Elite division to enter the International Grand Dome.',
  },

  // =========================================================================
  // GROUP 7: EXPERT-LEVEL REACTION & TARGETING (Levels 31–35) - International Grand Dome
  // =========================================================================
  {
    level: 31,
    title: 'Grand Dome Premiere',
    subtitle: 'Grand Dome • Diamond Lighting',
    stadiumTier: 'international',
    stadiumName: 'International Grand Dome',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 153000,
    targetRally: 28,
    targetPerfectHits: 15,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.12,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.97,
    opponentSpeed: 8.8,
    spinFactor: 0.50,
    timingWindow: 0.10,
    livesAllowed: 1,
    requiredCumulativeScore: 331500,
    aiAttackDirectionBias: 0.95,
    aiReactionDelay: 0.0,
    specialRule: 'International Grand Dome rules: supreme velocity and accuracy.',
    specialBallType: 'POWER',
    description: 'Elite international AI opponents test your highest physical limits.',
  },
  {
    level: 32,
    title: 'Sub-Zero Reaction',
    subtitle: 'Grand Dome • Laser Precision',
    stadiumTier: 'international',
    stadiumName: 'International Grand Dome',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 166000,
    targetRally: 29,
    targetPerfectHits: 15,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.15,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.97,
    opponentSpeed: 9.0,
    spinFactor: 0.51,
    timingWindow: 0.10,
    livesAllowed: 1,
    requiredCumulativeScore: 361500,
    aiAttackDirectionBias: 0.95,
    aiReactionDelay: 0.0,
    specialRule: 'Reaction delay eliminated: AI positions immediately upon your contact.',
    specialBallType: 'SPIN',
    description: 'Use directional swipe to catch the AI moving against its momentum.',
  },
  {
    level: 33,
    title: 'Orbital Velocity',
    subtitle: 'Grand Dome • Maximum Acceleration',
    stadiumTier: 'international',
    stadiumName: 'International Grand Dome',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 180000,
    targetRally: 30,
    targetPerfectHits: 16,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.18,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.98,
    opponentSpeed: 9.1,
    spinFactor: 0.52,
    timingWindow: 0.09,
    livesAllowed: 1,
    requiredCumulativeScore: 393500,
    aiAttackDirectionBias: 0.96,
    aiReactionDelay: 0.0,
    specialRule: '30-rally target under extreme international tempo.',
    specialBallType: 'NONE',
    description: 'Sustain flawless timing across three dozen high-speed exchanges.',
  },
  {
    level: 34,
    title: 'The Edge of Touchline',
    subtitle: 'Grand Dome • Millimeter Margin',
    stadiumTier: 'international',
    stadiumName: 'International Grand Dome',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 195000,
    targetRally: 31,
    targetPerfectHits: 16,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.22,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.98,
    opponentSpeed: 9.2,
    spinFactor: 0.53,
    timingWindow: 0.09,
    livesAllowed: 1,
    requiredCumulativeScore: 427500,
    aiAttackDirectionBias: 0.96,
    aiReactionDelay: 0.0,
    specialRule: 'Every return targets within 10% of pitch perimeter touchlines.',
    specialBallType: 'PRECISION',
    description: 'Defend edge-to-edge with relentless one-hand swipe dexterity.',
  },
  {
    level: 35,
    title: 'International Masters Trophy',
    subtitle: 'Grand Dome • Crown of Masters',
    stadiumTier: 'international',
    stadiumName: 'International Grand Dome',
    difficultyTier: 'Master',
    difficultyStars: 5,
    targetScore: 211000,
    targetRally: 32,
    targetPerfectHits: 17,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.25,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.98,
    opponentSpeed: 9.3,
    spinFactor: 0.54,
    timingWindow: 0.09,
    livesAllowed: 1,
    requiredCumulativeScore: 463500,
    aiAttackDirectionBias: 0.97,
    aiReactionDelay: 0.0,
    specialRule: 'Qualify for the World Championship Grand Stadium with 32 rallies.',
    specialBallType: 'BONUS',
    description: 'Claim the International Masters Trophy to enter the ultimate final tier.',
  },

  // =========================================================================
  // GROUP 8: ELITE DIFFICULTY (Levels 36–40) - World Championship Grand Stadium
  // =========================================================================
  {
    level: 36,
    title: 'World Grand Stadium Kickoff',
    subtitle: 'World Stadium • Pure Gold Ambience',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Elite',
    difficultyStars: 5,
    targetScore: 228000,
    targetRally: 33,
    targetPerfectHits: 17,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.28,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.98,
    opponentSpeed: 9.4,
    spinFactor: 0.55,
    timingWindow: 0.08,
    livesAllowed: 1,
    requiredCumulativeScore: 501500,
    aiAttackDirectionBias: 0.97,
    aiReactionDelay: 0.0,
    specialRule: 'THE PINNACLE: 1 life, 2.28x speed multiplier, 0.08s sweet spot.',
    specialBallType: 'POWER',
    description: 'The premier soccer ping pong competitors of the world converge here.',
  },
  {
    level: 37,
    title: 'Supersonic Exchange',
    subtitle: 'World Stadium • Stadium Roar',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Elite',
    difficultyStars: 5,
    targetScore: 246000,
    targetRally: 34,
    targetPerfectHits: 18,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.32,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.99,
    opponentSpeed: 9.5,
    spinFactor: 0.56,
    timingWindow: 0.08,
    livesAllowed: 1,
    requiredCumulativeScore: 541500,
    aiAttackDirectionBias: 0.97,
    aiReactionDelay: 0.0,
    specialRule: 'World-record ball velocity and 99% AI intercept accuracy.',
    specialBallType: 'SPIN',
    description: 'Unflinching discipline: swipe precisely at the moment of arrival.',
  },
  {
    level: 38,
    title: 'Penultimate Showdown',
    subtitle: 'World Stadium • Eve of Immortality',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Elite',
    difficultyStars: 5,
    targetScore: 265000,
    targetRally: 35,
    targetPerfectHits: 19,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.36,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.99,
    opponentSpeed: 9.6,
    spinFactor: 0.57,
    timingWindow: 0.08,
    livesAllowed: 1,
    requiredCumulativeScore: 583500,
    aiAttackDirectionBias: 0.98,
    aiReactionDelay: 0.0,
    specialRule: '35 consecutive rallies required to advance to the Grand Final.',
    specialBallType: 'PRECISION',
    description: 'Defend every touchline flank under unbearable championship pressure.',
  },
  {
    level: 39,
    title: 'World Champion Semi-Final',
    subtitle: 'World Stadium • Under The Golden Stars',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Elite',
    difficultyStars: 5,
    targetScore: 285000,
    targetRally: 36,
    targetPerfectHits: 20,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.40,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.99,
    opponentSpeed: 9.8,
    spinFactor: 0.58,
    timingWindow: 0.07,
    livesAllowed: 1,
    requiredCumulativeScore: 627500,
    aiAttackDirectionBias: 0.98,
    aiReactionDelay: 0.0,
    specialRule: 'AI striker plays with 0.07s reaction threshold. Pure reflexes required.',
    specialBallType: 'POWER',
    description: 'One match remains before reaching soccer ping pong immortality.',
  },
  {
    level: 40,
    title: 'World Grand Master Finale',
    subtitle: 'World Stadium • The Golden Football Crown',
    stadiumTier: 'championship',
    stadiumName: 'World Championship Grand Stadium',
    difficultyTier: 'Elite',
    difficultyStars: 5,
    targetScore: 310000,
    targetRally: 38,
    targetPerfectHits: 22,
    ballSpeed: 'EXTREME',
    ballSpeedMultiplier: 2.45,
    opponentSkill: 'MASTER',
    opponentAccuracy: 0.99,
    opponentSpeed: 10.0,
    spinFactor: 0.60,
    timingWindow: 0.07,
    livesAllowed: 1,
    requiredCumulativeScore: 673500,
    aiAttackDirectionBias: 0.99,
    aiReactionDelay: 0.0,
    specialRule: 'THE ULTIMATE LEVEL 40 FINALE: Defeat the Grand Master AI for the World Golden Trophy.',
    specialBallType: 'BONUS',
    description: 'The highest pinnacle of Soccer Ping-Pong speed, skill, and precision. Become a legend!',
  },
];

export const SOCCER_LEVELS: SoccerLevelConfig[] = RAW_SOCCER_LEVELS.map((lvl) => ({
  ...lvl,
  targetGoals: lvl.level <= 5 ? 3 : lvl.level <= 20 ? 4 : 5,
}));
