/**
 * ============================================================================
 * [INTERNAL NOTICE: DEMO DATA LAYER]
 * This file contains strictly labeled simulated demonstration data for
 * TelePlay Ethiopia. No real customer personal data or production records are
 * exposed. It ensures full offline portal functionality and predictable UI preview.
 * ============================================================================
 */

import {
  GameDefinition,
  LeaderboardEntry,
  Tournament,
  DailyRewardItem,
  UserProfile,
} from '../types';
import { getGameArtworkUrl } from './gameArtwork';

export const DEMO_USER_PROFILE: UserProfile = {
  id: 'usr_demo_telebirr_001',
  phoneNumber: '0911428890',
  displayName: 'Abebe B.',
  avatarId: 'avatar_eagle',
  isRegistered: true,
  telebirrLinked: true,
  telebirrId: 'TB-894210',
  telebirrBalance: 145.50, // 145.50 ETB in telebirr account
  coins: 50, // 50 GameON Coins
  xp: 3850,
  level: 5,
  energy: 5,
  maxEnergy: 5,
  lastEnergyRefillTimestamp: Date.now(),
  subscription: {
    plan: 'daily',
    isActive: true,
    expiresAt: Date.now() + 24 * 60 * 60 * 1000,
    autoRenew: true,
  },
  streak: {
    current: 4,
    lastClaimedDate: '',
    hasClaimedToday: false,
  },
  highScores: {
    'candy-blast': 380,
    'world-legends': 340,
    'juicy-match': 390,
    'solitaire': 320,
    'puzzle-block': 350,
    'sorting-balls': 280,
    'emoji-sorting-ball': 320,
    'emoji-fun': 320,
    'emoji-iq': 350,
    'bubble-shooter': 310,
    'memory-match': 290,
    'helix-jump': 400,
    'crazy-colors': 360,
    'color-rush': 330,
    'knife-madness': 310,
    'archery-strike': 295,
    'fruit-slice': 375,
    'hill-rider': 340,
    'moto-race': 385,
    'soccer-ping-pong': 360,
    'soccer-shooter': 340,
    'dama': 310,
    'pop-piano': 350,
  },
  achievements: ['first_win', 'streak_3', 'telebirr_link', 'top_100'],
  matchesPlayed: 42,
  trophiesCount: 8,
};

export const INITIAL_GUEST_PROFILE: UserProfile = {
  id: 'usr_guest_' + Math.random().toString(36).substring(2, 8),
  phoneNumber: '',
  displayName: 'Guest Player',
  avatarId: 'avatar_runner',
  isRegistered: false,
  telebirrLinked: false,
  telebirrBalance: 0,
  coins: 100,
  xp: 0,
  level: 1,
  energy: 5,
  maxEnergy: 5,
  lastEnergyRefillTimestamp: Date.now(),
  subscription: {
    plan: 'free',
    isActive: false,
    autoRenew: false,
  },
  streak: {
    current: 1,
    lastClaimedDate: '',
    hasClaimedToday: false,
  },
  highScores: {},
  achievements: [],
  matchesPlayed: 0,
  trophiesCount: 0,
};

/**
 * 6 Independent Modular Games Definition
 */
export const SIX_MODULAR_GAMES: GameDefinition[] = [
  {
    id: 'candy-blast',
    title: 'Candy Crush',
    titleAmharic: 'ኬንዲ ክራሽ',
    category: 'puzzle',
    genre: 'Puzzle',
    difficulty: 'Easy',
    tagline: 'Match vibrant Ethiopian honey candies and sweet jellies!',
    description: 'A delightful confectionery match-3 puzzle. Swap and connect 3 or more delicious honey candies to trigger colorful cascades, sweet sugar blasts, and massive combo multipliers.',
    thumbnailUrl: getGameArtworkUrl('candy-blast'),
    bannerUrl: getGameArtworkUrl('candy-blast'),
    primaryColor: '#e11d48',
    secondaryColor: '#70C922',
    rating: 4.9,
    playsCount: 154200,
    energyCost: 1,
    featured: true,
    isTrending: true,
    instructions: [
      'Swap adjacent candies to create horizontal or vertical rows of 3 or more matching colors',
      'Match 4 candies to create explosive Striped Candies that clear entire rows',
      'Combine 5 candies to form a Rainbow Honey Bomb that blasts all candies of the same color',
    ],
    controlsDescription: 'Tap and swipe candies to swap positions.',
  },
  {
    id: 'color-rush',
    title: 'Color Rush',
    titleAmharic: 'ከለር ረሽ',
    category: 'reaction',
    genre: 'Reaction',
    difficulty: 'Hard',
    tagline: 'Test your lightning-fast reflex timing against the chromatic rush!',
    description: 'High-speed reflex reaction test. Match incoming chromatic neon pulses and rotating color gates before the countdown runs out. Speed increases with every successful combo!',
    thumbnailUrl: getGameArtworkUrl('color-rush'),
    bannerUrl: getGameArtworkUrl('color-rush'),
    primaryColor: '#70C922',
    secondaryColor: '#0B3B70',
    rating: 4.8,
    playsCount: 132600,
    energyCost: 1,
    featured: true,
    isTrending: true,
    instructions: [
      'Watch the target color flash on screen and tap the matching color paddle immediately',
      'Keep your reaction streak alive to trigger the 3x Multiplier Fever mode',
      'Avoid incorrect taps which instantly break your combo streak and cost a life',
    ],
    controlsDescription: 'Tap color buttons or press Arrow keys (Up/Down/Left/Right) in rapid sequence.',
  },
  {
    id: 'world-legends',
    title: 'Word Legend',
    titleAmharic: 'ዎርድ ሌጀንድ',
    category: 'knowledge',
    genre: 'Knowledge',
    difficulty: 'Medium',
    tagline: 'Journey through epic world history, mythology, and legendary lore!',
    description: 'An immersive knowledge and trivia adventure. Answer intriguing questions on world civilizations, ancient mythology, Ethiopian imperial heritage, and legendary world events.',
    thumbnailUrl: getGameArtworkUrl('world-legends'),
    bannerUrl: getGameArtworkUrl('world-legends'),
    primaryColor: '#f59e0b',
    secondaryColor: '#05234A',
    rating: 4.9,
    playsCount: 98700,
    energyCost: 1,
    featured: false,
    isNew: true,
    instructions: [
      'Answer 10 rapid multiple-choice legend questions before the 15-second timer runs out',
      'Score bonus speed points by answering accurately within the first 3 seconds',
      'Use 50:50 and Clue lifelines when facing complex historical questions',
    ],
    controlsDescription: 'Tap the correct historical answer card.',
  },
  {
    id: 'pop-piano',
    title: 'Piano',
    titleAmharic: 'ፖፕ ፒያኖ',
    category: 'music',
    genre: 'Music',
    difficulty: 'Medium',
    tagline: 'Tap falling glowing keys to chart-topping melodies and rhythms!',
    description: 'Fast rhythm piano tile gameplay featuring popular Ethiopian pop songs, acoustic chords, and global hits. Tap descending piano tiles in sync with the beat to achieve perfect harmony.',
    thumbnailUrl: getGameArtworkUrl('pop-piano'),
    bannerUrl: getGameArtworkUrl('pop-piano'),
    primaryColor: '#8b5cf6',
    secondaryColor: '#70C922',
    rating: 4.9,
    playsCount: 187400,
    energyCost: 1,
    featured: true,
    isTrending: true,
    instructions: [
      'Tap the descending piano tiles exactly as they hit the rhythm baseline bar',
      'Hold down long note tiles for sustained chord points and acoustic vibrato',
      'Do not tap empty spaces or let any piano note pass the baseline without tapping',
    ],
    controlsDescription: 'Tap keys on screen or use keyboard keys [D] [F] [J] [K].',
  },
  {
    id: 'hill-rider',
    title: 'Hill Climb',
    titleAmharic: 'ሂል ክላይምብ',
    category: 'racing',
    genre: 'Racing',
    difficulty: 'Medium',
    tagline: 'Conquer steep highland ridges and rugged mountain terrains!',
    description: 'Physics-based 2D hill climbing driving game. Control acceleration and vehicle pitch balance over steep Ethiopian highland hills, rocky gorges, and suspension bridges to reach the summit.',
    thumbnailUrl: getGameArtworkUrl('hill-rider'),
    bannerUrl: getGameArtworkUrl('hill-rider'),
    primaryColor: '#0B3B70',
    secondaryColor: '#70C922',
    rating: 4.7,
    playsCount: 119800,
    energyCost: 1,
    featured: false,
    isNew: true,
    instructions: [
      'Hold Gas (Right) to accelerate uphill and release on steep drops to maintain traction',
      'Use Brake / Tilt (Left) to slow down and stabilize buggy balance mid-air',
      'Collect fuel jerrycans along the track before your vehicle engine runs dry',
    ],
    controlsDescription: 'Tap/hold Gas (Right) & Brake (Left) on screen, or use Left/Right arrow keys.',
  },
  {
    id: 'archery-strike',
    title: 'Pop Ballon',
    titleAmharic: 'ፖፕ ባሎን',
    category: 'arcade',
    genre: 'Arcade',
    difficulty: 'Medium',
    tagline: 'Tap and pop the falling colored balloons before they reach the bottom!',
    description: 'Fast-paced reflex game. Tap and pop vibrant falling colored circles while testing your speed, rhythm, and accuracy before any balloons slip past.',
    thumbnailUrl: getGameArtworkUrl('archery-strike'),
    bannerUrl: getGameArtworkUrl('archery-strike'),
    primaryColor: '#EC4899',
    secondaryColor: '#3B82F6',
    rating: 4.9,
    playsCount: 168000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    instructions: [
      'Tap or click directly on each falling colored balloon to pop it instantly',
      'Do not tap empty background space or the decorative center ring',
      'Prevent balloons from escaping past the bottom to preserve your 3 hearts',
    ],
    controlsDescription: 'Tap or click falling colored balloons to pop.',
  },
  {
    id: 'memory-match',
    title: 'Picture Match',
    titleAmharic: 'ሜሞሪ ማች',
    category: 'puzzle',
    genre: 'Puzzle',
    difficulty: 'Challenging',
    tagline: 'Test your photographic memory and uncover legendary matching relics!',
    description: 'A premium, high-stakes memory matching experience. Flip beautifully beveled 3D cards, remember mysterious symbols and ancient artifacts, and uncover matching pairs across challenging stages.',
    thumbnailUrl: getGameArtworkUrl('memory-match'),
    bannerUrl: getGameArtworkUrl('memory-match'),
    primaryColor: '#0B3B70',
    secondaryColor: '#8BCB3D',
    rating: 4.95,
    playsCount: 142000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Tap face-down cards to reveal their hidden ancient symbol',
      'Find and match identical pairs to clear the board before time runs out',
      'Build consecutive match streaks to multiply your score and earn 3 gold stars',
    ],
    controlsDescription: 'Tap or click any card to flip.',
  },
  {
    id: 'dama',
    title: 'Dama',
    titleAmharic: 'ዳማ',
    category: 'strategy',
    genre: 'Strategy & Tactics',
    difficulty: 'Hard',
    tagline: 'Master the 3D championship draughts board against intelligent tactical AI!',
    description: 'Single-player 3D Draughts (Dama) against an advanced computer opponent. Experience physical wooden pieces, realistic board depth, mandatory captures, multi-jumps, and king crowning across progressive tactical challenges.',
    thumbnailUrl: getGameArtworkUrl('dama'),
    bannerUrl: getGameArtworkUrl('dama'),
    primaryColor: '#b45309',
    secondaryColor: '#1c1917',
    rating: 4.98,
    playsCount: 156000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Tap your white pieces to reveal legal diagonal moves and mandatory capture paths',
      'Jumps and chain captures are strictly mandatory when available on the board',
      'Reach the opponent back rank to crown your piece into a powerful 4-way King',
      'Outmaneuver and capture all computer pieces to claim victory',
    ],
    controlsDescription: 'Tap piece to select, then tap highlighted square to move.',
  },
  {
    id: 'soccer-ping-pong',
    title: 'Soccer Ping Pong',
    titleAmharic: 'ሶከር ፒንግ ፖንግ',
    category: 'sports',
    genre: '3D Sports Arcade',
    difficulty: 'Challenging',
    tagline: 'Master professional 3D soccer table tennis across 20 high-stakes stadium levels!',
    description: 'Control a high-velocity 3D soccer ball in fast-paced table tennis rallies against tactical AI opponents. Execute precision volleys, curve spins, power smashes, and obstacle rebounds across 6 progressive stadiums.',
    thumbnailUrl: getGameArtworkUrl('soccer-ping-pong'),
    bannerUrl: getGameArtworkUrl('soccer-ping-pong'),
    primaryColor: '#1688C9',
    secondaryColor: '#8BCB3D',
    rating: 4.99,
    playsCount: 198000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Slide your striker left and right to intercept the incoming soccer ball',
      'Time returns within the glowing green Sweet-Spot zone for PERFECT power shots and combo multipliers',
      'Hit bullseye rings, spring bumpers, and deflect past moving defender barriers',
      'Maintain continuous rallies without letting the ball pass your baseline to unlock all 20 levels',
    ],
    controlsDescription: 'Touch and drag striker horizontally, or use mouse / arrow keys.',
  },
  {
    id: 'sorting-balls',
    title: 'Sorting Ball',
    titleAmharic: 'ሶርቲንግ ቦል',
    category: 'puzzle',
    genre: '3D Color-Sorting Puzzle',
    difficulty: 'Medium',
    tagline: 'Sort vibrant glossy 3D spheres into transparent glass tubes across 40 mind-bending levels!',
    description: 'A beautifully relaxing and cerebral 3D color sorting puzzle. Strategically transfer colored spheres between glass cylinders until each tube contains exclusively identical colors. Features realistic glass reflections, smooth trajectory arcs, and 40 progressive stages.',
    thumbnailUrl: getGameArtworkUrl('sorting-balls'),
    bannerUrl: getGameArtworkUrl('sorting-balls'),
    primaryColor: '#FF8A00',
    secondaryColor: '#171B26',
    rating: 4.99,
    playsCount: 215000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Tap any tube to select its top ball, then tap another valid tube to transfer it',
      'A ball can only be placed into an empty tube or on top of a matching color',
      'Sort all 4 balls of each color into their dedicated tubes to solve the puzzle',
      'Use Undo or add an Extra Tube if you reach a tight impasse',
    ],
    controlsDescription: 'Tap source tube to lift ball, tap destination tube to drop.',
  },
  {
    id: 'emoji-sorting-ball',
    title: 'EMOJI SORTING BALL',
    titleAmharic: 'ኢሞጂ ሶርቲንግ ቦል',
    category: 'puzzle',
    genre: '3D Emoji Sorting Tournament Puzzle',
    difficulty: 'Medium',
    tagline: 'Sort stylized 3D emoji vinyl spheres into color-coded crystal tubes across 40 levels!',
    description: 'The premier 3D Emoji Sorting tournament challenge. Transfer identical emoji spheres between vibrant tubes, utilize sequential multi-ball transfers, manage undos, hints, and buffer tubes, and maximize your tournament par efficiency.',
    thumbnailUrl: getGameArtworkUrl('emoji-sorting-ball'),
    bannerUrl: getGameArtworkUrl('emoji-sorting-ball'),
    primaryColor: '#8B5CF6',
    secondaryColor: '#F472B6',
    rating: 4.99,
    playsCount: 280000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Tap any tube to lift top emoji ball(s), then tap destination tube with matching emoji or empty space',
      'Contiguous matching emojis transfer together in a coordinated sequential wave',
      'Finish each puzzle in minimum moves to earn 3 stars and tournament Par bonus score',
      'Use Undo (-50 PTS), Hints (-150 PTS), or Add Extra Tube (-250 PTS) when stuck',
    ],
    controlsDescription: 'Tap source tube to select emoji, tap destination tube to transfer.',
  },
  {
    id: 'bubble-shooter',
    title: 'Bubble Pop',
    titleAmharic: 'ባብል ሹተር',
    category: 'puzzle',
    genre: 'Hexagonal Bubble Match',
    difficulty: 'Challenging',
    tagline: 'Aim, reflect wall bank shots, and pop dense glossy bubble formations across 40 tournament levels!',
    description: 'The tournament edition of the classic Bubble Shooter. Aim the precision dotted laser guide, calculate tactical wall bank shots, trigger satisfying cluster drop cascades, and conquer 40 progressive stages from Hard to Championship.',
    thumbnailUrl: getGameArtworkUrl('bubble-shooter'),
    bannerUrl: getGameArtworkUrl('bubble-shooter'),
    primaryColor: '#1788E8',
    secondaryColor: '#071626',
    rating: 4.98,
    playsCount: 230000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Touch and drag in the lower area to aim the dotted trajectory guide',
      'Bounce shots off side walls to reach concealed high-value color clusters',
      'Connect 3 or more matching bubbles to pop them and drop unsupported clusters',
      'Clear all bubbles to complete the level before fouls cause the ceiling to descend',
    ],
    controlsDescription: 'Drag to aim, release to shoot. Tap swap button to exchange next bubble.',
  },
  {
    id: 'soccer-shooter',
    title: 'Soccer Shooter',
    titleAmharic: 'ሶከር ሹተር',
    category: 'sports',
    genre: 'Stadium Soccer Bubble Match',
    difficulty: 'Hard',
    tagline: 'Kick 3D national team soccer balls, execute wall bank shots, and clear 40 World Cup tournament levels!',
    description: 'The championship edition of Soccer Shooter. Aim the precision dotted trajectory guide from the penalty spot, bank shots off stadium walls, trigger massive goalmouth cluster drops (+250 PTS), and manage penalty fouls across 40 progressive tournament stages from Group Stage to the World Cup Final.',
    thumbnailUrl: getGameArtworkUrl('soccer-shooter'),
    bannerUrl: getGameArtworkUrl('soccer-shooter'),
    primaryColor: '#009739',
    secondaryColor: '#061325',
    rating: 4.99,
    playsCount: 275000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Touch and drag in the stadium field to aim the precision dotted trajectory laser',
      'Bounce kicks off stadium walls to reach upper root soccer balls and trigger falling cascades',
      'Match 3 or more national team soccer balls to pop them with crowd celebration',
      'Unsupported soccer balls fall into the goalmouth for location bonuses (+250 for center goal!)',
      'Avoid consecutive missed shots (fouls) before the referee whistle causes the ceiling to descend',
    ],
    controlsDescription: 'Touch/drag to aim, release to kick. Tap SWAP button to change upcoming ball.',
  },
  {
    id: 'moto-race',
    title: 'Moto Race',
    titleAmharic: 'ሞተር ሬስ',
    category: 'racing',
    genre: '3D First-Person Racing',
    difficulty: 'Hard',
    tagline: 'First-person high-speed highway traffic racing across 40 progressive city levels!',
    description: 'Experience adrenaline-pumping 3D first-person motorcycle highway racing. Grip the handlebars, lean into turns, weave through high-density urban traffic, execute close near-miss overtakes, and conquer 40 progressive stages from Sunset Boulevard to Midnight City.',
    thumbnailUrl: getGameArtworkUrl('moto-race'),
    bannerUrl: getGameArtworkUrl('moto-race'),
    primaryColor: '#0284c7',
    secondaryColor: '#8BCB3D',
    rating: 4.99,
    playsCount: 312000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Steer left and right using screen arrow buttons or [A]/[D] / Left/Right arrow keys',
      'Hold GAS (W / Up Arrow) to accelerate up to 148 km/h and maintain high-speed scoring streaks',
      'Tap BRAKE (S / Down Arrow / Space) when approaching congested traffic corridors',
      'Execute close overtakes (Near Misses) within inches of traffic for combo multipliers and time bonuses',
      'Avoid collisions and cross the checkered finish line archway before the mission timer expires',
    ],
    controlsDescription: 'Touch steer/gas/brake buttons or use keyboard [W][A][S][D] / Arrow keys.',
  },
  {
    id: 'fruit-slice',
    title: 'Fruit Slice',
    titleAmharic: 'ፍሩት ኒንጃ',
    category: 'action',
    genre: '3D Action Blade Arcade',
    difficulty: 'Hard',
    tagline: 'Slice 3D fruits, trigger juicy combos, and master 40 championship Katana levels!',
    description: 'Experience exhilarating 3D Katana blade fruit slicing. Swipe through flying fruits, split juicy 3D watermelons, kiwis, pineapples and coconuts, avoid dangerous bombs, and conquer 40 progressive stages from Apprentice to Grandmaster Dojo.',
    thumbnailUrl: getGameArtworkUrl('fruit-slice'),
    bannerUrl: getGameArtworkUrl('fruit-slice'),
    primaryColor: '#e11d48',
    secondaryColor: '#f59e0b',
    rating: 4.99,
    playsCount: 345000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Swipe or slide your finger / mouse cursor across the screen to slice incoming fruits',
      'Slice 2 or more fruits in a single swipe to trigger powerful combo multipliers',
      'Strike Critical Fruits for sparkling +10 bonus points',
      'Avoid slicing black bombs or use deflections before detonating',
      'Do not let 3 whole fruits fall past the bottom edge of the screen',
    ],
    controlsDescription: 'Swipe or drag with finger on touchscreens, or drag mouse on desktop.',
  },
  {
    id: 'knife-madness',
    title: 'Knife Madness',
    titleAmharic: 'ናይፍ ማድነስ',
    category: 'arcade',
    genre: '3D Precision Target Arcade',
    difficulty: 'Hard',
    tagline: 'Throw 3D knives, slice juicy apples, and shatter rotating targets across 40 extreme stages!',
    description: 'The ultimate test of precision timing and reflexes. Tap to throw steel knives into rotating 3D targets, slice apples for bonus points, avoid hitting existing blades or hazardous obstacles, and shatter targets to conquer 40 skill-based stages from Tire and Cheese to Master Cog.',
    thumbnailUrl: getGameArtworkUrl('knife-madness'),
    bannerUrl: getGameArtworkUrl('knife-madness'),
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    rating: 4.99,
    playsCount: 385000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Tap the screen or click mouse to launch a knife straight toward the rotating 3D target',
      'Time your throws carefully into open gaps to embed the required number of knives',
      'Slice red apples attached to targets for +2 bonus points and extra collection reward',
      'Avoid striking any pre-embedded knives, daggers, bones, or previously thrown blades',
      'Successfully embed all knives to shatter the target and advance to the next stage',
    ],
    controlsDescription: 'Tap or click anywhere on screen to throw knife.',
  },
  {
    id: 'juicy-match',
    title: 'Candy Crush',
    titleAmharic: 'ኬንዲ ጁሲ',
    category: 'puzzle',
    genre: 'Match-3 Fruit Puzzle',
    difficulty: 'Hard',
    tagline: 'Match glossy 3D tropical fruits, trigger juice cascades, and conquer 40 progressive island levels!',
    description: 'A vibrant and juicy Match-3 puzzle adventure. Swap 3D strawberries, blueberries, kiwi slices, bananas, and grapes to shatter crates, uncover treasure chests, clear juice puddles, and unleash Rainbow Bomb combos across 40 challenging tropical levels.',
    thumbnailUrl: getGameArtworkUrl('juicy-match'),
    bannerUrl: getGameArtworkUrl('juicy-match'),
    primaryColor: '#f59e0b',
    secondaryColor: '#0284c7',
    rating: 4.99,
    playsCount: 420000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Swipe or tap adjacent fruits to create rows or columns of 3 matching fruits',
      'Match 4 fruits to create Striped Fruits that blast entire rows or columns',
      'Match 5 fruits in a line to form the Rainbow Super Fruit that clears all fruits of one color',
      'Combine T-shapes or L-shapes to create explosive Fruit Bombs with 3x3 blast radius',
      'Clear juice puddles, break multi-layer crates, and open treasure chests before moves run out',
    ],
    controlsDescription: 'Swipe or tap adjacent fruits to swap. Tap boosters at the bottom to activate.',
  },
  {
    id: 'solitaire',
    title: 'Solitaire',
    titleAmharic: 'ሶሊቴር',
    category: 'puzzle',
    genre: 'Classic Klondike Solitaire',
    difficulty: 'Challenging',
    tagline: 'Master authentic 52-card Klondike Solitaire across 40 progressive championship levels!',
    description: 'The definitive Klondike Solitaire experience. Features Draw 1 and Draw 3 modes, authentic playing card artwork with classic court illustrations and red geometric card backs, deep emerald felt table acoustics, 40 progressive levels scaling from Hard to Grandmaster, daily challenge deals, unlimited undo, smart hints, and auto-complete.',
    thumbnailUrl: getGameArtworkUrl('solitaire'),
    bannerUrl: getGameArtworkUrl('solitaire'),
    primaryColor: '#007a40',
    secondaryColor: '#ffd54f',
    rating: 4.99,
    playsCount: 485000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Stack cards in descending order (King down to Ace) in alternating red and black suits in the 7 tableau columns',
      'Build the 4 foundation piles from Ace to King by suit (Hearts, Diamonds, Clubs, Spades)',
      'Place Kings or King-headed runs into empty tableau columns',
      'Draw from the stock pile (Draw 1 or Draw 3) to discover new strategic cards',
      'Use smart auto-moves by tapping cards, or drag and place sequences freely',
    ],
    controlsDescription: 'Tap any card to auto-move to best legal position, or tap to select and place. Tap stock to draw.',
  },
  {
    id: 'puzzle-block',
    title: 'Block',
    titleAmharic: 'ብሎክ',
    category: 'puzzle',
    genre: 'Wooden Block Puzzle',
    difficulty: 'Challenging',
    tagline: 'Place polyomino blocks on the 10x10 wooden board and clear full rows and columns across 40 levels!',
    description: 'The definitive 10x10 wooden block puzzle experience inspired by classic block mechanics. Features 40 progressive championship levels scaling from Hard to Grandmaster, real drag & drop with touch-elevation offset, glossy 3D polyominoes, wood/ice/stone blockers, special explosive bomb blocks, multi-line combo feedback, limited reshuffle, daily challenge, and rich procedural Web Audio acoustics.',
    thumbnailUrl: getGameArtworkUrl('puzzle-block'),
    bannerUrl: getGameArtworkUrl('puzzle-block'),
    primaryColor: '#8a3f20',
    secondaryColor: '#f59e0b',
    rating: 4.99,
    playsCount: 520000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Touch and drag block shapes from the bottom 3-piece tray onto the 10x10 board',
      'Fill complete 10-cell horizontal rows or vertical columns to collapse them',
      'Clear multiple lines simultaneously to trigger massive combo multipliers and fanfare',
      'Damage and shatter adjacent Wood and Ice blockers to open space for large pieces',
      'Use limited reshuffles strategically when tight on moves to survive',
    ],
    controlsDescription: 'Touch and drag pieces onto the 10x10 board. Release over valid cells to place.',
  },
  {
    id: 'crazy-colors',
    title: 'Color Switch',
    titleAmharic: 'ክሬዚ ከለር',
    category: 'reaction',
    genre: 'Precision Color Match Arcade',
    difficulty: 'Hard',
    tagline: 'Bounce upwards, pass through matching neon obstacles, and conquer 40 championship levels!',
    description: 'The definitive 40-level Crazy Colors experience based on authentic color-matching physics. Tap to bounce against gravity, time passes through matching neon segments, navigate dynamic chevrons, double rings and star polygons, collect stars, and become the Crazy Colors Grandmaster!',
    thumbnailUrl: getGameArtworkUrl('crazy-colors'),
    bannerUrl: getGameArtworkUrl('crazy-colors'),
    primaryColor: '#FF008C',
    secondaryColor: '#00D9FF',
    rating: 4.99,
    playsCount: 560000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Tap anywhere on the screen or press Spacebar to bounce upwards against gravity',
      'Your ball can only pass through obstacle segments that match its current color',
      'Passing through Color Switcher orbs changes your ball color for upcoming obstacles',
      'Collect golden stars along the track for high scores and 1-5 star ratings',
      'Reach the rotating finish portal at the top to complete all 40 progressive levels',
    ],
    controlsDescription: 'Tap or click screen to jump. Spacebar supported on desktop.',
  },
  {
    id: 'helix-jump',
    title: 'Helix Jump',
    titleAmharic: 'ሄሊክስ ጃምፕ',
    category: 'arcade',
    genre: '3D Arcade Drop',
    difficulty: 'Very Hard',
    tagline: 'Swipe to rotate the central tower, drop through gaps, and conquer 40 championship levels!',
    description: 'The definitive 40-level 3D Helix Jump experience. Swipe horizontally to rotate the cylindrical tower, guide the bouncing ball through open gaps, land on safe sectors, trigger fiery multi-level combo smashes, avoid red danger platforms, and conquer 40 progressive stages from Vertex Descent to The Helix Pinnacle.',
    thumbnailUrl: getGameArtworkUrl('helix-jump'),
    bannerUrl: getGameArtworkUrl('helix-jump'),
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    rating: 4.99,
    playsCount: 620000,
    energyCost: 1,
    featured: true,
    isTrending: true,
    isNew: true,
    instructions: [
      'Swipe or drag left and right on the screen to rotate the central helix tower',
      'Align open gaps directly underneath the bouncing ball to descend through the rings',
      'Land on white safe platforms to bounce upward and maintain control',
      'Avoid red or orange danger platform sectors that instantly shatter the ball',
      'Drop through 3 or more consecutive rings to trigger Power Smash mode',
      'Reach the checkered finish ring at the base to complete each of the 40 levels',
    ],
    controlsDescription: 'Swipe left/right to rotate tower. Drag finger or mouse horizontally.',
  },
];

/**
 * Tournaments Demo Data
 */
export const DEMO_TOURNAMENTS: Tournament[] = [
  {
    id: 'tourney_solitaire_weekly',
    title: 'Solitaire Grand Masters',
    gameId: 'solitaire',
    gameTitle: 'Solitaire',
    cycle: 'weekly',
    bannerImage: getGameArtworkUrl('solitaire'),
    prizePoolETB: 15000,
    prizePoolCoins: 75000,
    entryFeeEnergy: 1,
    entryRequirement: '10 Coins Entry',
    startDate: '2026-08-28',
    endDate: '2026-08-31',
    status: 'Live',
    participantsCount: 16800,
    sponsor: 'EthioTelecom TeleBirr',
    prizes: [
      { rank: '1st Place', reward: '8,000 ETB TeleBirr Transfer', telebirrETB: 8000 },
      { rank: '2nd Place', reward: '4,000 ETB TeleBirr Transfer', telebirrETB: 4000 },
      { rank: '3rd Place', reward: '2,000 ETB TeleBirr Transfer', telebirrETB: 2000 },
      { rank: '4th - 20th', reward: '200 ETB Airtime Recharge', telebirrETB: 200 },
    ],
  },
  {
    id: 'tourney_candy_blast_weekly',
    title: 'Candy Crush Super Cup',
    gameId: 'candy-blast',
    gameTitle: 'Candy Crush',
    cycle: 'weekly',
    bannerImage: getGameArtworkUrl('candy-blast'),
    prizePoolETB: 10000,
    prizePoolCoins: 50000,
    entryFeeEnergy: 1,
    entryRequirement: '10 Coins Entry',
    startDate: '2026-08-28',
    endDate: '2026-08-31',
    status: 'Live',
    participantsCount: 12450,
    sponsor: 'TeleBirr SuperApp',
    prizes: [
      { rank: '1st Place', reward: '5,000 ETB TeleBirr Transfer', telebirrETB: 5000 },
      { rank: '2nd Place', reward: '2,500 ETB TeleBirr Transfer', telebirrETB: 2500 },
      { rank: '3rd Place', reward: '1,000 ETB TeleBirr Transfer', telebirrETB: 1000 },
      { rank: '4th - 20th', reward: '100 ETB Airtime Voucher', telebirrETB: 100 },
    ],
  },
  {
    id: 'tourney_color_rush_weekly',
    title: 'Color Rush Reflex Challenge',
    gameId: 'color-rush',
    gameTitle: 'Color Rush',
    cycle: 'weekly',
    bannerImage: getGameArtworkUrl('color-rush'),
    prizePoolETB: 15000,
    prizePoolCoins: 75000,
    entryFeeEnergy: 1,
    entryRequirement: '10 Coins Entry',
    startDate: '2026-08-28',
    endDate: '2026-08-31',
    status: 'Live',
    participantsCount: 9800,
    sponsor: 'EthioTelecom 4G/5G',
    prizes: [
      { rank: '1st Place', reward: '7,500 ETB TeleBirr Transfer', telebirrETB: 7500 },
      { rank: '2nd Place', reward: '3,500 ETB TeleBirr Transfer', telebirrETB: 3500 },
      { rank: '3rd Place', reward: '1,500 ETB TeleBirr Transfer', telebirrETB: 1500 },
      { rank: '4th - 20th', reward: '150 ETB Airtime Recharge', telebirrETB: 150 },
    ],
  },
  {
    id: 'tourney_pop_piano_weekly',
    title: 'Pop Piano Rhythm Cup',
    gameId: 'pop-piano',
    gameTitle: 'Pop Piano',
    cycle: 'weekly',
    bannerImage: getGameArtworkUrl('pop-piano'),
    prizePoolETB: 12000,
    prizePoolCoins: 60000,
    entryFeeEnergy: 1,
    entryRequirement: '10 Coins Entry',
    startDate: '2026-08-28',
    endDate: '2026-08-31',
    status: 'Live',
    participantsCount: 11200,
    sponsor: 'EthioTelecom Digital Services',
    prizes: [
      { rank: '1st Place', reward: '6,000 ETB TeleBirr Transfer', telebirrETB: 6000 },
      { rank: '2nd Place', reward: '3,000 ETB TeleBirr Transfer', telebirrETB: 3000 },
      { rank: '3rd Place', reward: '1,000 ETB TeleBirr Transfer', telebirrETB: 1000 },
    ],
  },
  {
    id: 'tourney_world_legends_monthly',
    title: 'Word Legend Grand Championship',
    gameId: 'world-legends',
    gameTitle: 'Word Legend',
    cycle: 'monthly',
    bannerImage: getGameArtworkUrl('world-legends'),
    prizePoolETB: 50000,
    prizePoolCoins: 250000,
    entryFeeEnergy: 2,
    entryRequirement: '20 Coins Entry',
    startDate: '2026-08-25',
    endDate: '2026-09-02',
    status: 'Live',
    participantsCount: 24500,
    sponsor: 'EthioTelecom 5G Network',
    prizes: [
      { rank: '1st Place', reward: '25,000 ETB TeleBirr + 6 Months 5G Unlimited', telebirrETB: 25000 },
      { rank: '2nd Place', reward: '12,500 ETB TeleBirr + 3 Months 5G Package', telebirrETB: 12500 },
      { rank: '3rd Place', reward: '6,000 ETB TeleBirr + 1 Month 5G Package', telebirrETB: 6000 },
      { rank: '4th - 10th', reward: '1,000 ETB Airtime Voucher', telebirrETB: 1000 },
      { rank: 'Top 100', reward: '200 ETB Airtime Voucher', telebirrETB: 200 },
    ],
  },
  {
    id: 'tourney_hill_climb_monthly',
    title: 'Highland Hill Climb Championship',
    gameId: 'hill-rider',
    gameTitle: 'Hill Climb',
    cycle: 'monthly',
    bannerImage: getGameArtworkUrl('hill-rider'),
    prizePoolETB: 40000,
    prizePoolCoins: 200000,
    entryFeeEnergy: 2,
    entryRequirement: '20 Coins Entry',
    startDate: '2026-08-25',
    endDate: '2026-09-02',
    status: 'Live',
    participantsCount: 19800,
    sponsor: 'TeleBirr SuperApp',
    prizes: [
      { rank: '1st Place', reward: '20,000 ETB TeleBirr Transfer', telebirrETB: 20000 },
      { rank: '2nd Place', reward: '10,000 ETB TeleBirr Transfer', telebirrETB: 10000 },
      { rank: '3rd Place', reward: '5,000 ETB TeleBirr Transfer', telebirrETB: 5000 },
    ],
  },
  {
    id: 'tourney_archery_monthly',
    title: 'Pop Balloon Reflex Championship',
    gameId: 'archery-strike',
    gameTitle: 'Pop Balloon',
    cycle: 'monthly',
    bannerImage: getGameArtworkUrl('archery-strike'),
    prizePoolETB: 35000,
    prizePoolCoins: 175000,
    entryFeeEnergy: 2,
    entryRequirement: '20 Coins Entry',
    startDate: '2026-08-25',
    endDate: '2026-09-02',
    status: 'Live',
    participantsCount: 16400,
    sponsor: 'EthioTelecom Digital',
    prizes: [
      { rank: '1st Place', reward: '18,000 ETB TeleBirr Transfer', telebirrETB: 18000 },
      { rank: '2nd Place', reward: '9,000 ETB TeleBirr Transfer', telebirrETB: 9000 },
      { rank: '3rd Place', reward: '4,000 ETB TeleBirr Transfer', telebirrETB: 4000 },
    ],
  },
];

/**
 * Leaderboards Demo Data
 */
export const DEMO_LEADERBOARD_ENTRIES: Record<string, LeaderboardEntry[]> = {
  daily: [
    { id: 'lb_1', rank: 1, userId: 'u_101', displayName: 'Yared_Speed', phoneNumberMasked: '+251 91 **** 812', avatarId: 'avatar_runner', score: 28450, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: '12m ago' },
    { id: 'lb_2', rank: 2, userId: 'u_102', displayName: 'Selam_Pro', phoneNumberMasked: '+251 92 **** 409', avatarId: 'avatar_eagle', score: 26900, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Hawassa', timestamp: '24m ago' },
    { id: 'lb_3', rank: 3, userId: 'u_103', displayName: 'Dawit_99', phoneNumberMasked: '+251 93 **** 611', avatarId: 'avatar_lion', score: 24800, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: false, region: 'Adama', timestamp: '45m ago' },
    { id: 'lb_4', rank: 4, userId: 'u_104', displayName: 'Beti_Puzzle', phoneNumberMasked: '+251 91 **** 780', avatarId: 'avatar_crown', score: 21350, gameId: 'habesha-2048', gameTitle: 'Habesha 2048', isVip: true, region: 'Bahir Dar', timestamp: '1h ago' },
    { id: 'lb_5', rank: 5, userId: 'u_105', displayName: 'Tadesse_Apex', phoneNumberMasked: '+251 94 **** 332', avatarId: 'avatar_runner', score: 19800, gameId: 'nile-gem-quest', gameTitle: 'Nile Gem Quest', isVip: false, region: 'Mekelle', timestamp: '2h ago' },
    { id: 'lb_6', rank: 6, userId: 'u_106', displayName: 'Helen_Quiz', phoneNumberMasked: '+251 91 **** 105', avatarId: 'avatar_lion', score: 18400, gameId: 'ethio-trivia', gameTitle: 'Ethio Trivia Master', isVip: false, region: 'Dire Dawa', timestamp: '2h ago' },
    { id: 'lb_7', rank: 7, userId: 'u_107', displayName: 'Kidus_Goal', phoneNumberMasked: '+251 92 **** 991', avatarId: 'avatar_eagle', score: 16750, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: true, region: 'Addis Ababa', timestamp: '3h ago' },
    { id: 'lb_8', rank: 8, userId: 'u_108', displayName: 'Marta_Derby', phoneNumberMasked: '+251 96 **** 554', avatarId: 'avatar_crown', score: 15200, gameId: 'speed-bumper-derby', gameTitle: 'Speed Bumper Derby', isVip: false, region: 'Jimma', timestamp: '3h ago' },
  ],
  weekly: [
    { id: 'lb_w1', rank: 1, userId: 'u_201', displayName: 'Kassahun_Apex', phoneNumberMasked: '+251 91 **** 300', avatarId: 'avatar_crown', score: 142800, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: '2d ago' },
    { id: 'lb_w2', rank: 2, userId: 'u_202', displayName: 'Almaz_Legend', phoneNumberMasked: '+251 91 **** 981', avatarId: 'avatar_lion', score: 128400, gameId: 'habesha-2048', gameTitle: 'Habesha 2048', isVip: true, region: 'Adama', timestamp: '1d ago' },
    { id: 'lb_w3', rank: 3, userId: 'u_203', displayName: 'Solomon_Strike', phoneNumberMasked: '+251 93 **** 447', avatarId: 'avatar_eagle', score: 119500, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: true, region: 'Hawassa', timestamp: '3d ago' },
    { id: 'lb_w4', rank: 4, userId: 'u_204', displayName: 'Genet_Gems', phoneNumberMasked: '+251 92 **** 112', avatarId: 'avatar_runner', score: 98700, gameId: 'nile-gem-quest', gameTitle: 'Nile Gem Quest', isVip: false, region: 'Dire Dawa', timestamp: '4d ago' },
    { id: 'lb_w5', rank: 5, userId: 'u_205', displayName: 'Biruk_Trivia', phoneNumberMasked: '+251 94 **** 882', avatarId: 'avatar_crown', score: 87600, gameId: 'ethio-trivia', gameTitle: 'Ethio Trivia Master', isVip: false, region: 'Gondar', timestamp: '2d ago' },
  ],
  alltime: [
    { id: 'lb_a1', rank: 1, userId: 'u_301', displayName: 'Moges_GrandMaster', phoneNumberMasked: '+251 91 **** 001', avatarId: 'avatar_crown', score: 940500, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: 'Aug 2026' },
    { id: 'lb_a2', rank: 2, userId: 'u_302', displayName: 'Aster_Champion', phoneNumberMasked: '+251 91 **** 552', avatarId: 'avatar_lion', score: 815200, gameId: 'penalty-shootout', gameTitle: 'Highland Shootout', isVip: true, region: 'Bishoftu', timestamp: 'Aug 2026' },
    { id: 'lb_a3', rank: 3, userId: 'u_303', displayName: 'Yohannes_Pro', phoneNumberMasked: '+251 92 **** 783', avatarId: 'avatar_eagle', score: 760400, gameId: 'habesha-2048', gameTitle: 'Habesha 2048', isVip: true, region: 'Bahir Dar', timestamp: 'Jul 2026' },
  ],
  tournament: [
    { id: 'lb_t1', rank: 1, userId: 'u_401', displayName: 'Addis_Sonic', phoneNumberMasked: '+251 91 **** 449', avatarId: 'avatar_crown', score: 48900, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Addis Ababa', timestamp: '30m ago' },
    { id: 'lb_t2', rank: 2, userId: 'u_402', displayName: 'Tigist_Fast', phoneNumberMasked: '+251 93 **** 201', avatarId: 'avatar_lion', score: 46200, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Hawassa', timestamp: '1h ago' },
    { id: 'lb_t3', rank: 3, userId: 'u_403', displayName: 'Elias_Volt', phoneNumberMasked: '+251 92 **** 873', avatarId: 'avatar_runner', score: 44100, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: false, region: 'Adama', timestamp: '2h ago' },
    { id: 'lb_t4', rank: 4, userId: 'u_404', displayName: 'Mesfin_Rush', phoneNumberMasked: '+251 91 **** 662', avatarId: 'avatar_eagle', score: 41800, gameId: 'addis-runner', gameTitle: 'Addis Runner', isVip: true, region: 'Mekelle', timestamp: '3h ago' },
  ],
};

/**
 * 7-Day Daily Streak Reward Ladder
 */
export const DAILY_REWARD_LADDER: DailyRewardItem[] = [
  { day: 1, coins: 50, energy: 1, badge: 'Novice Day' },
  { day: 2, coins: 100, energy: 1, badge: 'Double Boost' },
  { day: 3, coins: 150, energy: 2, badge: 'Streak Power' },
  { day: 4, coins: 250, energy: 2, badge: 'Bronze Rank' },
  { day: 5, coins: 400, energy: 3, badge: 'Silver Tier' },
  { day: 6, coins: 600, energy: 3, badge: 'Gold Rush' },
  { day: 7, coins: 1200, energy: 5, badge: 'Walia Grand Chest', special: true },
];

/**
 * Rewarded Ads Catalog (EthioTelecom & TeleBirr sponsored ads)
 */
export const DEMO_TELECOM_ADS = [
  {
    id: 'ad_telebirr_superapp',
    brand: 'TeleBirr SuperApp',
    title: 'Pay bills, send money & earn cashbacks instantly!',
    tagline: 'Ethiopia’s #1 Digital Payment Lifestyle Platform',
    videoBanner: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 5,
    ctaText: 'Open TeleBirr SuperApp',
    accentColor: '#70C922',
  },
  {
    id: 'ad_ethio_5g_router',
    brand: 'EthioTelecom 5G Ultra Broadband',
    title: 'Experience blistering Gigabit speeds across 120+ cities!',
    tagline: 'Connect your home & gaming stations with 0-ping latency',
    videoBanner: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 5,
    ctaText: 'Upgrade to 5G Now',
    accentColor: '#0B3B70',
  },
  {
    id: 'ad_ethio_youth_package',
    brand: 'EthioTelecom Youth Chill Pack',
    title: 'Unlimited Social Media + 10GB Gaming Data at just 50 ETB',
    tagline: 'Empowering the next generation of digital creators',
    videoBanner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 5,
    ctaText: 'Dial *999# to Subscribe',
    accentColor: '#70C922',
  },
];
