/**
 * GameON Tele - Data-Driven Game Catalog (Designed for 100+ Games)
 * Scalable Game Discovery, Category Classification, and Access Models.
 */

import { getGameArtworkUrl } from './gameArtwork';

export type GameAccessType = 'FREE' | 'COIN' | 'SUBSCRIPTION' | 'PURCHASE' | 'TRIAL';

export interface GameSubscriptionOptions {
  daily?: { enabled: boolean; priceETB: number };
  weekly?: { enabled: boolean; priceETB: number };
  monthly?: { enabled: boolean; priceETB: number };
}

export interface CatalogGame {
  gameId: string;
  gameName: string;
  titleAmharic: string;
  category: 'Action' | 'Arcade' | 'Puzzle' | 'Racing' | 'Sports' | 'Adventure' | 'Board' | 'Music' | 'Casual' | 'Strategy' | 'Other';
  genre: string;
  tagline: string;
  description: string;
  thumbnail: string;
  banner: string;
  accessType: GameAccessType;
  price?: number; // for ONE-TIME PURCHASE
  billingPeriod?: ('daily' | 'weekly' | 'monthly')[];
  isFeatured: boolean;
  isActive: boolean;
  isNew: boolean;
  isRecommended?: boolean;
  isFree: boolean;
  requiresCoins: boolean;
  coinCost: number;
  subscriptionOptions?: GameSubscriptionOptions;
  leaderboardEnabled: boolean;
  sortOrder: number;
  providerId?: string;
  providerName?: string;
  rating: number;
  playsCount: number;
  instructions: string[];
  controlsDescription: string;
  primaryColor: string;
  secondaryColor: string;
}

export const ALL_STANDARD_CATEGORIES = [
  'All Games',
  'Action',
  'Arcade',
  'Puzzle',
  'Racing',
  'Sports',
  'Adventure',
  'Board',
  'Music',
  'Casual',
  'Strategy',
  'Other',
] as const;

export const MANDATORY_CATALOG_ORDER = [
  'emoji-fun', // 1: Emoji
  'crazy-colors', // 2: Color Switch
  'fruit-slice', // 3: Fruit Slice
  'juicy-match', // 4: Candy Crush
  'bubble-shooter', // 5: Bubble Pop
  'pop-piano', // 6: Piano
  'memory-match', // 7: Picture Match
  'dama', // 8: Dama
] as const;

export const INITIAL_GAME_CATALOG: CatalogGame[] = [
  {
    gameId: 'emoji-fun',
    gameName: 'Emoji',
    titleAmharic: 'ኢሞጂ',
    category: 'Puzzle',
    genre: 'Tournament Emoji Puzzle & Knowledge',
    tagline: 'Master 40 levels of emoji puzzles, combinations, sequences & tournament scoring!',
    description: 'The official Emoji tournament puzzle arena. Solve 15 unique emoji puzzle categories across 40 levels with dynamic skill-based scoring, combos, hints, lives, store, and competitive leaderboard.',
    thumbnail: getGameArtworkUrl('emoji-fun'),
    banner: getGameArtworkUrl('emoji-fun'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 0,
    providerId: 'prv_gameon_core',
    providerName: 'TelePlus Studios',
    rating: 4.99,
    playsCount: 350000,
    primaryColor: '#ffb300',
    secondaryColor: '#f43f5e',
    instructions: [
      'Analyze the emoji presentation and answer before the countdown timer expires',
      'Answer quickly to earn up to +50% speed bonus points',
      'Chain consecutive correct answers to multiply tournament score up to 2.5x',
      'Use hints to eliminate wrong choices when stuck on tricky puzzles',
    ],
    controlsDescription: 'Tap the correct answer tile.',
  },
  {
    gameId: 'crazy-colors',
    gameName: 'Color Switch',
    titleAmharic: 'ከለር ስዊች',
    category: 'Arcade',
    genre: 'Precision Color Match Physics',
    tagline: 'Bounce upwards, pass through matching neon obstacles, and conquer 40 levels!',
    description: 'The definitive 40-level Color Switch experience based on authentic color-matching physics. Tap to bounce against gravity, time passes through matching neon segments, collect stars, and become the Grandmaster!',
    thumbnail: getGameArtworkUrl('crazy-colors'),
    banner: getGameArtworkUrl('crazy-colors'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 1,
    providerId: 'prv_gameon_core',
    providerName: 'TelePlus Studios',
    rating: 4.99,
    playsCount: 560000,
    primaryColor: '#FF008C',
    secondaryColor: '#00D9FF',
    instructions: [
      'Tap anywhere on the screen to bounce upwards against gravity',
      'Your ball can only pass through obstacle segments that match its current color',
      'Passing through Color Switcher orbs changes your ball color for upcoming obstacles',
    ],
    controlsDescription: 'Tap or click screen to jump. Spacebar supported on desktop.',
  },
  {
    gameId: 'fruit-slice',
    gameName: 'Fruit Slice',
    titleAmharic: 'ፍሩት ስላይስ',
    category: 'Action',
    genre: '3D Katana Blade Slicing',
    tagline: 'Slice 3D fruits, trigger juicy combos, and master 40 Katana levels!',
    description: 'Experience exhilarating 3D Katana blade fruit slicing. Swipe through flying fruits, split juicy watermelons, kiwis, pineapples and coconuts, avoid dangerous bombs, and conquer 40 progressive stages.',
    thumbnail: getGameArtworkUrl('fruit-slice'),
    banner: getGameArtworkUrl('fruit-slice'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 2,
    providerId: 'prv_gameon_core',
    providerName: 'TelePlus Studios',
    rating: 4.99,
    playsCount: 345000,
    primaryColor: '#e11d48',
    secondaryColor: '#f59e0b',
    instructions: [
      'Swipe or slide across the screen to slice incoming flying fruits',
      'Slice 2 or more fruits in a single swipe for combo multipliers',
      'Avoid slicing black bombs, and do not let fruits drop uncut',
    ],
    controlsDescription: 'Swipe or drag with finger on touchscreens, or drag mouse on desktop.',
  },
  {
    gameId: 'juicy-match',
    gameName: 'Candy Crush',
    titleAmharic: 'ኬንዲ ክረሽ',
    category: 'Puzzle',
    genre: '3D Tropical Match-3',
    tagline: 'Match glossy 3D tropical fruits, trigger juice cascades, and conquer 40 island levels!',
    description: 'A vibrant and juicy Match-3 puzzle adventure. Swap 3D strawberries, blueberries, kiwi slices, bananas, and grapes to shatter crates, uncover treasure chests, and unleash Rainbow Bomb combos across 40 challenging tropical levels.',
    thumbnail: getGameArtworkUrl('juicy-match'),
    banner: getGameArtworkUrl('juicy-match'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 3,
    providerId: 'prv_gameon_core',
    providerName: 'TelePlus Studios',
    rating: 4.99,
    playsCount: 420000,
    primaryColor: '#f59e0b',
    secondaryColor: '#0284c7',
    instructions: [
      'Swipe or tap adjacent fruits to create rows or columns of 3 matching fruits',
      'Match 4 fruits to create Striped Fruits that blast entire rows or columns',
      'Match 5 fruits in a line to form the Rainbow Super Fruit that clears all fruits of one color',
    ],
    controlsDescription: 'Swipe or tap adjacent fruits to swap. Tap boosters to activate.',
  },
  {
    gameId: 'bubble-shooter',
    gameName: 'Bubble Pop',
    titleAmharic: 'ባብል ፖፕ',
    category: 'Puzzle',
    genre: 'Hexagonal Bubble Match',
    tagline: 'Aim, reflect wall bank shots, and pop dense glossy bubble clusters!',
    description: 'The tournament edition of the classic Bubble Pop. Aim the precision dotted laser guide, calculate tactical wall bank shots, trigger satisfying cluster drop cascades, and conquer 40 progressive stages.',
    thumbnail: getGameArtworkUrl('bubble-shooter'),
    banner: getGameArtworkUrl('bubble-shooter'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 4,
    providerId: 'prv_gameon_core',
    providerName: 'TelePlus Studios',
    rating: 4.98,
    playsCount: 230000,
    primaryColor: '#1788E8',
    secondaryColor: '#071626',
    instructions: [
      'Touch and drag in the lower area to aim the dotted trajectory guide',
      'Bounce shots off side walls to reach concealed high-value color clusters',
      'Connect 3 or more matching bubbles to pop them and drop unsupported clusters',
    ],
    controlsDescription: 'Drag to aim, release to shoot. Tap swap button to exchange next bubble.',
  },
  {
    gameId: 'helix-jump',
    gameName: 'Helix Jump',
    titleAmharic: 'ሄሊክስ ጃምፕ',
    category: 'Arcade',
    genre: '3D Cylinder Tower Drop Arcade',
    tagline: 'Rotate the central tower, drop through gaps, and conquer 40 levels!',
    description: 'The definitive 40-level 3D Helix Jump experience. Swipe horizontally to rotate the cylindrical tower, guide the bouncing ball through open gaps, land on safe sectors, and trigger fiery multi-level combo smashes.',
    thumbnail: getGameArtworkUrl('helix-jump'),
    banner: getGameArtworkUrl('helix-jump'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 5,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 620000,
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    instructions: [
      'Swipe or drag left and right on the screen to rotate the central helix tower',
      'Align open gaps directly underneath the bouncing ball to descend through the rings',
      'Avoid red or orange danger platform sectors that shatter the ball',
    ],
    controlsDescription: 'Swipe left/right to rotate tower. Drag finger or mouse horizontally.',
  },
  {
    gameId: 'pop-piano',
    gameName: 'Piano',
    titleAmharic: 'ፒያኖ',
    category: 'Music',
    genre: 'Rhythm Piano Beat Tiles',
    tagline: 'Tap falling glowing keys to chart-topping melodies and rhythms!',
    description: 'Fast rhythm piano tile gameplay featuring popular songs, acoustic chords, and global hits. Tap descending piano tiles in sync with the beat to achieve perfect harmony.',
    thumbnail: getGameArtworkUrl('pop-piano'),
    banner: getGameArtworkUrl('pop-piano'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 6,
    providerId: 'prv_gameon_core',
    providerName: 'TelePlus Studios',
    rating: 4.9,
    playsCount: 187400,
    primaryColor: '#8b5cf6',
    secondaryColor: '#70C922',
    instructions: [
      'Tap the descending piano tiles exactly as they hit the rhythm baseline bar',
      'Hold down long note tiles for sustained chord points and acoustic vibrato',
      'Do not tap empty spaces or let any piano note pass the baseline without tapping',
    ],
    controlsDescription: 'Tap keys on screen or use keyboard keys [D] [F] [J] [K].',
  },
  {
    gameId: 'world-legends',
    gameName: 'Word Legend',
    titleAmharic: 'ዎርድ ሌጀንድ',
    category: 'Puzzle',
    genre: 'Civilization & Mythology Trivia Puzzle',
    tagline: 'Journey through world history, mythology, ancient civilizations, and lore!',
    description: 'An immersive knowledge and trivia adventure. Answer intriguing questions on world civilizations, ancient mythology, Ethiopian imperial heritage, and legendary world events.',
    thumbnail: getGameArtworkUrl('world-legends'),
    banner: getGameArtworkUrl('world-legends'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 7,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.9,
    playsCount: 189000,
    primaryColor: '#f59e0b',
    secondaryColor: '#05234A',
    instructions: [
      'Answer 10 rapid multiple-choice legend questions before the 15-second timer runs out',
      'Score bonus speed points by answering accurately within the first 3 seconds',
      'Use 50:50 and Clue lifelines when facing complex historical questions',
    ],
    controlsDescription: 'Tap the correct historical answer card.',
  },
  {
    gameId: 'candy-blast',
    gameName: 'Candy Crush',
    titleAmharic: 'ኬንዲ ክራሽ',
    category: 'Puzzle',
    genre: 'Match-3 Confectionery Puzzle',
    tagline: 'Match vibrant honey candies, trigger sweet sugar blasts and combos!',
    description: 'A delightful confectionery match-3 puzzle. Swap and connect 3 or more delicious honey candies to trigger colorful cascades, sweet sugar blasts, and massive combo multipliers.',
    thumbnail: getGameArtworkUrl('candy-blast'),
    banner: getGameArtworkUrl('candy-blast'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 8,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.9,
    playsCount: 245000,
    primaryColor: '#e11d48',
    secondaryColor: '#70C922',
    instructions: [
      'Swap adjacent candies to create horizontal or vertical rows of 3 matching colors',
      'Match 4 candies to create explosive Striped Candies that clear entire rows',
      'Combine 5 candies to form a Rainbow Honey Bomb that blasts all candies of the same color',
    ],
    controlsDescription: 'Tap and swipe candies to swap positions.',
  },
  {
    gameId: 'emoji-iq',
    gameName: 'EMOJI IQ',
    titleAmharic: 'ኢሞጂ አይኪው',
    category: 'Puzzle',
    genre: 'Tournament Emoji & Number Calculation Challenge',
    tagline: 'Master 40 stages of emoji equations, logical calculations & tournament scoring!',
    description: 'The official EMOJI IQ tournament arena. Solve 12 unique emoji equation puzzle categories across 40 progressive stages with multi-step calculations, order of operations, changed quantities, visual differences, combos, hints, lives, store, and competitive leaderboard.',
    thumbnail: getGameArtworkUrl('emoji-iq'),
    banner: getGameArtworkUrl('emoji-iq'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 9,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 380000,
    primaryColor: '#6C5CE7',
    secondaryColor: '#00B8D9',
    instructions: [
      'Deduce the numerical values of emojis from the clue equations',
      'Mind the order of operations (PEMDAS): calculate multiplication and division first',
      'Watch for changes in emoji quantity (pairs vs singles) and visual differences',
      'Answer quickly without hints to claim +30% speed bonuses and ⭐ PERFECT! badges',
    ],
    controlsDescription: 'Tap the correct numerical answer tile.',
  },
  {
    gameId: 'royal-water-sort',
    gameName: 'Royal Water Sort',
    titleAmharic: 'ሮያል ወተር ሶርት',
    category: 'Puzzle',
    genre: '3D Royal Glass Water Sort Puzzle',
    tagline: 'Pour glossy liquid into 3D glass bottles, unlock golden corks, and conquer 40 Championship levels!',
    description: 'The premier 3D glass liquid sorting puzzle experience. Select crystal vials, pour vibrant liquid layers, plan complex multi-color transfers, use Undo, Shuffle & Extra Tube boosters, and conquer 40 Very Difficult royal championship levels.',
    thumbnail: getGameArtworkUrl('royal-water-sort'),
    banner: getGameArtworkUrl('royal-water-sort'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 10,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 310000,
    primaryColor: '#38BDF8',
    secondaryColor: '#FFD54F',
    instructions: [
      'Tap a glass bottle to lift and select it',
      'Tap another bottle to tilt and pour its top matching liquid group',
      'Fill each bottle with a single pure color to lock its golden cork and complete the level',
    ],
    controlsDescription: 'Tap source bottle, then tap destination bottle to pour.',
  },
  {
    gameId: 'archery-strike',
    gameName: 'Pop Ballon',
    titleAmharic: 'ፖፕ ባሎን',
    category: 'Arcade',
    genre: 'Reflex Balloon Pop Arcade',
    tagline: 'Tap and pop falling colored balloons before they reach the bottom!',
    description: 'Fast-paced reflex game. Tap and pop vibrant falling colored balloons while testing your speed, rhythm, and accuracy before any balloons slip past.',
    thumbnail: getGameArtworkUrl('archery-strike'),
    banner: getGameArtworkUrl('archery-strike'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 11,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.9,
    playsCount: 168000,
    primaryColor: '#EC4899',
    secondaryColor: '#3B82F6',
    instructions: [
      'Tap or click directly on each falling colored balloon to pop it instantly',
      'Do not tap empty background space or decorative borders',
      'Prevent balloons from escaping past the bottom to preserve your hearts',
    ],
    controlsDescription: 'Tap or click falling colored balloons to pop.',
  },
  {
    gameId: 'halloween-fruit-slice',
    gameName: 'Halloween Fruit Slice',
    titleAmharic: 'ሃሎዊን ፍሩት ስላይስ',
    category: 'Action',
    genre: 'Spooky Monster Fruit Slicing',
    tagline: 'Slice spooky monster fruits, dodge flying bombs, and conquer 40 very difficult levels!',
    description: 'A haunted twist on classic blade slicing! Swipe across flying monster fruits, carve juicy jack-o-lantern pumpkins, trigger multi-slice combos, and conquer 40 very difficult progressive levels.',
    thumbnail: getGameArtworkUrl('halloween-fruit-slice'),
    banner: getGameArtworkUrl('halloween-fruit-slice'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 12,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 185000,
    primaryColor: '#FF6B00',
    secondaryColor: '#00E5FF',
    instructions: [
      'Swipe finger or drag mouse across flying monster fruits to slice them',
      'Never slice danger bombs or your run ends immediately',
      'Slice multiple monster fruits in a single swipe to trigger high-scoring combos',
      'Level 1 is calibrated to be very difficult - maintain high focus!',
    ],
    controlsDescription: 'Swipe finger or click & drag mouse to slice.',
  },
  {
    gameId: 'hill-rider',
    gameName: 'Hill Climb',
    titleAmharic: 'ሂል ክላይምብ',
    category: 'Racing',
    genre: 'Highland Physics Driving',
    tagline: 'Conquer steep highland ridges and rugged mountain terrains!',
    description: 'Physics-based 2D hill climbing driving game. Control acceleration and vehicle pitch balance over steep highland hills, rocky gorges, and suspension bridges to reach the summit.',
    thumbnail: getGameArtworkUrl('hill-rider'),
    banner: getGameArtworkUrl('hill-rider'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: false,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 13,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.7,
    playsCount: 119800,
    primaryColor: '#0B3B70',
    secondaryColor: '#70C922',
    instructions: [
      'Hold Gas (Right) to accelerate uphill and release on steep drops to maintain traction',
      'Use Brake / Tilt (Left) to slow down and stabilize buggy balance mid-air',
      'Collect fuel jerrycans along the track before your vehicle engine runs dry',
    ],
    controlsDescription: 'Tap/hold Gas (Right) & Brake (Left) on screen, or use Arrow keys.',
  },
  {
    gameId: 'knife-madness',
    gameName: 'Knife Madness',
    titleAmharic: 'ናይፍ ማድነስ',
    category: 'Arcade',
    genre: '3D Precision Target Throwing',
    tagline: 'Throw steel knives, slice juicy apples, and shatter rotating 3D targets!',
    description: 'The ultimate test of precision timing and reflexes. Tap to throw steel knives into rotating 3D targets, slice apples for bonus points, avoid hitting existing blades, and shatter targets across 40 stages.',
    thumbnail: getGameArtworkUrl('knife-madness'),
    banner: getGameArtworkUrl('knife-madness'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 14,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 385000,
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    instructions: [
      'Tap the screen to launch a knife straight toward the rotating 3D target',
      'Time your throws carefully into open gaps to embed the required number of knives',
      'Avoid striking any pre-embedded knives or previously thrown blades',
    ],
    controlsDescription: 'Tap or click anywhere on screen to throw knife.',
  },
  {
    gameId: 'sorting-balls',
    gameName: 'Sorting Ball',
    titleAmharic: 'ሶርቲንግ ቦል',
    category: 'Puzzle',
    genre: '3D Color Sorting Puzzle',
    tagline: 'Sort vibrant glossy 3D spheres into glass cylinders across 40 mind-bending levels!',
    description: 'A beautifully relaxing and cerebral 3D color sorting puzzle. Strategically transfer colored spheres between glass cylinders until each tube contains exclusively identical colors.',
    thumbnail: getGameArtworkUrl('sorting-balls'),
    banner: getGameArtworkUrl('sorting-balls'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: false,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 15,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 215000,
    primaryColor: '#FF8A00',
    secondaryColor: '#171B26',
    instructions: [
      'Tap any tube to select its top ball, then tap another valid tube to transfer it',
      'A ball can only be placed into an empty tube or on top of a matching color',
      'Sort all balls of each color into their dedicated tubes to solve the puzzle',
    ],
    controlsDescription: 'Tap source tube to lift ball, tap destination tube to drop.',
  },
  {
    gameId: 'puzzle-block',
    gameName: 'Block',
    titleAmharic: 'ብሎክ',
    category: 'Puzzle',
    genre: '10x10 Wooden Block Puzzle',
    tagline: 'Place polyomino blocks on the 10x10 wooden board and clear full rows and columns!',
    description: 'The definitive 10x10 wooden block puzzle experience. Features 40 progressive championship levels, real drag & drop with touch-elevation offset, wood/ice/stone blockers, bomb blocks, and multi-line combo feedback.',
    thumbnail: getGameArtworkUrl('puzzle-block'),
    banner: getGameArtworkUrl('puzzle-block'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 16,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 520000,
    primaryColor: '#8a3f20',
    secondaryColor: '#f59e0b',
    instructions: [
      'Touch and drag block shapes from the bottom 3-piece tray onto the 10x10 board',
      'Fill complete 10-cell horizontal rows or vertical columns to collapse them',
      'Clear multiple lines simultaneously to trigger massive combo multipliers',
    ],
    controlsDescription: 'Touch and drag pieces onto the 10x10 board. Release over valid cells to place.',
  },
  {
    gameId: 'memory-match',
    gameName: 'Picture Match',
    titleAmharic: 'ፒክቸር ማች',
    category: 'Puzzle',
    genre: '3D Memory Card Pair Matching',
    tagline: 'Test your photographic memory and uncover legendary matching relics!',
    description: 'A premium, high-stakes memory matching experience. Flip beautifully beveled 3D cards, remember mysterious symbols and ancient artifacts, and uncover matching pairs across challenging stages.',
    thumbnail: getGameArtworkUrl('memory-match'),
    banner: getGameArtworkUrl('memory-match'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 17,
    providerId: 'prv_gameon_core',
    providerName: 'TelePlus Studios',
    rating: 4.95,
    playsCount: 142000,
    primaryColor: '#0B3B70',
    secondaryColor: '#8BCB3D',
    instructions: [
      'Tap face-down cards to reveal their hidden ancient symbol',
      'Find and match identical pairs to clear the board before time runs out',
      'Build consecutive match streaks to multiply your score and earn 3 gold stars',
    ],
    controlsDescription: 'Tap or click any card to flip.',
  },
  {
    gameId: 'color-rush',
    gameName: 'Color Rush',
    titleAmharic: 'ከለር ረሽ',
    category: 'Arcade',
    genre: 'Reflex Speed Timing Arcade',
    tagline: 'Test your lightning-fast reflex timing against the chromatic rush!',
    description: 'High-speed reflex reaction test. Match incoming chromatic neon pulses and rotating color gates before the countdown runs out. Speed increases with every successful combo!',
    thumbnail: getGameArtworkUrl('color-rush'),
    banner: getGameArtworkUrl('color-rush'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: false,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 18,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.8,
    playsCount: 132600,
    primaryColor: '#70C922',
    secondaryColor: '#0B3B70',
    instructions: [
      'Watch the target color flash on screen and tap the matching color paddle immediately',
      'Keep your reaction streak alive to trigger the 3x Multiplier Fever mode',
      'Avoid incorrect taps which instantly break your combo streak and cost a life',
    ],
    controlsDescription: 'Tap color buttons or press Arrow keys in rapid sequence.',
  },
  {
    gameId: 'soccer-shooter',
    gameName: 'Soccer Shooter',
    titleAmharic: 'ሶከር ሹተር',
    category: 'Sports',
    genre: 'Stadium Soccer Bubble Match',
    tagline: 'Kick 3D national soccer balls, execute wall bank shots, and clear 40 World Cup levels!',
    description: 'The championship edition of Soccer Shooter. Aim the precision dotted trajectory guide from the penalty spot, bank shots off stadium walls, trigger massive goalmouth cluster drops (+250 PTS), and manage penalty fouls.',
    thumbnail: getGameArtworkUrl('soccer-shooter'),
    banner: getGameArtworkUrl('soccer-shooter'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 19,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 275000,
    primaryColor: '#009739',
    secondaryColor: '#061325',
    instructions: [
      'Touch and drag in the stadium field to aim the precision dotted trajectory laser',
      'Bounce kicks off stadium walls to reach upper root soccer balls and trigger falling cascades',
      'Match 3 or more soccer balls to pop them with crowd celebration',
    ],
    controlsDescription: 'Touch/drag to aim, release to kick. Tap SWAP button to change upcoming ball.',
  },
  {
    gameId: 'dama',
    gameName: 'Dama',
    titleAmharic: 'ዳማ',
    category: 'Board',
    genre: '3D Ethiopian Draughts Strategy',
    tagline: 'Master the 3D championship draughts board against intelligent tactical AI!',
    description: 'Single-player 3D Draughts (Dama) against an advanced computer opponent. Experience physical wooden pieces, realistic board depth, mandatory captures, multi-jumps, and king crowning across progressive challenges.',
    thumbnail: getGameArtworkUrl('dama'),
    banner: getGameArtworkUrl('dama'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 20,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 156000,
    primaryColor: '#b45309',
    secondaryColor: '#1c1917',
    instructions: [
      'Tap your white pieces to reveal legal diagonal moves and mandatory capture paths',
      'Jumps and chain captures are strictly mandatory when available on the board',
      'Reach the opponent back rank to crown your piece into a powerful King',
    ],
    controlsDescription: 'Tap piece to select, then tap highlighted square to move.',
  },
  {
    gameId: 'button-soccer',
    gameName: 'Button Soccer',
    titleAmharic: 'የአዝራር እግር ኳስ',
    category: 'Sports',
    genre: '2026 World Tour Table Soccer',
    tagline: 'Drag back to aim & power, execute bank shots, and conquer 40 very difficult Championship levels!',
    description: 'The authentic 2026 World Tour button soccer tournament. Choose your nation, drag back from your 3D team discs to aim & power, score against very difficult AI opponents, and conquer 40 championship levels with pass-and-play 2-player mode.',
    thumbnail: getGameArtworkUrl('button-soccer'),
    banner: getGameArtworkUrl('button-soccer'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 21,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 210000,
    primaryColor: '#009C3B',
    secondaryColor: '#FFD54F',
    instructions: [
      'Touch and drag backward from your team disc to aim and set shot power',
      'Release to strike the soccer ball towards the opponent goal',
      'First team to reach the target goals or highest score at full time wins',
    ],
    controlsDescription: 'Touch and drag backward from your disc to aim & set power, release to shoot.',
  },
  {
    gameId: 'soccer-ping-pong',
    gameName: 'Soccer Ping Pong',
    titleAmharic: 'ሶከር ፒንግ ፖንግ',
    category: 'Sports',
    genre: '3D Soccer Table Tennis Arcade',
    tagline: 'Master professional 3D soccer table tennis across 20 stadium levels!',
    description: 'Control a high-velocity 3D soccer ball in fast-paced table tennis rallies against tactical AI opponents. Execute precision volleys, curve spins, power smashes, and obstacle rebounds across 6 progressive stadiums.',
    thumbnail: getGameArtworkUrl('soccer-ping-pong'),
    banner: getGameArtworkUrl('soccer-ping-pong'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 22,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 198000,
    primaryColor: '#1688C9',
    secondaryColor: '#8BCB3D',
    instructions: [
      'Slide your striker left and right to intercept the incoming soccer ball',
      'Time returns within the glowing green Sweet-Spot zone for power shots and combo multipliers',
      'Maintain continuous rallies without letting the ball pass your baseline',
    ],
    controlsDescription: 'Touch and drag striker horizontally, or use mouse / arrow keys.',
  },
  {
    gameId: 'moto-race',
    gameName: 'Moto Race',
    titleAmharic: 'ሞተር ሬስ',
    category: 'Racing',
    genre: '3D First-Person Highway Racing',
    tagline: 'First-person high-speed highway traffic racing across 40 progressive city levels!',
    description: 'Experience adrenaline-pumping 3D first-person motorcycle highway racing. Grip the handlebars, lean into turns, weave through high-density urban traffic, execute close near-miss overtakes, and conquer 40 progressive stages.',
    thumbnail: getGameArtworkUrl('moto-race'),
    banner: getGameArtworkUrl('moto-race'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 23,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 312000,
    primaryColor: '#0284c7',
    secondaryColor: '#8BCB3D',
    instructions: [
      'Steer left and right using screen arrow buttons or Left/Right arrow keys',
      'Hold GAS to accelerate up to 148 km/h and maintain high-speed streaks',
      'Execute close near-miss overtakes within inches of traffic for combo bonuses',
    ],
    controlsDescription: 'Touch steer/gas/brake buttons or use keyboard Arrow keys.',
  },
  {
    gameId: 'solitaire',
    gameName: 'Solitaire',
    titleAmharic: 'ሶሊቴር',
    category: 'Puzzle',
    genre: 'Classic Klondike Solitaire',
    tagline: 'Master authentic 52-card Klondike Solitaire across 40 championship levels!',
    description: 'The definitive Klondike Solitaire experience. Features Draw 1 and Draw 3 modes, authentic playing card artwork, deep emerald felt table acoustics, 40 progressive levels, daily challenge deals, unlimited undo, smart hints, and auto-complete.',
    thumbnail: getGameArtworkUrl('solitaire'),
    banner: getGameArtworkUrl('solitaire'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 24,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 485000,
    primaryColor: '#007a40',
    secondaryColor: '#ffd54f',
    instructions: [
      'Stack cards in descending order (King down to Ace) in alternating red and black suits',
      'Build the 4 foundation piles from Ace to King by suit',
      'Draw from the stock pile to discover new strategic cards',
    ],
    controlsDescription: 'Tap any card to auto-move, or drag and place freely. Tap stock to draw.',
  },
  {
    gameId: 'emoji-sorting-ball',
    gameName: 'EMOJI SORTING BALL',
    titleAmharic: 'ኢሞጂ ሶርቲንግ ቦል',
    category: 'Puzzle',
    genre: '3D Emoji Sorting Tournament Puzzle',
    tagline: 'Sort stylized 3D emoji vinyl spheres into color-coded crystal tubes across 40 levels!',
    description: 'The premier 3D Emoji Sorting tournament challenge. Transfer identical emoji spheres between vibrant tubes, utilize sequential multi-ball transfers, manage undos, hints, and buffer tubes, and maximize your tournament par efficiency.',
    thumbnail: getGameArtworkUrl('emoji-sorting-ball'),
    banner: getGameArtworkUrl('emoji-sorting-ball'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: false,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 25,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 280000,
    primaryColor: '#8B5CF6',
    secondaryColor: '#F472B6',
    instructions: [
      'Tap any tube to lift top emoji ball(s), then tap destination tube with matching emoji or empty space',
      'Contiguous matching emojis transfer together in a coordinated sequential wave',
      'Finish each puzzle in minimum moves to earn 3 stars and tournament Par bonus score',
      'Use Undo (-50 PTS), Hints (-150 PTS), or Add Extra Tube (-250 PTS) when stuck',
    ],
    controlsDescription: 'Tap source tube to select emoji, tap destination tube to transfer.',
  }
];

export const GameCatalog = {
  getAll(): CatalogGame[] {
    const orderIndexMap = new Map(MANDATORY_CATALOG_ORDER.map((id, idx) => [id, idx]));
    const allowedSet = new Set<string>(MANDATORY_CATALOG_ORDER);
    return INITIAL_GAME_CATALOG.filter((g) => g.isActive && allowedSet.has(g.gameId))
      .sort((a, b) => (orderIndexMap.get(a.gameId as any) ?? 999) - (orderIndexMap.get(b.gameId as any) ?? 999))
      .map((g) => {
        const art = getGameArtworkUrl(g.gameId);
        return art ? { ...g, thumbnail: art, banner: art } : g;
      });
  },

  getById(gameId: string): CatalogGame | undefined {
    const allowedSet = new Set<string>(MANDATORY_CATALOG_ORDER);
    if (!allowedSet.has(gameId)) return undefined;
    const g = INITIAL_GAME_CATALOG.find((g) => g.gameId === gameId && g.isActive);
    if (!g) return undefined;
    const art = getGameArtworkUrl(g.gameId);
    return art ? { ...g, thumbnail: art, banner: art } : g;
  },

  getByCategory(category: string): CatalogGame[] {
    if (category === 'All Games') {
      return this.getAll();
    }
    return this.getAll().filter((g) => g.category.toLowerCase() === category.toLowerCase());
  },

  /**
   * Only return categories that currently contain active games, with 'All Games' first
   */
  getCategoriesWithGames(): string[] {
    const categoriesSet = new Set<string>();
    this.getAll().forEach((game) => {
      categoriesSet.add(game.category);
    });

    // Ensure order conforms to ALL_STANDARD_CATEGORIES
    const ordered = ALL_STANDARD_CATEGORIES.filter(
      (cat) => cat === 'All Games' || categoriesSet.has(cat)
    );
    return ordered as unknown as string[];
  },

  getFeatured(): CatalogGame[] {
    return this.getAll().filter((g) => g.isFeatured);
  },

  getRecommended(): CatalogGame[] {
    return this.getAll().filter((g) => g.isRecommended);
  },

  getRecentlyPlayed(ids: string[]): CatalogGame[] {
    if (!ids || ids.length === 0) return [];
    return ids
      .map((id) => this.getById(id))
      .filter((g): g is CatalogGame => Boolean(g));
  },

  search(query: string): CatalogGame[] {
    if (!query.trim()) return this.getAll();
    const q = query.toLowerCase().trim();
    return this.getAll().filter(
      (g) =>
        g.gameName.toLowerCase().includes(q) ||
        g.titleAmharic.includes(query) ||
        g.category.toLowerCase().includes(q) ||
        g.tagline.toLowerCase().includes(q) ||
        g.genre.toLowerCase().includes(q)
    );
  },
};
