/**
 * MOTO RACE — 40 Progressive Level Configurations
 * 
 * Strict Specification:
 * - 40 continuous levels of increasing challenge
 * - Level 1 is ALREADY HARD: high traffic density, immediate lane navigation needed
 * - Levels 2-5: Very Hard
 * - Levels 6-10: Expert
 * - Levels 11-15: Advanced Expert
 * - Levels 16-20: Extreme
 * - Levels 21-25: Master
 * - Levels 26-30: Near-Perfect
 * - Levels 31-35: Elite
 * - Levels 36-39: Near-Ultimate
 * - Level 40: Ultimate Challenge
 * - Never shows "40 Levels" or total level count in UI; only displays "LEVEL {n}"
 */

export interface MotoRaceLevelConfig {
  level: number;
  title: string;
  difficultyLabel: string;
  targetDistanceMeters: number;
  timeLimitSeconds: number;
  trafficDensity: number; // Maximum concurrent active vehicles on road
  trafficBaseSpeedKmh: number; // Average speed of civilian traffic
  truckRatio: number; // Ratio of large box trucks / delivery vans (0.0 to 1.0)
  laneChangeFrequency: number; // Likelihood of vehicles switching lanes (0.1 to 1.0)
  nearMissBonusSeconds: number; // Bonus time rewarded on close overtakes
  nearMissBonusPoints: number; // Bonus points rewarded per close overtake
  speedBonusThresholdKmh: number; // Speed above which High-Speed points accumulate
  environmentTheme: 'noon' | 'sunset' | 'night' | 'overcast';
}

export const MOTO_RACE_LEVELS: MotoRaceLevelConfig[] = [
  // Levels 1 - 5: HARD TO VERY HARD
  {
    level: 1,
    title: 'Boulevard Rush',
    difficultyLabel: 'Hard',
    targetDistanceMeters: 900,
    timeLimitSeconds: 38,
    trafficDensity: 5,
    trafficBaseSpeedKmh: 50,
    truckRatio: 0.2,
    laneChangeFrequency: 0.25,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 150,
    speedBonusThresholdKmh: 90,
    environmentTheme: 'noon',
  },
  {
    level: 2,
    title: 'Downtown Expressway',
    difficultyLabel: 'Hard',
    targetDistanceMeters: 1000,
    timeLimitSeconds: 40,
    trafficDensity: 6,
    trafficBaseSpeedKmh: 52,
    truckRatio: 0.25,
    laneChangeFrequency: 0.3,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 160,
    speedBonusThresholdKmh: 90,
    environmentTheme: 'noon',
  },
  {
    level: 3,
    title: 'Sunset Arterial',
    difficultyLabel: 'Very Hard',
    targetDistanceMeters: 1100,
    timeLimitSeconds: 42,
    trafficDensity: 6,
    trafficBaseSpeedKmh: 54,
    truckRatio: 0.28,
    laneChangeFrequency: 0.35,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 170,
    speedBonusThresholdKmh: 92,
    environmentTheme: 'sunset',
  },
  {
    level: 4,
    title: 'Avenue of Palms',
    difficultyLabel: 'Very Hard',
    targetDistanceMeters: 1200,
    timeLimitSeconds: 44,
    trafficDensity: 7,
    trafficBaseSpeedKmh: 55,
    truckRatio: 0.3,
    laneChangeFrequency: 0.4,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 180,
    speedBonusThresholdKmh: 92,
    environmentTheme: 'noon',
  },
  {
    level: 5,
    title: 'Harbor Flyover',
    difficultyLabel: 'Very Hard',
    targetDistanceMeters: 1300,
    timeLimitSeconds: 46,
    trafficDensity: 7,
    trafficBaseSpeedKmh: 56,
    truckRatio: 0.32,
    laneChangeFrequency: 0.42,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 190,
    speedBonusThresholdKmh: 94,
    environmentTheme: 'sunset',
  },

  // Levels 6 - 10: EXPERT
  {
    level: 6,
    title: 'Skyline Bypass',
    difficultyLabel: 'Expert',
    targetDistanceMeters: 1400,
    timeLimitSeconds: 48,
    trafficDensity: 8,
    trafficBaseSpeedKmh: 58,
    truckRatio: 0.35,
    laneChangeFrequency: 0.45,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 200,
    speedBonusThresholdKmh: 95,
    environmentTheme: 'overcast',
  },
  {
    level: 7,
    title: 'Commercial Corridor',
    difficultyLabel: 'Expert',
    targetDistanceMeters: 1500,
    timeLimitSeconds: 50,
    trafficDensity: 8,
    trafficBaseSpeedKmh: 60,
    truckRatio: 0.35,
    laneChangeFrequency: 0.48,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 210,
    speedBonusThresholdKmh: 95,
    environmentTheme: 'noon',
  },
  {
    level: 8,
    title: 'Twilight Ring Road',
    difficultyLabel: 'Expert',
    targetDistanceMeters: 1600,
    timeLimitSeconds: 52,
    trafficDensity: 8,
    trafficBaseSpeedKmh: 60,
    truckRatio: 0.38,
    laneChangeFrequency: 0.5,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 220,
    speedBonusThresholdKmh: 96,
    environmentTheme: 'sunset',
  },
  {
    level: 9,
    title: 'Financial Viaduct',
    difficultyLabel: 'Expert',
    targetDistanceMeters: 1700,
    timeLimitSeconds: 54,
    trafficDensity: 9,
    trafficBaseSpeedKmh: 62,
    truckRatio: 0.4,
    laneChangeFrequency: 0.52,
    nearMissBonusSeconds: 0.3,
    nearMissBonusPoints: 230,
    speedBonusThresholdKmh: 96,
    environmentTheme: 'night',
  },
  {
    level: 10,
    title: 'Metro Freeway Alpha',
    difficultyLabel: 'Expert',
    targetDistanceMeters: 1800,
    timeLimitSeconds: 55,
    trafficDensity: 9,
    trafficBaseSpeedKmh: 62,
    truckRatio: 0.4,
    laneChangeFrequency: 0.55,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 240,
    speedBonusThresholdKmh: 98,
    environmentTheme: 'sunset',
  },

  // Levels 11 - 15: ADVANCED EXPERT
  {
    level: 11,
    title: 'Speedway Junction',
    difficultyLabel: 'Advanced Expert',
    targetDistanceMeters: 1900,
    timeLimitSeconds: 57,
    trafficDensity: 9,
    trafficBaseSpeedKmh: 64,
    truckRatio: 0.42,
    laneChangeFrequency: 0.58,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 250,
    speedBonusThresholdKmh: 98,
    environmentTheme: 'noon',
  },
  {
    level: 12,
    title: 'Industrial Gateway',
    difficultyLabel: 'Advanced Expert',
    targetDistanceMeters: 2000,
    timeLimitSeconds: 58,
    trafficDensity: 10,
    trafficBaseSpeedKmh: 64,
    truckRatio: 0.45,
    laneChangeFrequency: 0.6,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 260,
    speedBonusThresholdKmh: 100,
    environmentTheme: 'overcast',
  },
  {
    level: 13,
    title: 'Neon Overpass',
    difficultyLabel: 'Advanced Expert',
    targetDistanceMeters: 2100,
    timeLimitSeconds: 60,
    trafficDensity: 10,
    trafficBaseSpeedKmh: 65,
    truckRatio: 0.42,
    laneChangeFrequency: 0.62,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 270,
    speedBonusThresholdKmh: 100,
    environmentTheme: 'night',
  },
  {
    level: 14,
    title: 'Central Interchange',
    difficultyLabel: 'Advanced Expert',
    targetDistanceMeters: 2150,
    timeLimitSeconds: 60,
    trafficDensity: 10,
    trafficBaseSpeedKmh: 66,
    truckRatio: 0.44,
    laneChangeFrequency: 0.64,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 280,
    speedBonusThresholdKmh: 100,
    environmentTheme: 'sunset',
  },
  {
    level: 15,
    title: 'Grand Boulevard Dash',
    difficultyLabel: 'Advanced Expert',
    targetDistanceMeters: 2200,
    timeLimitSeconds: 61,
    trafficDensity: 10,
    trafficBaseSpeedKmh: 66,
    truckRatio: 0.45,
    laneChangeFrequency: 0.65,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 290,
    speedBonusThresholdKmh: 102,
    environmentTheme: 'noon',
  },

  // Levels 16 - 20: EXTREME
  {
    level: 16,
    title: 'Thunder Corridor',
    difficultyLabel: 'Extreme',
    targetDistanceMeters: 2250,
    timeLimitSeconds: 61,
    trafficDensity: 11,
    trafficBaseSpeedKmh: 68,
    truckRatio: 0.45,
    laneChangeFrequency: 0.66,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 300,
    speedBonusThresholdKmh: 102,
    environmentTheme: 'overcast',
  },
  {
    level: 17,
    title: 'Midnight Blitz',
    difficultyLabel: 'Extreme',
    targetDistanceMeters: 2300,
    timeLimitSeconds: 62,
    trafficDensity: 11,
    trafficBaseSpeedKmh: 68,
    truckRatio: 0.46,
    laneChangeFrequency: 0.68,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 310,
    speedBonusThresholdKmh: 104,
    environmentTheme: 'night',
  },
  {
    level: 18,
    title: 'Golden Hour Gridlock',
    difficultyLabel: 'Extreme',
    targetDistanceMeters: 2350,
    timeLimitSeconds: 62,
    trafficDensity: 11,
    trafficBaseSpeedKmh: 70,
    truckRatio: 0.46,
    laneChangeFrequency: 0.7,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 320,
    speedBonusThresholdKmh: 104,
    environmentTheme: 'sunset',
  },
  {
    level: 19,
    title: 'Terminal Speed Run',
    difficultyLabel: 'Extreme',
    targetDistanceMeters: 2400,
    timeLimitSeconds: 63,
    trafficDensity: 11,
    trafficBaseSpeedKmh: 70,
    truckRatio: 0.48,
    laneChangeFrequency: 0.72,
    nearMissBonusSeconds: 0.35,
    nearMissBonusPoints: 330,
    speedBonusThresholdKmh: 105,
    environmentTheme: 'noon',
  },
  {
    level: 20,
    title: 'Apex Highway Summit',
    difficultyLabel: 'Extreme',
    targetDistanceMeters: 2450,
    timeLimitSeconds: 63,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 70,
    truckRatio: 0.48,
    laneChangeFrequency: 0.74,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 350,
    speedBonusThresholdKmh: 105,
    environmentTheme: 'sunset',
  },

  // Levels 21 - 25: MASTER
  {
    level: 21,
    title: 'Supersonic Transit',
    difficultyLabel: 'Master',
    targetDistanceMeters: 2500,
    timeLimitSeconds: 64,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 72,
    truckRatio: 0.48,
    laneChangeFrequency: 0.75,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 360,
    speedBonusThresholdKmh: 106,
    environmentTheme: 'noon',
  },
  {
    level: 22,
    title: 'Cyber City Expressway',
    difficultyLabel: 'Master',
    targetDistanceMeters: 2550,
    timeLimitSeconds: 64,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 72,
    truckRatio: 0.5,
    laneChangeFrequency: 0.76,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 370,
    speedBonusThresholdKmh: 106,
    environmentTheme: 'night',
  },
  {
    level: 23,
    title: 'Vortex Overpass',
    difficultyLabel: 'Master',
    targetDistanceMeters: 2600,
    timeLimitSeconds: 65,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 74,
    truckRatio: 0.5,
    laneChangeFrequency: 0.78,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 380,
    speedBonusThresholdKmh: 108,
    environmentTheme: 'sunset',
  },
  {
    level: 24,
    title: 'Titan Cargo Lane',
    difficultyLabel: 'Master',
    targetDistanceMeters: 2650,
    timeLimitSeconds: 65,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 74,
    truckRatio: 0.52,
    laneChangeFrequency: 0.8,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 390,
    speedBonusThresholdKmh: 108,
    environmentTheme: 'overcast',
  },
  {
    level: 25,
    title: 'Infinity Skyway',
    difficultyLabel: 'Master',
    targetDistanceMeters: 2700,
    timeLimitSeconds: 66,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 75,
    truckRatio: 0.5,
    laneChangeFrequency: 0.82,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 400,
    speedBonusThresholdKmh: 110,
    environmentTheme: 'noon',
  },

  // Levels 26 - 30: NEAR-PERFECT
  {
    level: 26,
    title: 'Precision Slalom',
    difficultyLabel: 'Near-Perfect',
    targetDistanceMeters: 2750,
    timeLimitSeconds: 66,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 75,
    truckRatio: 0.5,
    laneChangeFrequency: 0.82,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 410,
    speedBonusThresholdKmh: 110,
    environmentTheme: 'sunset',
  },
  {
    level: 27,
    title: 'Ghost City Parkway',
    difficultyLabel: 'Near-Perfect',
    targetDistanceMeters: 2800,
    timeLimitSeconds: 67,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 76,
    truckRatio: 0.5,
    laneChangeFrequency: 0.84,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 420,
    speedBonusThresholdKmh: 110,
    environmentTheme: 'night',
  },
  {
    level: 28,
    title: 'Metro Stormway',
    difficultyLabel: 'Near-Perfect',
    targetDistanceMeters: 2850,
    timeLimitSeconds: 67,
    trafficDensity: 12,
    trafficBaseSpeedKmh: 76,
    truckRatio: 0.52,
    laneChangeFrequency: 0.84,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 430,
    speedBonusThresholdKmh: 112,
    environmentTheme: 'overcast',
  },
  {
    level: 29,
    title: 'Asphalt Odyssey',
    difficultyLabel: 'Near-Perfect',
    targetDistanceMeters: 2900,
    timeLimitSeconds: 68,
    trafficDensity: 13,
    trafficBaseSpeedKmh: 76,
    truckRatio: 0.52,
    laneChangeFrequency: 0.85,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 440,
    speedBonusThresholdKmh: 112,
    environmentTheme: 'sunset',
  },
  {
    level: 30,
    title: 'Zenith Grand Prix',
    difficultyLabel: 'Near-Perfect',
    targetDistanceMeters: 2950,
    timeLimitSeconds: 68,
    trafficDensity: 13,
    trafficBaseSpeedKmh: 78,
    truckRatio: 0.52,
    laneChangeFrequency: 0.86,
    nearMissBonusSeconds: 0.4,
    nearMissBonusPoints: 450,
    speedBonusThresholdKmh: 114,
    environmentTheme: 'noon',
  },

  // Levels 31 - 35: ELITE
  {
    level: 31,
    title: 'Hyperdrive Causeway',
    difficultyLabel: 'Elite',
    targetDistanceMeters: 3000,
    timeLimitSeconds: 69,
    trafficDensity: 13,
    trafficBaseSpeedKmh: 78,
    truckRatio: 0.52,
    laneChangeFrequency: 0.86,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 460,
    speedBonusThresholdKmh: 114,
    environmentTheme: 'night',
  },
  {
    level: 32,
    title: 'Nitro Boulevard',
    difficultyLabel: 'Elite',
    targetDistanceMeters: 3050,
    timeLimitSeconds: 69,
    trafficDensity: 13,
    trafficBaseSpeedKmh: 78,
    truckRatio: 0.54,
    laneChangeFrequency: 0.87,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 470,
    speedBonusThresholdKmh: 115,
    environmentTheme: 'sunset',
  },
  {
    level: 33,
    title: 'Iron Gate Throughway',
    difficultyLabel: 'Elite',
    targetDistanceMeters: 3100,
    timeLimitSeconds: 70,
    trafficDensity: 13,
    trafficBaseSpeedKmh: 80,
    truckRatio: 0.54,
    laneChangeFrequency: 0.88,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 480,
    speedBonusThresholdKmh: 115,
    environmentTheme: 'noon',
  },
  {
    level: 34,
    title: 'Mirage Viaduct',
    difficultyLabel: 'Elite',
    targetDistanceMeters: 3150,
    timeLimitSeconds: 70,
    trafficDensity: 13,
    trafficBaseSpeedKmh: 80,
    truckRatio: 0.54,
    laneChangeFrequency: 0.88,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 490,
    speedBonusThresholdKmh: 116,
    environmentTheme: 'overcast',
  },
  {
    level: 35,
    title: 'Obsidian Arterial',
    difficultyLabel: 'Elite',
    targetDistanceMeters: 3200,
    timeLimitSeconds: 71,
    trafficDensity: 13,
    trafficBaseSpeedKmh: 80,
    truckRatio: 0.55,
    laneChangeFrequency: 0.89,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 500,
    speedBonusThresholdKmh: 116,
    environmentTheme: 'night',
  },

  // Levels 36 - 39: NEAR-ULTIMATE
  {
    level: 36,
    title: 'Quantum Gridlock',
    difficultyLabel: 'Near-Ultimate',
    targetDistanceMeters: 3250,
    timeLimitSeconds: 71,
    trafficDensity: 14,
    trafficBaseSpeedKmh: 82,
    truckRatio: 0.55,
    laneChangeFrequency: 0.9,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 520,
    speedBonusThresholdKmh: 118,
    environmentTheme: 'sunset',
  },
  {
    level: 37,
    title: 'Shadowline Sprint',
    difficultyLabel: 'Near-Ultimate',
    targetDistanceMeters: 3300,
    timeLimitSeconds: 72,
    trafficDensity: 14,
    trafficBaseSpeedKmh: 82,
    truckRatio: 0.55,
    laneChangeFrequency: 0.9,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 540,
    speedBonusThresholdKmh: 118,
    environmentTheme: 'noon',
  },
  {
    level: 38,
    title: 'Velocity Horizon',
    difficultyLabel: 'Near-Ultimate',
    targetDistanceMeters: 3350,
    timeLimitSeconds: 72,
    trafficDensity: 14,
    trafficBaseSpeedKmh: 84,
    truckRatio: 0.56,
    laneChangeFrequency: 0.92,
    nearMissBonusSeconds: 0.45,
    nearMissBonusPoints: 560,
    speedBonusThresholdKmh: 120,
    environmentTheme: 'overcast',
  },
  {
    level: 39,
    title: 'Crucible Highway',
    difficultyLabel: 'Near-Ultimate',
    targetDistanceMeters: 3400,
    timeLimitSeconds: 73,
    trafficDensity: 14,
    trafficBaseSpeedKmh: 84,
    truckRatio: 0.56,
    laneChangeFrequency: 0.92,
    nearMissBonusSeconds: 0.5,
    nearMissBonusPoints: 580,
    speedBonusThresholdKmh: 120,
    environmentTheme: 'sunset',
  },

  // Level 40: ULTIMATE CHALLENGE
  {
    level: 40,
    title: 'Ultimate Champion Expressway',
    difficultyLabel: 'Ultimate Challenge',
    targetDistanceMeters: 3500,
    timeLimitSeconds: 74,
    trafficDensity: 14,
    trafficBaseSpeedKmh: 85,
    truckRatio: 0.58,
    laneChangeFrequency: 0.95,
    nearMissBonusSeconds: 0.5,
    nearMissBonusPoints: 650,
    speedBonusThresholdKmh: 122,
    environmentTheme: 'night',
  },
];

export function getMotoRaceLevel(levelNumber: number): MotoRaceLevelConfig {
  const index = Math.max(0, Math.min(MOTO_RACE_LEVELS.length - 1, levelNumber - 1));
  return MOTO_RACE_LEVELS[index];
}
