import { GameConfig } from './types';

export const GAME_CONFIGS: Record<string, GameConfig> = {
  'candy-blast': {
    gameId: 'candy-blast',
    title: 'Candy Crush',
    titleAmharic: 'ኬንዲ ክራሽ',
    genre: 'Match-3 Puzzle',
    tagline: 'Swap delicious candies to create mouthwatering combos!',
    description: 'Switch and match vibrant confectionery candies in this sugary puzzle adventure to progress through delightful levels.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-pink-500 via-rose-500 to-purple-600',
      accentColor: '#F43F5E',
      badgeBg: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
      cardBg: 'bg-slate-900/90 border-pink-500/30',
      iconEmoji: '🍬',
      bannerBg: 'bg-gradient-to-b from-pink-900/60 via-purple-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Swap adjacent candies to create horizontal or vertical rows of 3 or more identical sweets to clear them from the board.',
      rules: [
        'Match 3 candies of the same color to pop them and score points.',
        'Match 4 candies in a row to create a Striped Candy that clears entire lines.',
        'Match 5 candies in an L or T shape to create a Wrapped Candy with explosive radius.',
        'Match 5 in a straight line to produce a Color Bomb that clears all candies of one color.',
        'Complete the target score before running out of moves.',
      ],
      controls: 'Tap or drag a candy toward an adjacent tile to swap positions.',
      proTips: [
        'Prioritize moves near the bottom of the board to trigger cascade chain reactions.',
        'Combine two special candies (like Color Bomb + Striped Candy) for massive board-clearing effects.',
      ],
    },
    achievements: [
      { id: 'cb_first_match', title: 'Sugar Rush', desc: 'Complete your first candy match', icon: '🍬', maxProgress: 1 },
      { id: 'cb_combo_master', title: 'Sugar Star', desc: 'Trigger a 4x cascade combo', icon: '⭐', maxProgress: 4 },
      { id: 'cb_color_bomb', title: 'Confectionery King', desc: 'Create 5 Color Bombs', icon: '👑', maxProgress: 5 },
    ],
    about: {
      version: '2.4.0',
      developer: 'TelePlay Game Studios',
      engine: 'HTML5 WebGL Canvas Engine',
      features: ['Dynamic physics cascades', 'Special candy fusions', 'Offline play support'],
    },
  },

  'world-legends': {
    gameId: 'world-legends',
    title: 'Word Legend',
    titleAmharic: 'ዎርድ ሌጀንድስ',
    genre: 'Word Puzzle',
    tagline: 'Connect letter tiles to discover hidden words and expand vocabulary!',
    description: 'Swipe across the circular letter dial to build valid Ethiopian and international words, uncover bonus anagrams, and master levels.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'WORDS',
    theme: {
      primaryGradient: 'from-amber-500 via-orange-500 to-yellow-600',
      accentColor: '#F59E0B',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '🔤',
      bannerBg: 'bg-gradient-to-b from-amber-950/60 via-stone-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Form valid words by connecting the given letters in the letter dial to fill the crossword grid.',
      rules: [
        'Swipe through adjacent letters to spell words.',
        'Words must match the crossword crossword slots on the board.',
        'Discover extra dictionary words to fill your Bonus Coin jar.',
        'Shuffle letters when you are stuck to see new anagram patterns.',
        'Use the Hint magnifying glass if you need the first letter revealed.',
      ],
      controls: 'Touch and swipe from letter to letter without lifting your finger.',
      proTips: [
        'Look for common prefixes (UN, RE) and suffixes (ED, ING, S).',
        'Find shorter 3-letter combinations first to open up clues for longer words.',
      ],
    },
    achievements: [
      { id: 'wl_word_smith', title: 'Word Smith', desc: 'Solve 10 crossword levels', icon: '📖', maxProgress: 10 },
      { id: 'wl_lexicon', title: 'Lexicon Master', desc: 'Discover 25 bonus words', icon: '🧠', maxProgress: 25 },
      { id: 'wl_speedy', title: 'Speed Reader', desc: 'Solve a level in under 30 seconds', icon: '⚡', maxProgress: 1 },
    ],
    about: {
      version: '1.8.2',
      developer: 'TelePlay Game Studios',
      engine: 'React Vector Lexical Engine',
      features: ['Bilingual word banks', 'Anagram discovery solver', 'Vocabulary expansion'],
    },
  },

  'juicy-match': {
    gameId: 'juicy-match',
    title: 'Candy Crush',
    titleAmharic: 'ኬንዲ ጁሲ',
    genre: 'Fruit Match-3',
    tagline: 'Slice and match tropical fruits in vivid splash puzzles!',
    description: 'Embark on a refreshing tropical orchard journey swapping watermelons, kiwis, oranges, and strawberries with juicy splatters.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-emerald-500 via-teal-500 to-cyan-600',
      accentColor: '#10B981',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '🍉',
      bannerBg: 'bg-gradient-to-b from-emerald-950/60 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Swap fruits to match 3 or more of the same variety and pop obstacles like jelly and fruit baskets.',
      rules: [
        'Match 3 fruits in any orthogonal line to harvest them.',
        'Match 4 fruits to create a Splash Juice Rocket.',
        'Match 5 in a row for the Rainbow Blender that clears all fruits of a type.',
        'Clear all jelly layers and complete level quotas before moves run out.',
      ],
      controls: 'Tap or drag a fruit toward an adjacent fruit to swap.',
      proTips: [
        'Focus on clearing corner jellies early as they are harder to reach.',
        'Save your boosters for tricky levels with frozen fruit cages.',
      ],
    },
    achievements: [
      { id: 'jm_harvest', title: 'Fruit Harvester', desc: 'Match 100 tropical fruits', icon: '🍓', maxProgress: 100 },
      { id: 'jm_splash', title: 'Mega Splash', desc: 'Create 10 Juice Rockets', icon: '🚀', maxProgress: 10 },
      { id: 'jm_orchard', title: 'Orchard Champ', desc: 'Clear 15 juicy stages', icon: '🏆', maxProgress: 15 },
    ],
    about: {
      version: '3.1.0',
      developer: 'TelePlay Game Studios',
      engine: 'JuiceFX WebGL Match Engine',
      features: ['Realistic splash particles', 'Tactile haptic pops', 'Orchard campaign map'],
    },
  },

  'solitaire': {
    gameId: 'solitaire',
    title: 'Solitaire',
    titleAmharic: 'ሶሊቴር',
    genre: 'Classic Card',
    tagline: 'Timeless Klondike Solitaire with smooth card deals and smart hints!',
    description: 'Play the world-renowned Klondike Solitaire card game. Stack tableau columns in descending order with alternating red and black suits.',
    hasLevels: false,
    scoreType: 'score',
    scoreLabel: 'SCORE',
    theme: {
      primaryGradient: 'from-emerald-700 via-green-800 to-teal-900',
      accentColor: '#059669',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '♠️',
      bannerBg: 'bg-gradient-to-b from-emerald-950/80 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Organize a standard 52-card deck into the 4 foundation piles from Ace up to King by suit.',
      rules: [
        'Build foundations up from Ace to King (A, 2, 3... Q, K) sorted by suit.',
        'Build tableau columns down in descending rank with alternating red and black colors.',
        'Only Kings can be placed into empty tableau spaces.',
        'Draw cards from the stockpile when no tableau moves are available.',
      ],
      controls: 'Tap a card to auto-move it to the best available position, or drag and drop onto a column.',
      proTips: [
        'Always uncover face-down tableau cards first before drawing from the stock.',
        'Do not empty a tableau column unless you have a King ready to occupy it.',
      ],
    },
    achievements: [
      { id: 'sol_first_win', title: 'Card Shark', desc: 'Win your first Solitaire deal', icon: '🃏', maxProgress: 1 },
      { id: 'sol_speed_deal', title: 'Lightning Hands', desc: 'Finish a deal in under 3 minutes', icon: '⏱️', maxProgress: 1 },
      { id: 'sol_streak_3', title: 'Triple Crown', desc: 'Win 3 deals in a row', icon: '👑', maxProgress: 3 },
    ],
    about: {
      version: '2.5.0',
      developer: 'TelePlay Game Studios',
      engine: 'CardCanvas 2D Physics',
      features: ['Solvable deal algorithm', 'Unlimited undo & auto-hints', 'Vegas and Standard scoring'],
    },
  },

  'puzzle-block': {
    gameId: 'puzzle-block',
    title: 'Block',
    titleAmharic: 'ፓዝል ብሎክ',
    genre: 'Grid Block Puzzle',
    tagline: 'Fit wooden and jewel shapes on the 10x10 board to clear rows and columns!',
    description: 'Strategic block placement game on a clean 10x10 board. Clear full horizontal lines and vertical columns to keep the board clear.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-amber-600 via-yellow-600 to-orange-700',
      accentColor: '#D97706',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '🧱',
      bannerBg: 'bg-gradient-to-b from-amber-950/70 via-stone-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Place 3 provided polyomino block pieces onto the 10x10 board. Fill full rows or columns to clear them and score points.',
      rules: [
        'Drag pieces from the tray onto the 10x10 board.',
        'Blocks cannot overlap and cannot be rotated.',
        'Complete a full horizontal row or vertical column of 10 blocks to clear it.',
        'Clearing multiple rows/columns simultaneously triggers mega combo bonuses.',
        'Game is over when there is no room left on the board for any of the 3 pieces.',
      ],
      controls: 'Touch and drag a piece onto any valid empty cells on the board.',
      proTips: [
        'Always maintain space for the large 3x3 square and 5-block long lines.',
        'Avoid creating isolated 1-cell gaps that are hard to fill.',
      ],
    },
    achievements: [
      { id: 'pb_first_clear', title: 'Clear Builder', desc: 'Clear your first line', icon: '🪵', maxProgress: 1 },
      { id: 'pb_triple_clear', title: 'Combo Master', desc: 'Clear 3 lines in one placement', icon: '💥', maxProgress: 1 },
      { id: 'pb_high_score', title: 'Block Legend', desc: 'Score over 2,000 points', icon: '🏆', maxProgress: 2000 },
    ],
    about: {
      version: '3.0.0',
      developer: 'TelePlay Game Studios',
      engine: 'High-Precision 10x10 Matrix Engine',
      features: ['Clean empty board initialization', '40 tournament stages', 'Real-time score persistence'],
    },
  },

  'sorting-balls': {
    gameId: 'sorting-balls',
    title: 'Sorting Ball',
    titleAmharic: 'ሶርቲንግ ቦልስ',
    genre: 'Color Sorting Puzzle',
    tagline: 'Sort vibrant colored 3D spheres into matching test tubes!',
    description: 'Challenging logic puzzle with 3D glass tubes. Transfer top balls between flasks until every tube contains only one uniform color.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'stage',
    scoreLabel: 'STAGE',
    theme: {
      primaryGradient: 'from-violet-600 via-indigo-600 to-purple-800',
      accentColor: '#8B5CF6',
      badgeBg: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
      cardBg: 'bg-slate-900/90 border-violet-500/30',
      iconEmoji: '🧪',
      bannerBg: 'bg-gradient-to-b from-indigo-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Pour balls between glass tubes so that all balls of the same color are grouped together in their own tube.',
      rules: [
        'Tap a tube to lift its top ball(s).',
        'Tap another tube to pour the ball into it.',
        'You can only pour a ball on top of another ball of the same color.',
        'A tube can hold at most 4 balls.',
        'An empty tube can accept any color ball.',
        'Level is won when all tubes either contain 4 balls of the same color or are completely empty.',
      ],
      controls: 'Tap on a tube to select, then tap target tube to transfer.',
      proTips: [
        'Use empty tubes wisely as temporary parking spots for blocked colors.',
        'Look ahead: clear one color entirely to free up a permanent sorting tube.',
      ],
    },
    achievements: [
      { id: 'sb_first_sort', title: 'Lab Assistant', desc: 'Sort your first tube', icon: '🧪', maxProgress: 1 },
      { id: 'sb_perfect_sort', title: 'Master Chemist', desc: 'Complete 5 levels with 3 stars', icon: '🌟', maxProgress: 5 },
      { id: 'sb_puzzle_genius', title: 'Color Prodigy', desc: 'Solve Level 20', icon: '🎓', maxProgress: 20 },
    ],
    about: {
      version: '2.8.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 3D Realistic Shader Engine',
      features: ['Realistic glass refraction', 'Coordinated multi-ball pours', 'Undo & extra tube powerups'],
    },
  },

  'emoji-sorting-ball': {
    gameId: 'emoji-sorting-ball',
    title: 'EMOJI SORTING BALL',
    titleAmharic: 'ኢሞጂ ሶርቲንግ ቦል',
    genre: '3D Emoji Sorting Tournament Puzzle',
    tagline: 'Sort stylized 3D emoji vinyl spheres into color-coded crystal tubes across 40 levels!',
    description: 'The premier 3D Emoji Sorting tournament challenge. Transfer identical emoji spheres between vibrant tubes, utilize sequential multi-ball transfers, manage undos, hints, and buffer tubes, and maximize your tournament par efficiency.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-violet-600 via-fuchsia-600 to-pink-600',
      accentColor: '#8B5CF6',
      badgeBg: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
      cardBg: 'bg-slate-900/90 border-violet-500/30',
      iconEmoji: '😀',
      bannerBg: 'bg-gradient-to-b from-purple-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Sort matching 3D emoji spheres into designated color-coded crystal tubes until every tube is solved.',
      rules: [
        'Tap a tube to lift its top emoji sphere (or contiguous matching group).',
        'Tap another tube to transfer the emoji spheres into it.',
        'Spheres can only be transferred into an empty tube or onto a matching emoji type.',
        'Each tube holds up to 4 emoji spheres.',
        'Solve all tubes with 4 matching emojis to complete the level and claim tournament bonuses.',
      ],
      controls: 'Tap on a tube to select, then tap destination tube to transfer.',
      proTips: [
        'Matching contiguous emojis lift and move together in a multi-ball wave.',
        'Aim to beat the Par move count for 3 stars and maximum tournament score.',
        'Use extra tubes or undo if you reach a dead end.',
      ],
    },
    achievements: [
      { id: 'esb_first_level', title: 'First Emoji Sort', desc: 'Complete your first Emoji Sorting level', icon: '😀', maxProgress: 1 },
      { id: 'esb_star_sorter', title: 'Emoji Virtuoso', desc: 'Achieve 3 stars on 10 levels', icon: '🌟', maxProgress: 10 },
      { id: 'esb_master_mind', title: 'Grand Emoji Master', desc: 'Complete all 40 tournament levels', icon: '👑', maxProgress: 40 },
    ],
    about: {
      version: '1.0.0',
      developer: 'GameON Studios',
      engine: 'Three.js 3D Vinyl Sphere Engine',
      features: ['Stylized 3D vinyl emoji spheres', 'Mandatory 8-tube vibrant palette', '40 isomorphic tournament levels', 'Undo, Hint, and Extra Buffer Tubes'],
    },
  },

  'bubble-shooter': {
    gameId: 'bubble-shooter',
    title: 'Bubble Pop',
    titleAmharic: 'ባብል ሹተር',
    genre: 'Arcade Bubble Match',
    tagline: 'Aim cannon and pop clusters of 3 or more matching bubbles!',
    description: 'Classic arcade bubble popping game with precision angle aiming, bouncy wall bank shots, and cascading ceiling drops.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-sky-500 via-blue-600 to-indigo-700',
      accentColor: '#38BDF8',
      badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-500/40',
      cardBg: 'bg-slate-900/90 border-sky-500/30',
      iconEmoji: '🫧',
      bannerBg: 'bg-gradient-to-b from-sky-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Launch colored bubbles at the suspended ceiling cluster to form groups of 3 or more matching colors.',
      rules: [
        'Aim the cannon using the laser trajectory guideline.',
        'Release to shoot the current projectile bubble.',
        'Matching 3 or more bubbles of identical color will pop them.',
        'Any disconnected bubbles suspended below the popped group will drop and grant bonus points.',
        'Clear all bubbles before they descend below the danger threshold line.',
      ],
      controls: 'Touch and drag on screen to aim, release your finger to fire.',
      proTips: [
        'Bank shots off the side walls to reach tricky clusters high up.',
        'Target root attachments: dropping a cluster yields much more score than popping individually.',
      ],
    },
    achievements: [
      { id: 'bs_popper', title: 'Bubble Popper', desc: 'Pop 50 bubbles', icon: '🫧', maxProgress: 50 },
      { id: 'bs_avalanche', title: 'Bubble Avalanche', desc: 'Drop 10 bubbles in one shot', icon: '🏔️', maxProgress: 10 },
      { id: 'bs_sniper', title: 'Precision Gunner', desc: 'Clear 5 levels with no missed shots', icon: '🎯', maxProgress: 5 },
    ],
    about: {
      version: '2.3.0',
      developer: 'TelePlay Game Studios',
      engine: 'Hexagonal Grid Trajectory Physics',
      features: ['Accurate laser bounce physics', 'Next bubble switcher', '40 challenging layouts'],
    },
  },

  'memory-match': {
    gameId: 'memory-match',
    title: 'Picture Match',
    titleAmharic: 'ሜሞሪ ማች',
    genre: 'Brain & Memory',
    tagline: 'Flip cards, memorize positions, and match twin pairs!',
    description: 'Sharpen your cognitive memory and concentration. Flip cards two at a time to uncover matching cultural and safari icons before the clock expires.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-teal-500 via-cyan-600 to-blue-700',
      accentColor: '#14B8A6',
      badgeBg: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
      cardBg: 'bg-slate-900/90 border-teal-500/30',
      iconEmoji: '🃏',
      bannerBg: 'bg-gradient-to-b from-teal-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Find all matching pairs of cards on the board in the fewest turns and fastest time.',
      rules: [
        'Tap any card to flip it face up.',
        'Tap a second card to see if it matches the first.',
        'If the cards match, they stay revealed and you earn combo score.',
        'If they do not match, they flip back face down after a brief glance.',
        'Match all pairs on the board to complete the level.',
      ],
      controls: 'Tap cards to flip them.',
      proTips: [
        'Establish a mental grid pattern (scan top row left to right).',
        'Maintain a steady pace to keep your streak bonus multiplier active.',
      ],
    },
    achievements: [
      { id: 'mm_quick_pair', title: 'Sharp Eye', desc: 'Find 5 pairs in under 15 seconds', icon: '👀', maxProgress: 5 },
      { id: 'mm_perfect', title: 'Photographic Memory', desc: 'Complete a level without any wrong flip', icon: '🧠', maxProgress: 1 },
      { id: 'mm_safari_king', title: 'Memory Champ', desc: 'Clear Level 15', icon: '🦁', maxProgress: 15 },
    ],
    about: {
      version: '2.1.0',
      developer: 'TelePlay Game Studios',
      engine: 'Card Flip 3D Matrix',
      features: ['Ethiopian wildlife icons', 'Combo streak multipliers', '40 mental difficulty levels'],
    },
  },

  'helix-jump': {
    gameId: 'helix-jump',
    title: 'Helix Jump',
    titleAmharic: 'ሄሊክስ ጃምፕ',
    genre: '3D Arcade Physics',
    tagline: 'Rotate the helix tower to guide the bouncing ball through safe platforms!',
    description: 'High-octane 3D arcade drop. Spin the concentric helix tower left and right to allow the continuously bouncing ball to fall through gaps while dodging red hazard zones.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-amber-500 via-red-500 to-rose-700',
      accentColor: '#EF4444',
      badgeBg: 'bg-red-500/20 text-red-300 border-red-500/40',
      cardBg: 'bg-slate-900/90 border-red-500/30',
      iconEmoji: '🌀',
      bannerBg: 'bg-gradient-to-b from-red-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Rotate the helix cylinder so the bouncing ball drops down through open gaps without touching forbidden hazard sections.',
      rules: [
        'Swipe left or right to rotate the entire helix tower.',
        'The ball bounces automatically on normal platforms.',
        'Drop through gaps between platforms to descend.',
        'NEVER land on the bright hazard platforms—doing so will shatter the ball.',
        'Dropping through 3 or more platforms continuously charges a Fireball that smashes the next platform.',
      ],
      controls: 'Touch and drag horizontally across the screen to rotate the tower.',
      proTips: [
        'Build up a multi-floor speed drop to activate the invulnerable Fireball state.',
        'Look ahead below your current floor to align with the next gap.',
      ],
    },
    achievements: [
      { id: 'hj_drop_master', title: 'Tower Plunger', desc: 'Drop 5 floors in a single dive', icon: '⬇️', maxProgress: 5 },
      { id: 'hj_fireball', title: 'Fireball Breaker', desc: 'Smash a hazard platform with Fireball', icon: '🔥', maxProgress: 1 },
      { id: 'hj_tower_cleared', title: 'Helix Champion', desc: 'Complete 10 levels', icon: '🏆', maxProgress: 10 },
    ],
    about: {
      version: '3.2.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 60FPS Continuous Arcade Loop',
      features: ['Dynamic splash splatters', 'Procedural tower geometries', '40 skill stages'],
    },
  },

  'crazy-colors': {
    gameId: 'crazy-colors',
    title: 'Color Switch',
    titleAmharic: 'ክሬዚ ከለርስ',
    genre: 'Precision Reflex',
    tagline: 'Tap to bounce the ball upward through matching color obstacles!',
    description: 'Electrifying reflex challenge. Guide your colored sphere through rotating multi-colored geometric shapes. You can only pass through segments that match your ball.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-fuchsia-500 via-purple-600 to-indigo-700',
      accentColor: '#D946EF',
      badgeBg: 'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/40',
      cardBg: 'bg-slate-900/90 border-fuchsia-500/30',
      iconEmoji: '🎨',
      bannerBg: 'bg-gradient-to-b from-purple-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Tap rhythmically to keep the bouncing ball airborne and time your ascent through matching color segments.',
      rules: [
        'Tap anywhere on the screen to make the ball hop upward.',
        'The ball can only pass through barriers that match its current color.',
        'Touching any mismatched color segment causes the ball to burst.',
        'Collect Color Switcher orbs to morph into a new random color.',
        'Collect yellow stars to earn score points.',
      ],
      controls: 'Tap the screen to bounce upward.',
      proTips: [
        'Patience is key: bounce gently in place until the matching color segment rotates into position.',
        'Do not rush into a shape immediately after picking up a color switch.',
      ],
    },
    achievements: [
      { id: 'cc_star_collector', title: 'Star Hunter', desc: 'Collect 25 stars', icon: '⭐', maxProgress: 25 },
      { id: 'cc_prism', title: 'Prism Master', desc: 'Pass through 10 color rings', icon: '🌈', maxProgress: 10 },
      { id: 'cc_perfectionist', title: 'Color Guru', desc: 'Reach Level 15', icon: '🎖️', maxProgress: 15 },
    ],
    about: {
      version: '2.0.1',
      developer: 'TelePlay Game Studios',
      engine: 'Chromatic 2D Physics Engine',
      features: ['Neon glow visual effects', '40 hand-tuned level orbits', 'Precise touch controls'],
    },
  },

  'color-rush': {
    gameId: 'color-rush',
    title: 'Color Rush',
    titleAmharic: 'ከለር ረሽ',
    genre: 'Fast Reaction',
    tagline: 'Match the target color with lightning-fast tap reflexes!',
    description: 'High-speed cognitive reflex challenge across 10 progressive rounds. Match the central vibrant target color against a grid of choices with sub-16ms touch response.',
    hasLevels: true,
    totalLevels: 10,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-yellow-500 via-amber-500 to-orange-600',
      accentColor: '#F59E0B',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '⚡',
      bannerBg: 'bg-gradient-to-b from-amber-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Identify the large central target color and tap its exact match on the choice grid as fast as possible.',
      rules: [
        'Observe the central target color swatch and its chromatic label.',
        'Tap the matching color swatch from the bottom options grid.',
        'Correct selections advance to the next round immediately and reward time bonus points.',
        'Incorrect taps penalize your combo streak and time.',
        'Complete all 10 rounds to achieve the maximum 400 tournament points.',
      ],
      controls: 'Tap the matching color tile.',
      proTips: [
        'Do not read the color name text if it conflicts—focus on the actual visual hue!',
        'Speed is rewarded: faster taps yield up to 15 bonus points per round.',
      ],
    },
    achievements: [
      { id: 'cr_fast_tap', title: 'Lightning Tap', desc: 'Answer a round in under 0.5s', icon: '⚡', maxProgress: 1 },
      { id: 'cr_perfect_10', title: 'Flawless Rush', desc: 'Clear all 10 rounds with 100% accuracy', icon: '🎯', maxProgress: 1 },
      { id: 'cr_400_club', title: '400 PTS Elite', desc: 'Achieve the maximum 400 points', icon: '👑', maxProgress: 400 },
    ],
    about: {
      version: '1.9.0',
      developer: 'TelePlay Game Studios',
      engine: 'High-Speed Reflex Dispatcher',
      features: ['Sub-16ms latency', '10 progressive rounds', 'Normalized 400 PTS tournament model'],
    },
  },

  'knife-madness': {
    gameId: 'knife-madness',
    title: 'Knife Madness',
    titleAmharic: 'ናይፍ ማድነስ',
    genre: 'Arcade Target Throw',
    tagline: 'Throw knives into spinning wooden targets and slice juicy apples!',
    description: 'Test your timing and hand-eye precision in 3D. Throw knives into the rotating wooden log, avoid striking previously embedded blades, and slice target apples.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-rose-600 via-red-600 to-orange-700',
      accentColor: '#E11D48',
      badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
      cardBg: 'bg-slate-900/90 border-rose-500/30',
      iconEmoji: '🗡️',
      bannerBg: 'bg-gradient-to-b from-rose-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Launch all available knives into the rotating wooden target without colliding with existing knives.',
      rules: [
        'Tap anywhere on the screen to fling a knife forward.',
        'The knife lodges into the wooden target log.',
        'If your knife strikes another knife or spike, it deflects and the game ends.',
        'Slice apples stuck on the target to bank bonus points.',
        'Every 5th stage features a challenging Boss target with erratic rotation speeds.',
      ],
      controls: 'Tap the screen to throw a knife.',
      proTips: [
        'Observe the target rotation cadence—it frequently speeds up, slows down, or reverses!',
        'Space your knives evenly during the first few throws.',
      ],
    },
    achievements: [
      { id: 'km_apple_slicer', title: 'Apple Slicer', desc: 'Slice 10 target apples', icon: '🍎', maxProgress: 10 },
      { id: 'km_boss_slayer', title: 'Boss Slayer', desc: 'Defeat your first Boss log', icon: '🪵', maxProgress: 1 },
      { id: 'km_bullseye', title: 'Grand Thrower', desc: 'Lodge 12 knives in one stage', icon: '🎯', maxProgress: 12 },
    ],
    about: {
      version: '2.7.0',
      developer: 'TelePlay Game Studios',
      engine: 'Knife 3D Perspective Raycaster',
      features: ['Tactile knife rack', 'Boss stages every 5 levels', 'Physics wood deflections'],
    },
  },

  'archery-strike': {
    gameId: 'archery-strike',
    title: 'Pop Ballon',
    titleAmharic: 'ፖፕ ባሉን',
    genre: 'Rapid Reflex Arcade',
    tagline: 'Tap rising colorful balloons before they escape into the sky!',
    description: 'Ultra-responsive balloon popping arcade game. Tap colorful rising balloons instantly. Missing a target balloon or tapping empty space ends the run.',
    hasLevels: true,
    totalLevels: 30,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-red-500 via-pink-500 to-rose-600',
      accentColor: '#F43F5E',
      badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
      cardBg: 'bg-slate-900/90 border-rose-500/30',
      iconEmoji: '🎈',
      bannerBg: 'bg-gradient-to-b from-rose-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Pop rising balloons as quickly as possible. Don\'t miss any target balloons and don\'t tap empty white space!',
      rules: [
        'Tap directly on a balloon to pop it and score points.',
        'Target objectives show specific color quotas to prioritize.',
        'Tapping empty space counts as a miss and causes game over.',
        'Allowing a required balloon to float past the bottom or top causes failure.',
        'Maintain quick consecutive pops to build up your combo score multiplier.',
      ],
      controls: 'Tap directly on rising balloons.',
      proTips: [
        'Keep both thumbs positioned over the screen for quick dual-thumb popping.',
        'Focus your gaze on the center of the balloon to prevent clicking empty space.',
      ],
    },
    achievements: [
      { id: 'pb_pop_50', title: 'Balloon Buster', desc: 'Pop 50 balloons', icon: '🎈', maxProgress: 50 },
      { id: 'pb_combo_10', title: 'Popping Fever', desc: 'Reach a 10x pop streak', icon: '🔥', maxProgress: 10 },
      { id: 'pb_master_pop', title: 'Sky Cleaner', desc: 'Clear Level 15', icon: '🌤️', maxProgress: 15 },
    ],
    about: {
      version: '2.2.0',
      developer: 'TelePlay Game Studios',
      engine: 'Pure Canvas Fast-Touch Engine',
      features: ['Zero-lag touch input', '30 skill progression stages', 'Strict precision scoring'],
    },
  },

  'fruit-slice': {
    gameId: 'fruit-slice',
    title: 'Fruit Slice',
    titleAmharic: 'ፍሩት ስላይስ',
    genre: 'Blade Slicing Arcade',
    tagline: 'Draw your blade and slice flying juicy fruits while dodging bombs!',
    description: 'Master the sharp katana blade in this legendary fruit-slashing arcade challenge. Slice tossed watermelons, pineapples, and coconuts with sweeping gestures.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-orange-500 via-amber-600 to-red-600',
      accentColor: '#EA580C',
      badgeBg: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
      cardBg: 'bg-slate-900/90 border-orange-500/30',
      iconEmoji: '🍉',
      bannerBg: 'bg-gradient-to-b from-orange-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Swipe across the screen to slice flying fruits in half before they drop off-screen.',
      rules: [
        'Swipe your finger or mouse across flying fruits to cut them.',
        'Slicing multiple fruits in a single blade stroke creates a Combo Bonus.',
        'Do NOT slice black explosives or skull bombs—they explode immediately.',
        'Don\'t let 3 un-sliced fruits fall off screen, or you lose your lives.',
        'Look out for special glowing bananas that trigger Freeze, Frenzy, or Double Points.',
      ],
      controls: 'Swipe across the screen with your finger or mouse to draw your blade.',
      proTips: [
        'Wait for fruits to reach the apex of their trajectory before slicing for easier combos.',
        'Keep your blade swipes short and controlled so you don\'t accidentally hit a bomb.',
      ],
    },
    achievements: [
      { id: 'fs_first_combo', title: 'Fruit Ninja', desc: 'Execute a 3-fruit blade combo', icon: '⚔️', maxProgress: 1 },
      { id: 'fs_fruit_salad', title: 'Juice Master', desc: 'Slice 100 fruits', icon: '🍍', maxProgress: 100 },
      { id: 'fs_bomb_dodger', title: 'Bomb Defuser', desc: 'Complete a level without touching any bomb', icon: '💣', maxProgress: 1 },
    ],
    about: {
      version: '3.3.0',
      developer: 'TelePlay Game Studios',
      engine: 'Blade Trail Particle Engine',
      features: ['Authentic juicy splatters', '40 championship levels', 'Special fruit frenzy states'],
    },
  },

  'hill-rider': {
    gameId: 'hill-rider',
    title: 'Hill Climb',
    titleAmharic: 'ሂል ክላይምብ',
    genre: '2.5D Physics Racing',
    tagline: 'Balance throttle and brake to conquer rugged mountain terrain!',
    description: 'Realistic vehicle physics racer. Drive custom jeeps and monster trucks over steep undulating hills, collect fuel canisters, and perform airborne flips.',
    hasLevels: false,
    scoreType: 'score',
    scoreLabel: 'METERS',
    theme: {
      primaryGradient: 'from-lime-600 via-emerald-600 to-green-800',
      accentColor: '#84CC16',
      badgeBg: 'bg-lime-500/20 text-lime-300 border-lime-500/40',
      cardBg: 'bg-slate-900/90 border-lime-500/30',
      iconEmoji: '🚙',
      bannerBg: 'bg-gradient-to-b from-green-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Drive as far as possible across steep hills without running out of gas or flipping your vehicle.',
      rules: [
        'Hold Gas (right pedal) to accelerate forward.',
        'Hold Brake (left pedal) to decelerate or tilt backwards in mid-air.',
        'Balance your vehicle in mid-air to land parallel with the sloped ground.',
        'Collect red Gas Cans along the route to keep your fuel gauge full.',
        'If your driver strikes the ground or fuel empties, your run ends.',
      ],
      controls: 'Use the on-screen Gas and Brake pedals or Left/Right Arrow keys.',
      proTips: [
        'Feather the throttle over steep crests so you don\'t flip backwards.',
        'Airborne flips award extra coin bonuses, but ensure a smooth wheels-down landing.',
      ],
    },
    achievements: [
      { id: 'hr_100m', title: 'Off-Roader', desc: 'Reach 200 meters', icon: '🏁', maxProgress: 200 },
      { id: 'hr_backflip', title: 'Airborne Daredevil', desc: 'Land a full mid-air flip', icon: '🤸', maxProgress: 1 },
      { id: 'hr_1000m', title: 'Mountain Legend', desc: 'Conquer 1,000 meters in a single run', icon: '🏔️', maxProgress: 1000 },
    ],
    about: {
      version: '2.4.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 2.5D Rigid Body Simulation',
      features: ['Dynamic suspension springs', 'Continuous procedural hills', 'Fuel economy challenge'],
    },
  },

  'moto-race': {
    gameId: 'moto-race',
    title: 'Moto Race',
    titleAmharic: 'ሞተርሳይክል ውድድር',
    genre: '3D Traffic Motorcycle',
    tagline: 'Weave through dense highway traffic at extreme motorcycle speeds!',
    description: 'First-person 3D cockpit motorcycle racing. Grip handlebars, accelerate up to 240 km/h, and perform razor-thin near misses against trucks and cars.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-amber-600 via-red-600 to-neutral-900',
      accentColor: '#F97316',
      badgeBg: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
      cardBg: 'bg-slate-900/90 border-orange-500/30',
      iconEmoji: '🏍️',
      bannerBg: 'bg-gradient-to-b from-neutral-950 via-red-950/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Race down the highway cockpit, dodging cars and overtaking traffic closely for extreme speed bonuses.',
      rules: [
        'Press and hold Throttle to accelerate to maximum speed.',
        'Steer left and right between highway traffic lanes.',
        'Perform close overtakes (Near Misses) at speeds above 100 km/h for score multipliers.',
        'Crashing into any vehicle ends the race.',
        'Reach the stage checkpoint before time runs out.',
      ],
      controls: 'Tap on-screen Left/Right Steer buttons, or tilt/use A/D Arrow keys.',
      proTips: [
        'Ride along the lane dividers (white lines) to slip between two adjacent cars.',
        'Tap the brake briefly if traffic forms a complete wall ahead.',
      ],
    },
    achievements: [
      { id: 'mr_near_miss', title: 'Close Shave', desc: 'Perform 5 close near misses', icon: '💨', maxProgress: 5 },
      { id: 'mr_speed_demon', title: 'Speed Demon', desc: 'Surpass 200 km/h top speed', icon: '🏎️', maxProgress: 200 },
      { id: 'mr_highway_hero', title: 'Highway Ace', desc: 'Complete Level 10 without crashes', icon: '🏆', maxProgress: 10 },
    ],
    about: {
      version: '3.1.0',
      developer: 'TelePlay Game Studios',
      engine: 'High-Speed 3D Cockpit Raycaster',
      features: ['Dual analog gauges (Speedo & Tacho)', 'Doppler sound effects', '40 highway stages'],
    },
  },

  'soccer-ping-pong': {
    gameId: 'soccer-ping-pong',
    title: 'Soccer Ping Pong',
    titleAmharic: 'ሶከር ፒንግ ፖንግ',
    genre: '3D Soccer Arcade',
    tagline: 'Defend your soccer goal and curve power shots against rival keepers!',
    description: 'Electrifying 3D stadium hybrid soccer game. Control your goalkeeper paddle, deflect balls with spin curves, and beat rival national AI keepers across 20 tournament stadiums.',
    hasLevels: true,
    totalLevels: 20,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-emerald-600 via-green-600 to-teal-800',
      accentColor: '#10B981',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '⚽',
      bannerBg: 'bg-gradient-to-b from-emerald-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Protect your net and deflect the soccer ball past the opposing goalkeeper to score 3 goals before they do.',
      rules: [
        'Move your paddle left and right across your goal line.',
        'Hit the ball with the paddle edges to apply heavy curve and spin.',
        'First player to score the target number of goals wins the match.',
        'Winning unlocks the next stadium tier and national rival team.',
      ],
      controls: 'Slide finger or move mouse horizontally to position your goalie paddle.',
      proTips: [
        'Strike the ball while moving sideways to impart sharp deflection angles.',
        'Watch the opponent keeper\'s movement: wait for them to over-commit to one side.',
      ],
    },
    achievements: [
      { id: 'spp_first_goal', title: 'Clean Strike', desc: 'Score your first goal', icon: '⚽', maxProgress: 1 },
      { id: 'spp_hat_trick', title: 'Hat-Trick', desc: 'Score 3 goals in one match', icon: '🎩', maxProgress: 3 },
      { id: 'spp_stadium_champ', title: 'Stadium Champion', desc: 'Win in the Grand Addis Arena', icon: '🏟️', maxProgress: 1 },
    ],
    about: {
      version: '2.6.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 3D Stadium Field Simulation',
      features: ['20 national league stages', 'Realistic ball spin physics', 'Pyrotechnic goal celebrations'],
    },
  },

  'soccer-shooter': {
    gameId: 'soccer-shooter',
    title: 'Soccer Shooter',
    titleAmharic: 'ሶከር ሹተር',
    genre: 'Hex Ball Match-3',
    tagline: 'Kick soccer balls into goal clusters to clear the tournament grid!',
    description: 'Strategic tournament shooting game with soccer theme. Aim balls using trajectory guidelines into hexagonal clusters of country colors to pop goals.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-blue-600 via-cyan-600 to-indigo-800',
      accentColor: '#0284C7',
      badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
      cardBg: 'bg-slate-900/90 border-blue-500/30',
      iconEmoji: '🥅',
      bannerBg: 'bg-gradient-to-b from-blue-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Aim your soccer ball into matching clusters of 3 or more balls in the goal net to pop them.',
      rules: [
        'Aim with the dashed guideline.',
        'Release to shoot your soccer ball toward the goal ceiling.',
        'Connect 3 balls of the same national pattern to score a pop.',
        'Clear all balls before they descend below the danger penalty line.',
      ],
      controls: 'Touch and drag to aim, release to shoot.',
      proTips: [
        'Use the side goalposts to bank shots into tight gaps.',
        'Cut off high anchoring clusters to drop large chunks in one shot.',
      ],
    },
    achievements: [
      { id: 'ss_goal_getter', title: 'Goal Getter', desc: 'Pop 30 soccer ball clusters', icon: '⚽', maxProgress: 30 },
      { id: 'ss_clean_sheet', title: 'Clean Sheet', desc: 'Clear a level without foul warnings', icon: '🧤', maxProgress: 1 },
      { id: 'ss_cup_winner', title: 'World Cup Winner', desc: 'Conquer Level 20', icon: '🏆', maxProgress: 20 },
    ],
    about: {
      version: '2.0.0',
      developer: 'TelePlay Game Studios',
      engine: 'Hexagonal Soccer Physics Engine',
      features: ['National country jerseys', 'Bank-shot laser lines', '40 cup stages'],
    },
  },

  'dama': {
    gameId: 'dama',
    title: 'Dama',
    titleAmharic: 'ባህላዊ የዳማ ጨዋታ',
    genre: 'Traditional Board Game',
    tagline: 'Authentic Ethiopian Dama / Draughts strategy against smart AI!',
    description: 'Master the traditional Ethiopian checkers board game played across Ethiopian coffee houses. Outmaneuver the AI opponent with multi-hop captures and crown your kings.',
    hasLevels: true,
    totalLevels: 30,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-amber-700 via-yellow-800 to-stone-900',
      accentColor: '#B45309',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '👑',
      bannerBg: 'bg-gradient-to-b from-stone-950 via-amber-950/50 to-slate-950',
    },
    howToPlay: {
      summary: 'Move pieces diagonally across dark squares, jumping over opponent pieces to capture them.',
      rules: [
        'Regular pieces move diagonally forward one step.',
        'Captures are mandatory whenever an opposing piece is adjacent with an empty landing cell behind it.',
        'Chain multiple jumps in a single turn to capture multiple pieces.',
        'Reach the opponent\'s back row to promote your piece into a powerful flying King.',
        'A King can fly diagonally across multiple empty squares to strike.',
        'Win by capturing all opponent pieces or blocking all their legal moves.',
      ],
      controls: 'Tap your piece to highlight valid destination squares, then tap target square.',
      proTips: [
        'Control the center of the board to limit the AI\'s mobility.',
        'Protect your back row pieces as long as possible to delay opponent promotions.',
      ],
    },
    achievements: [
      { id: 'dama_first_capture', title: 'First Strike', desc: 'Capture an opponent piece', icon: '♟️', maxProgress: 1 },
      { id: 'dama_crowned', title: 'Crowned King', desc: 'Promote a piece into a King', icon: '👑', maxProgress: 1 },
      { id: 'dama_grandmaster', title: 'Addis Grandmaster', desc: 'Defeat Level 20 AI', icon: '🏆', maxProgress: 20 },
    ],
    about: {
      version: '2.2.0',
      developer: 'TelePlay Game Studios',
      engine: 'Minimax AI Strategy Engine',
      features: ['Authentic Ethiopian Dama rules', 'Handcrafted rustic wood board', '30 progressive AI ranks'],
    },
  },

  'pop-piano': {
    gameId: 'pop-piano',
    title: 'Piano',
    titleAmharic: 'ፖፕ ፒያኖ',
    genre: 'Rhythm Music Game',
    tagline: 'Tap falling black piano keys to play beloved melodies with rhythm precision!',
    description: 'Clean ivory 4-lane rhythm tiles game. Tap falling black rectangular keys in synchronization with musical tempo. Don\'t miss any tiles or tap the white canvas.',
    hasLevels: true,
    totalLevels: 30,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-purple-600 via-indigo-600 to-slate-900',
      accentColor: '#6366F1',
      badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
      cardBg: 'bg-slate-900/90 border-indigo-500/30',
      iconEmoji: '🎹',
      bannerBg: 'bg-gradient-to-b from-indigo-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Tap the descending black piano tiles as they cross the strike line at the bottom of the screen.',
      rules: [
        'Tap the black tiles to trigger authentic harmonic piano notes.',
        'Tapping near the bottom target line yields "PERFECT" score ratings.',
        'Tapping the ivory white background results in immediate failure.',
        'Letting any black tile drop past the bottom causes a miss.',
        'Complete the full song score to clear the level.',
      ],
      controls: 'Tap the 4 lanes directly on falling black tiles.',
      proTips: [
        'Rest your index and middle fingers on each side of the screen for two-hand play.',
        'Listen to the music melody rhythm to anticipate rapid note cascades.',
      ],
    },
    achievements: [
      { id: 'pp_perfect_run', title: 'Virtuoso', desc: 'Score 10 consecutive PERFECT taps', icon: '🎵', maxProgress: 10 },
      { id: 'pp_melody_champ', title: 'Maestro', desc: 'Clear 5 songs without miss', icon: '🎼', maxProgress: 5 },
      { id: 'pp_400_score', title: 'Grand Pianist', desc: 'Reach 400 tournament points', icon: '🎹', maxProgress: 400 },
    ],
    about: {
      version: '2.5.0',
      developer: 'TelePlay Game Studios',
      engine: 'Harmonic Polyphonic Audio Engine',
      features: ['Instant zero-latency tap', '400 PTS normalized scoring', '30 classical & modern tracks'],
    },
  },

  'halloween-fruit-slice': {
    gameId: 'halloween-fruit-slice',
    title: 'Halloween Fruit Slice',
    titleAmharic: 'ሃሎዊን ፍሩት ስላይስ',
    genre: 'Spooky Slicing Arcade',
    tagline: 'Slice spooky jack-o\'-lanterns and avoid cursed bubbling potions!',
    description: 'Spooky-themed katana slicing game. Slash flying jack-o\'-lantern pumpkins, ghost watermelons, and eerie fruit while dodging skull bombs under a haunted moonlight.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-orange-600 via-purple-700 to-slate-950',
      accentColor: '#F97316',
      badgeBg: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
      cardBg: 'bg-slate-900/90 border-purple-500/30',
      iconEmoji: '🎃',
      bannerBg: 'bg-gradient-to-b from-purple-950/80 via-orange-950/40 to-slate-950',
    },
    howToPlay: {
      summary: 'Slice spooky flying pumpkins and spooky fruit while avoiding cursed purple bombs.',
      rules: [
        'Swipe across flying spooky pumpkins and fruit to slice them.',
        'Multi-fruit slices generate magical combo points.',
        'Never hit bubbling cursed potion bombs.',
        'Keep your lives intact until level targets are completed.',
      ],
      controls: 'Swipe across screen to slice.',
      proTips: [
        'Cursed bombs have a distinct purple aura—avoid blade paths near them.',
        'Golden pumpkins reward double points and slow down time.',
      ],
    },
    achievements: [
      { id: 'hfs_pumpkin_carver', title: 'Pumpkin Carver', desc: 'Slice 25 jack-o\'-lanterns', icon: '🎃', maxProgress: 25 },
      { id: 'hfs_ghost_hunter', title: 'Ghost Hunter', desc: 'Execute a 4x spooky combo', icon: '👻', maxProgress: 4 },
      { id: 'hfs_halloween_king', title: 'Nightmare Master', desc: 'Survive Level 20', icon: '👑', maxProgress: 20 },
    ],
    about: {
      version: '2.1.0',
      developer: 'TelePlay Game Studios',
      engine: 'SpookyFX Canvas 2D Engine',
      features: ['Eerie pumpkin splatters', 'Special ghost slowdown fruits', '40 haunted levels'],
    },
  },

  'royal-water-sort': {
    gameId: 'royal-water-sort',
    title: 'Royal Water Sorting',
    titleAmharic: 'ሮያል ወተር ሶርት',
    genre: '3D Liquid Puzzle',
    tagline: 'Pour majestic colored liquids into royal glass vials to complete sorting!',
    description: 'Luxurious 3D liquid sorting game with crystalline flasks. Pour vibrant royal potions between vials until each container holds a single uniform color.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-blue-600 via-indigo-600 to-purple-800',
      accentColor: '#38BDF8',
      badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
      cardBg: 'bg-slate-900/90 border-blue-500/30',
      iconEmoji: '🧪',
      bannerBg: 'bg-gradient-to-b from-blue-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Transfer liquid layers between glass vials so each vial holds only one pure color.',
      rules: [
        'Tap a vial to pick it up.',
        'Tap another vial to pour the top liquid layer into it.',
        'You can only pour liquid into another vial if the top colors match and there is room.',
        'An empty vial can hold any liquid color.',
        'Use the Undo button to step back if you make a mistake.',
      ],
      controls: 'Tap a vial to select, then tap target vial to pour.',
      proTips: [
        'Always try to uncover trapped bottom colors as soon as possible.',
        'Keep at least one vial empty as a temporary buffer for sorting.',
      ],
    },
    achievements: [
      { id: 'rws_first_potion', title: 'Alchemist', desc: 'Sort your first royal vial', icon: '👑', maxProgress: 1 },
      { id: 'rws_perfect_pour', title: 'Royal Scholar', desc: 'Complete 5 levels without undo', icon: '✨', maxProgress: 5 },
      { id: 'rws_crown_master', title: 'Vial Monarch', desc: 'Clear Level 20', icon: '🏆', maxProgress: 20 },
    ],
    about: {
      version: '3.0.0',
      developer: 'TelePlay Game Studios',
      engine: '3D Liquid Shader Simulation',
      features: ['Realistic fluid pouring physics', 'Crystalline glass reflections', '40 championship puzzles'],
    },
  },

  'pop-balloon': {
    gameId: 'pop-balloon',
    title: 'Pop Balloon',
    titleAmharic: 'ፊኛ ፖፕ',
    genre: 'Balloon Popping Arcade',
    tagline: 'Pop flying balloons before they escape into the sky!',
    description: 'Fast-paced reaction arcade game. Tap floating balloons to pop them and trigger chain lightning combos while avoiding dangerous spiked bombs.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-pink-500 via-rose-500 to-amber-500',
      accentColor: '#EC4899',
      badgeBg: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
      cardBg: 'bg-slate-900/90 border-pink-500/30',
      iconEmoji: '🎈',
      bannerBg: 'bg-gradient-to-b from-pink-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Tap rising balloons to pop them. Clear the quota before missing 3 balloons.',
      rules: [
        'Balloons float upwards at varying speeds and wind currents.',
        'Tap or click balloons to pop them for points.',
        'Do NOT tap spiked black bombs—they cost a life!',
        'Special golden and rainbow balloons give 3x multiplier points.',
      ],
      controls: 'Tap or click on balloons on screen.',
      proTips: [
        'Swipe rapidly across tightly grouped balloons for combo multipliers.',
        'Prioritize faster moving smaller balloons first.',
      ],
    },
    achievements: [
      { id: 'pb_pop_10', title: 'Popper', desc: 'Pop 50 balloons', icon: '🎈', maxProgress: 50 },
      { id: 'pb_golden', title: 'Gold Rush', desc: 'Pop 5 golden balloons', icon: '⭐', maxProgress: 5 },
      { id: 'pb_century', title: 'Master Popper', desc: 'Pop 200 balloons', icon: '🏆', maxProgress: 200 },
    ],
    about: {
      version: '2.1.0',
      developer: 'TelePlay Game Studios',
      engine: '2D Floating Particle Physics',
      features: ['Colorful balloon shaders', 'Wind dynamics', 'Chain combo pop audio'],
    },
  },

  'button-soccer': {
    gameId: 'button-soccer',
    title: 'Button Soccer',
    titleAmharic: 'ባተን ሶከር 2026',
    genre: 'Turn-Based Tabletop Soccer',
    tagline: 'Aim your button player tokens and strike goals against national champions!',
    description: 'Authentic 2026 tabletop button soccer championship. Select your national team (Ethiopia, Brazil, Argentina, Germany), aim disc trajectories with power arrows, and score goals.',
    hasLevels: true,
    totalLevels: 20,
    scoreType: 'score',
    scoreLabel: 'WINS',
    theme: {
      primaryGradient: 'from-emerald-700 via-teal-800 to-green-950',
      accentColor: '#10B981',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '🔘',
      bannerBg: 'bg-gradient-to-b from-green-950 via-emerald-950/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Turn-based table soccer: pull back on your team button tokens to aim trajectory and power, and strike the ball into the opponent net.',
      rules: [
        'Players take turns aiming and striking one button token.',
        'Drag backward from your button player to adjust angle and kicking power.',
        'Release to launch your button toward the ball or into opponent territory.',
        'Score target number of goals (e.g. 3 goals) to win the match.',
        'Use wall rebounds to curve around defenders.',
      ],
      controls: 'Touch and pull back on your button token to aim, release to shoot.',
      proTips: [
        'Bank your shots off side cushions to bypass defensive walls.',
        'Position one button as a sweeper right in front of your net.',
      ],
    },
    achievements: [
      { id: 'bs_first_strike', title: 'Table Striker', desc: 'Score your first button goal', icon: '⚽', maxProgress: 1 },
      { id: 'bs_derby_win', title: 'Derby Champion', desc: 'Win match with Ethiopian national team', icon: '🇪🇹', maxProgress: 1 },
      { id: 'bs_trophy_cup', title: 'Cup Winner', desc: 'Win the 2026 Table Championship', icon: '🏆', maxProgress: 1 },
    ],
    about: {
      version: '2.5.0',
      developer: 'TelePlay Game Studios',
      engine: 'Rigid Body Disc Physics 2D/3D',
      features: ['Official national flag discs', 'Realistic table rebounds', 'Championship tournament mode'],
    },
  },

  'emoji-iq': {
    gameId: 'emoji-iq',
    title: 'EMOJI IQ',
    titleAmharic: 'ኢሞጂ አይኪው',
    genre: 'Tournament Emoji & Number Calculation Challenge',
    tagline: 'Master 40 stages of emoji equations, logical calculations & tournament scoring!',
    description: 'Solve 12 unique emoji equation puzzle categories across 40 progressive stages with multi-step calculations, order of operations, changed quantities, visual differences, combos, hints, lives, store, and competitive leaderboard.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-violet-600 via-indigo-600 to-cyan-700',
      accentColor: '#6C5CE7',
      badgeBg: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
      cardBg: 'bg-slate-900/90 border-violet-500/30',
      iconEmoji: '🧠',
      bannerBg: 'bg-gradient-to-b from-[#241F3D] via-violet-950/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Deduce emoji values from clue equations, apply PEMDAS operations, and select the correct numerical answer.',
      rules: [
        'Deduce the numerical values of emojis from the clue equations.',
        'Mind the order of operations: multiplication and division are done before addition and subtraction.',
        'Watch for emoji quantity changes (e.g. triple bananas vs single banana).',
        'Speed and consecutive correct answers increase your combo multiplier.',
        'Use hints to eliminate wrong options if you need help.',
      ],
      controls: 'Tap the correct numerical answer tile.',
      proTips: [
        'Always check the operation signs in the target equation carefully (watch for × vs +).',
        'Solve row by row from top to bottom.',
      ],
    },
    achievements: [
      { id: 'eiq_first_solve', title: 'First Equation', desc: 'Solve your first Emoji IQ puzzle', icon: '🧠', maxProgress: 1 },
      { id: 'eiq_perfect_combo', title: 'Calculation Master', desc: 'Achieve a 5x combo streak', icon: '⚡', maxProgress: 5 },
      { id: 'eiq_tournament_champ', title: 'IQ Grandmaster', desc: 'Complete all 40 tournament stages', icon: '👑', maxProgress: 40 },
    ],
    about: {
      version: '1.0.0',
      developer: 'GameON Studios',
      engine: 'Deterministic Emoji Arithmetic & Logic Engine',
      features: ['40 Progressive Stages', '12 Unique Mathematical Categories', 'Tournament Skill Scoring & Combos', 'Persistent Global Standings'],
    },
  },
};

export const getGameConfig = (gameId: string): GameConfig => {
  return (
    GAME_CONFIGS[gameId] || {
      gameId,
      title: gameId.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
      titleAmharic: 'ጨዋታ',
      genre: 'Arcade Game',
      tagline: 'Play and compete for tournament glory!',
      description: 'Engaging tournament game with full leaderboard tracking and skill challenges.',
      hasLevels: true,
      totalLevels: 40,
      scoreType: 'score',
      scoreLabel: 'PTS',
      theme: {
        primaryGradient: 'from-blue-600 via-indigo-600 to-purple-700',
        accentColor: '#3B82F6',
        badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
        cardBg: 'bg-slate-900/90 border-blue-500/30',
        iconEmoji: '🎮',
      },
      howToPlay: {
        summary: 'Follow the on-screen objective to clear levels and achieve high scores.',
        rules: ['Tap or swipe to control gameplay.', 'Reach the target score to clear each stage.'],
        controls: 'Touch screen or use keyboard controls.',
        proTips: ['Practice regularly to master the mechanics.'],
      },
      achievements: [
        { id: 'default_play', title: 'First Game', desc: 'Play your first match', icon: '🎮', maxProgress: 1 },
      ],
      about: {
        version: '1.0.0',
        developer: 'TelePlay Game Studios',
        engine: 'Web Canvas Engine',
        features: ['Leaderboard integration', 'Offline progress tracking'],
      },
    }
  );
};
