import { LevelConfig } from './types';

/**
 * Halloween Fruit Slice - Exactly 40 Levels Progression
 * Level 1 is calibrated to be VERY DIFFICULT per user specifications.
 * Sequential progression: Level 1 is unlocked, levels 2-40 unlock one by one.
 */
export const HALLOWEEN_LEVELS: LevelConfig[] = [
  // TIER 1: Very Difficult (Levels 1 - 5)
  {
    levelNum: 1,
    title: 'Witching Hour Awakening',
    tier: 'Very Difficult',
    objectiveType: 'SCORE',
    objectiveTarget: 400,
    objectiveDescription: 'Score 400 Points — High Speed & Fast Reactions',
    maxMisses: 3,
    spawnIntervalMs: 1100,
    maxSimultaneous: 3,
    minSpeedY: 620,
    maxSpeedY: 820,
    bombChance: 0.22,
    star1: 400,
    star2: 600,
    star3: 850,
  },
  {
    levelNum: 2,
    title: 'Pumpkin Patch Ambush',
    tier: 'Very Difficult',
    objectiveType: 'SLICES',
    objectiveTarget: 35,
    objectiveDescription: 'Slice 35 Spooky Fruits without hitting Bombs',
    maxMisses: 3,
    spawnIntervalMs: 1050,
    maxSimultaneous: 3,
    minSpeedY: 630,
    maxSpeedY: 830,
    bombChance: 0.24,
    star1: 350,
    star2: 550,
    star3: 800,
  },
  {
    levelNum: 3,
    title: 'Crypt Blade Trial',
    tier: 'Very Difficult',
    objectiveType: 'COMBO',
    objectiveTarget: 4,
    objectiveDescription: 'Land a 4x Monster Combo & reach 500 points',
    maxMisses: 3,
    spawnIntervalMs: 1000,
    maxSimultaneous: 4,
    minSpeedY: 640,
    maxSpeedY: 840,
    bombChance: 0.25,
    star1: 500,
    star2: 750,
    star3: 1000,
  },
  {
    levelNum: 4,
    title: 'Phantom Frenzy',
    tier: 'Very Difficult',
    objectiveType: 'SURVIVE',
    objectiveTarget: 40,
    objectiveDescription: 'Survive 40 Seconds in the Haunted Storm',
    timeLimitSec: 40,
    maxMisses: 3,
    spawnIntervalMs: 950,
    maxSimultaneous: 4,
    minSpeedY: 650,
    maxSpeedY: 850,
    bombChance: 0.26,
    star1: 450,
    star2: 700,
    star3: 950,
  },
  {
    levelNum: 5,
    title: 'Graveyard Gauntlet',
    tier: 'Very Difficult',
    objectiveType: 'SCORE',
    objectiveTarget: 700,
    objectiveDescription: 'Score 700 Points in High-Density Swarms',
    maxMisses: 3,
    spawnIntervalMs: 920,
    maxSimultaneous: 4,
    minSpeedY: 660,
    maxSpeedY: 860,
    bombChance: 0.27,
    star1: 700,
    star2: 950,
    star3: 1250,
  },

  // TIER 2: Very Difficult + (Levels 6 - 10)
  {
    levelNum: 6,
    title: 'Banshee Blade Dance',
    tier: 'Very Difficult +',
    objectiveType: 'SLICES',
    objectiveTarget: 45,
    objectiveDescription: 'Slice 45 Monster Fruits amidst rising fog',
    maxMisses: 3,
    spawnIntervalMs: 900,
    maxSimultaneous: 4,
    minSpeedY: 670,
    maxSpeedY: 870,
    bombChance: 0.28,
    star1: 550,
    star2: 800,
    star3: 1100,
  },
  {
    levelNum: 7,
    title: 'Blood Moon Surge',
    tier: 'Very Difficult +',
    objectiveType: 'COMBO',
    objectiveTarget: 5,
    objectiveDescription: 'Execute a 5x Combo in a Single Slice',
    maxMisses: 3,
    spawnIntervalMs: 880,
    maxSimultaneous: 4,
    minSpeedY: 680,
    maxSpeedY: 880,
    bombChance: 0.29,
    star1: 650,
    star2: 950,
    star3: 1300,
  },
  {
    levelNum: 8,
    title: 'Cauldron Splash',
    tier: 'Very Difficult +',
    objectiveType: 'SCORE',
    objectiveTarget: 850,
    objectiveDescription: 'Score 850 Points with Rapid Blade Swipes',
    maxMisses: 3,
    spawnIntervalMs: 860,
    maxSimultaneous: 4,
    minSpeedY: 690,
    maxSpeedY: 890,
    bombChance: 0.30,
    star1: 850,
    star2: 1150,
    star3: 1500,
  },
  {
    levelNum: 9,
    title: 'Shadow Maze Slice',
    tier: 'Very Difficult +',
    objectiveType: 'SURVIVE',
    objectiveTarget: 45,
    objectiveDescription: 'Survive 45 Seconds of Chaotic Trajectories',
    timeLimitSec: 45,
    maxMisses: 3,
    spawnIntervalMs: 850,
    maxSimultaneous: 4,
    minSpeedY: 700,
    maxSpeedY: 900,
    bombChance: 0.30,
    star1: 600,
    star2: 900,
    star3: 1250,
  },
  {
    levelNum: 10,
    title: 'Gargoyle Gatekeeper',
    tier: 'Very Difficult +',
    objectiveType: 'SLICES',
    objectiveTarget: 55,
    objectiveDescription: 'Slice 55 Halloween Fruits with High Accuracy',
    maxMisses: 3,
    spawnIntervalMs: 830,
    maxSimultaneous: 5,
    minSpeedY: 710,
    maxSpeedY: 910,
    bombChance: 0.31,
    star1: 750,
    star2: 1100,
    star3: 1500,
  },

  // TIER 3: Expert (Levels 11 - 15)
  {
    levelNum: 11,
    title: 'Specter Gale',
    tier: 'Expert',
    objectiveType: 'SCORE',
    objectiveTarget: 1000,
    objectiveDescription: 'Reach 1,000 Points with Triple Wave Invasions',
    maxMisses: 3,
    spawnIntervalMs: 820,
    maxSimultaneous: 5,
    minSpeedY: 720,
    maxSpeedY: 920,
    bombChance: 0.32,
    star1: 1000,
    star2: 1350,
    star3: 1750,
  },
  {
    levelNum: 12,
    title: 'Cursed Orchard Harvest',
    tier: 'Expert',
    objectiveType: 'COMBO',
    objectiveTarget: 5,
    objectiveDescription: 'Perform Two 5x Combos & Score 800 Points',
    maxMisses: 3,
    spawnIntervalMs: 800,
    maxSimultaneous: 5,
    minSpeedY: 730,
    maxSpeedY: 930,
    bombChance: 0.32,
    star1: 800,
    star2: 1100,
    star3: 1500,
  },
  {
    levelNum: 13,
    title: 'Tomb Raider Slash',
    tier: 'Expert',
    objectiveType: 'SLICES',
    objectiveTarget: 60,
    objectiveDescription: 'Slice 60 Flying Monsters with Fast Reflexes',
    maxMisses: 3,
    spawnIntervalMs: 780,
    maxSimultaneous: 5,
    minSpeedY: 740,
    maxSpeedY: 940,
    bombChance: 0.33,
    star1: 850,
    star2: 1200,
    star3: 1650,
  },
  {
    levelNum: 14,
    title: 'Jack-o-Lantern Storm',
    tier: 'Expert',
    objectiveType: 'SURVIVE',
    objectiveTarget: 50,
    objectiveDescription: 'Survive 50 Seconds under Relentless Spawns',
    timeLimitSec: 50,
    maxMisses: 3,
    spawnIntervalMs: 760,
    maxSimultaneous: 5,
    minSpeedY: 750,
    maxSpeedY: 950,
    bombChance: 0.33,
    star1: 750,
    star2: 1100,
    star3: 1550,
  },
  {
    levelNum: 15,
    title: 'Demon Citadel Blitz',
    tier: 'Expert',
    objectiveType: 'SCORE',
    objectiveTarget: 1250,
    objectiveDescription: 'Score 1,250 Points with Expert Swordplay',
    maxMisses: 3,
    spawnIntervalMs: 750,
    maxSimultaneous: 5,
    minSpeedY: 760,
    maxSpeedY: 960,
    bombChance: 0.34,
    star1: 1250,
    star2: 1650,
    star3: 2100,
  },

  // TIER 4: Expert + (Levels 16 - 20)
  {
    levelNum: 16,
    title: 'Midnight Voodoo Strike',
    tier: 'Expert +',
    objectiveType: 'SLICES',
    objectiveTarget: 70,
    objectiveDescription: 'Slice 70 Cursed Fruits through Darkened Air',
    maxMisses: 3,
    spawnIntervalMs: 730,
    maxSimultaneous: 5,
    minSpeedY: 770,
    maxSpeedY: 970,
    bombChance: 0.34,
    star1: 950,
    star2: 1350,
    star3: 1800,
  },
  {
    levelNum: 17,
    title: 'Poltergeist Vortex',
    tier: 'Expert +',
    objectiveType: 'COMBO',
    objectiveTarget: 6,
    objectiveDescription: 'Achieve a 6x Ultra Combo in one swift drag',
    maxMisses: 3,
    spawnIntervalMs: 720,
    maxSimultaneous: 5,
    minSpeedY: 780,
    maxSpeedY: 980,
    bombChance: 0.35,
    star1: 900,
    star2: 1300,
    star3: 1750,
  },
  {
    levelNum: 18,
    title: 'Haunted Dungeon Run',
    tier: 'Expert +',
    objectiveType: 'SCORE',
    objectiveTarget: 1400,
    objectiveDescription: 'Accumulate 1,400 Points in Narrow Windows',
    maxMisses: 3,
    spawnIntervalMs: 700,
    maxSimultaneous: 6,
    minSpeedY: 790,
    maxSpeedY: 990,
    bombChance: 0.35,
    star1: 1400,
    star2: 1800,
    star3: 2300,
  },
  {
    levelNum: 19,
    title: 'Spooky Twilight Frenzy',
    tier: 'Expert +',
    objectiveType: 'SURVIVE',
    objectiveTarget: 55,
    objectiveDescription: 'Survive 55 Seconds of Intense Firepower',
    timeLimitSec: 55,
    maxMisses: 3,
    spawnIntervalMs: 690,
    maxSimultaneous: 6,
    minSpeedY: 800,
    maxSpeedY: 1000,
    bombChance: 0.36,
    star1: 900,
    star2: 1300,
    star3: 1800,
  },
  {
    levelNum: 20,
    title: 'Catacomb Monarch',
    tier: 'Expert +',
    objectiveType: 'SLICES',
    objectiveTarget: 80,
    objectiveDescription: 'Defeat 80 Monster Fruits before Midnight',
    maxMisses: 3,
    spawnIntervalMs: 680,
    maxSimultaneous: 6,
    minSpeedY: 810,
    maxSpeedY: 1010,
    bombChance: 0.36,
    star1: 1100,
    star2: 1550,
    star3: 2100,
  },

  // TIER 5: Extreme (Levels 21 - 25)
  {
    levelNum: 21,
    title: 'Infernal Nether Slash',
    tier: 'Extreme',
    objectiveType: 'SCORE',
    objectiveTarget: 1600,
    objectiveDescription: 'Score 1,600 Points in Blistering Trajectories',
    maxMisses: 3,
    spawnIntervalMs: 670,
    maxSimultaneous: 6,
    minSpeedY: 820,
    maxSpeedY: 1020,
    bombChance: 0.37,
    star1: 1600,
    star2: 2100,
    star3: 2700,
  },
  {
    levelNum: 22,
    title: 'Grim Reaper Onslaught',
    tier: 'Extreme',
    objectiveType: 'SLICES',
    objectiveTarget: 90,
    objectiveDescription: 'Slice 90 Targets through high-velocity bursts',
    maxMisses: 3,
    spawnIntervalMs: 660,
    maxSimultaneous: 6,
    minSpeedY: 830,
    maxSpeedY: 1030,
    bombChance: 0.37,
    star1: 1200,
    star2: 1700,
    star3: 2300,
  },
  {
    levelNum: 23,
    title: 'Necromancer Spell Storm',
    tier: 'Extreme',
    objectiveType: 'COMBO',
    objectiveTarget: 6,
    objectiveDescription: 'Connect Multiple 6x Combos & Hit 1,200 Points',
    maxMisses: 3,
    spawnIntervalMs: 650,
    maxSimultaneous: 6,
    minSpeedY: 840,
    maxSpeedY: 1040,
    bombChance: 0.38,
    star1: 1200,
    star2: 1700,
    star3: 2300,
  },
  {
    levelNum: 24,
    title: 'Abyssal Chasm Dash',
    tier: 'Extreme',
    objectiveType: 'SURVIVE',
    objectiveTarget: 60,
    objectiveDescription: 'Survive 60 Seconds of Extreme Air Chaos',
    timeLimitSec: 60,
    maxMisses: 3,
    spawnIntervalMs: 640,
    maxSimultaneous: 6,
    minSpeedY: 850,
    maxSpeedY: 1050,
    bombChance: 0.38,
    star1: 1100,
    star2: 1600,
    star3: 2200,
  },
  {
    levelNum: 25,
    title: 'Dracula Shadow Chamber',
    tier: 'Extreme',
    objectiveType: 'SCORE',
    objectiveTarget: 1800,
    objectiveDescription: 'Reach 1,800 Points in High-Density Waves',
    maxMisses: 3,
    spawnIntervalMs: 630,
    maxSimultaneous: 6,
    minSpeedY: 860,
    maxSpeedY: 1060,
    bombChance: 0.39,
    star1: 1800,
    star2: 2400,
    star3: 3100,
  },

  // TIER 6: Extreme + (Levels 26 - 30)
  {
    levelNum: 26,
    title: 'Spectral Cyclone Rush',
    tier: 'Extreme +',
    objectiveType: 'SLICES',
    objectiveTarget: 100,
    objectiveDescription: 'Slice 100 Airborne Monsters with Zero Lag',
    maxMisses: 3,
    spawnIntervalMs: 620,
    maxSimultaneous: 6,
    minSpeedY: 870,
    maxSpeedY: 1070,
    bombChance: 0.39,
    star1: 1350,
    star2: 1900,
    star3: 2550,
  },
  {
    levelNum: 27,
    title: 'Eerie Echo Shards',
    tier: 'Extreme +',
    objectiveType: 'COMBO',
    objectiveTarget: 7,
    objectiveDescription: 'Pull Off a Rare 7x Mega Combo',
    maxMisses: 3,
    spawnIntervalMs: 610,
    maxSimultaneous: 7,
    minSpeedY: 880,
    maxSpeedY: 1080,
    bombChance: 0.40,
    star1: 1300,
    star2: 1850,
    star3: 2500,
  },
  {
    levelNum: 28,
    title: 'Hallows Eve Inferno',
    tier: 'Extreme +',
    objectiveType: 'SCORE',
    objectiveTarget: 2100,
    objectiveDescription: 'Score 2,100 Points against Rapid Flight Paths',
    maxMisses: 3,
    spawnIntervalMs: 600,
    maxSimultaneous: 7,
    minSpeedY: 890,
    maxSpeedY: 1090,
    bombChance: 0.40,
    star1: 2100,
    star2: 2800,
    star3: 3600,
  },
  {
    levelNum: 29,
    title: 'Ghostly Maelstrom',
    tier: 'Extreme +',
    objectiveType: 'SURVIVE',
    objectiveTarget: 60,
    objectiveDescription: 'Survive 60 Seconds with Bomb Swarms',
    timeLimitSec: 60,
    maxMisses: 3,
    spawnIntervalMs: 590,
    maxSimultaneous: 7,
    minSpeedY: 900,
    maxSpeedY: 1100,
    bombChance: 0.41,
    star1: 1250,
    star2: 1800,
    star3: 2450,
  },
  {
    levelNum: 30,
    title: 'Titan of the Crypt',
    tier: 'Extreme +',
    objectiveType: 'SLICES',
    objectiveTarget: 115,
    objectiveDescription: 'Slice 115 Monster Fruits under High Pressure',
    maxMisses: 3,
    spawnIntervalMs: 580,
    maxSimultaneous: 7,
    minSpeedY: 910,
    maxSpeedY: 1110,
    bombChance: 0.41,
    star1: 1550,
    star2: 2200,
    star3: 3000,
  },

  // TIER 7: Master (Levels 31 - 35)
  {
    levelNum: 31,
    title: 'Blade Master Crucible',
    tier: 'Master',
    objectiveType: 'SCORE',
    objectiveTarget: 2400,
    objectiveDescription: 'Attain 2,400 Points with Precision Swiping',
    maxMisses: 3,
    spawnIntervalMs: 570,
    maxSimultaneous: 7,
    minSpeedY: 920,
    maxSpeedY: 1120,
    bombChance: 0.42,
    star1: 2400,
    star2: 3200,
    star3: 4100,
  },
  {
    levelNum: 32,
    title: 'Phantom Overlord Descent',
    tier: 'Master',
    objectiveType: 'COMBO',
    objectiveTarget: 7,
    objectiveDescription: 'Score 1,600 Points with Multiple 7x Combos',
    maxMisses: 3,
    spawnIntervalMs: 560,
    maxSimultaneous: 7,
    minSpeedY: 930,
    maxSpeedY: 1130,
    bombChance: 0.42,
    star1: 1600,
    star2: 2300,
    star3: 3100,
  },
  {
    levelNum: 33,
    title: 'Dark Moon Ascendance',
    tier: 'Master',
    objectiveType: 'SLICES',
    objectiveTarget: 130,
    objectiveDescription: 'Slice 130 Rapid Targets with Master Pacing',
    maxMisses: 3,
    spawnIntervalMs: 550,
    maxSimultaneous: 7,
    minSpeedY: 940,
    maxSpeedY: 1140,
    bombChance: 0.43,
    star1: 1750,
    star2: 2500,
    star3: 3400,
  },
  {
    levelNum: 34,
    title: 'Cursed Void Gauntlet',
    tier: 'Master',
    objectiveType: 'SURVIVE',
    objectiveTarget: 65,
    objectiveDescription: 'Survive 65 Seconds against Ruthless Swarms',
    timeLimitSec: 65,
    maxMisses: 3,
    spawnIntervalMs: 540,
    maxSimultaneous: 7,
    minSpeedY: 950,
    maxSpeedY: 1150,
    bombChance: 0.43,
    star1: 1450,
    star2: 2100,
    star3: 2900,
  },
  {
    levelNum: 35,
    title: 'Spooky Sovereign Clash',
    tier: 'Master',
    objectiveType: 'SCORE',
    objectiveTarget: 2700,
    objectiveDescription: 'Score 2,700 Points in Lightning Invasions',
    maxMisses: 3,
    spawnIntervalMs: 530,
    maxSimultaneous: 7,
    minSpeedY: 960,
    maxSpeedY: 1160,
    bombChance: 0.44,
    star1: 2700,
    star2: 3600,
    star3: 4700,
  },

  // TIER 8: Master + (Levels 36 - 39)
  {
    levelNum: 36,
    title: 'Wraith Blade Tempest',
    tier: 'Master +',
    objectiveType: 'SLICES',
    objectiveTarget: 145,
    objectiveDescription: 'Slice 145 Monster Fruits in Razor-Thin Windows',
    maxMisses: 3,
    spawnIntervalMs: 520,
    maxSimultaneous: 8,
    minSpeedY: 970,
    maxSpeedY: 1170,
    bombChance: 0.44,
    star1: 1950,
    star2: 2800,
    star3: 3800,
  },
  {
    levelNum: 37,
    title: 'Witch Queen Supernova',
    tier: 'Master +',
    objectiveType: 'COMBO',
    objectiveTarget: 8,
    objectiveDescription: 'Execute an 8x Legendary Combo',
    maxMisses: 3,
    spawnIntervalMs: 510,
    maxSimultaneous: 8,
    minSpeedY: 980,
    maxSpeedY: 1180,
    bombChance: 0.45,
    star1: 1800,
    star2: 2600,
    star3: 3600,
  },
  {
    levelNum: 38,
    title: 'Doomsday Nether Barrage',
    tier: 'Master +',
    objectiveType: 'SCORE',
    objectiveTarget: 3100,
    objectiveDescription: 'Reach 3,100 Points against Deadly Bomb Formations',
    maxMisses: 3,
    spawnIntervalMs: 500,
    maxSimultaneous: 8,
    minSpeedY: 990,
    maxSpeedY: 1190,
    bombChance: 0.45,
    star1: 3100,
    star2: 4100,
    star3: 5300,
  },
  {
    levelNum: 39,
    title: 'Eclipse of the Undead',
    tier: 'Master +',
    objectiveType: 'SURVIVE',
    objectiveTarget: 70,
    objectiveDescription: 'Survive 70 Seconds in the Master Storm',
    timeLimitSec: 70,
    maxMisses: 3,
    spawnIntervalMs: 490,
    maxSimultaneous: 8,
    minSpeedY: 1000,
    maxSpeedY: 1200,
    bombChance: 0.46,
    star1: 1650,
    star2: 2400,
    star3: 3300,
  },

  // FINAL CHALLENGE (Level 40)
  {
    levelNum: 40,
    title: 'FINAL HALLOWEEN CHALLENGE',
    tier: 'Final Challenge',
    objectiveType: 'SCORE',
    objectiveTarget: 3500,
    objectiveDescription: 'Defeat the Final 3,500 Point Halloween Gauntlet',
    maxMisses: 3,
    spawnIntervalMs: 480,
    maxSimultaneous: 8,
    minSpeedY: 1020,
    maxSpeedY: 1220,
    bombChance: 0.47,
    star1: 3500,
    star2: 4800,
    star3: 6500,
  },
];
