/**
 * Bubble Shooter - 40 Deterministic Solvable Levels
 * Tournament-grade progressive difficulty from Hard (Level 1) to Final Championship (Level 40)
 */

import { BubbleColor, BubbleShooterLevel } from './types';

// Helper alias for compact level matrix definitions
const R: BubbleColor = 'RED';
const B: BubbleColor = 'BLUE';
const G: BubbleColor = 'GREEN';
const Y: BubbleColor = 'YELLOW';
const P: BubbleColor = 'PURPLE';
const W: BubbleColor = 'WHITE';
const _: null = null;

export const BUBBLE_SHOOTER_LEVELS: BubbleShooterLevel[] = [
  // -------------------------------------------------------------
  // TIER 1: HARD (Levels 1 - 5)
  // Dense 5-6 color ceilings, strategic anchor blocks, bank shots
  // -------------------------------------------------------------
  {
    levelNumber: 1,
    name: 'Tournament Inception',
    difficultyTier: 'Hard',
    maxFouls: 5,
    targetScore: 2400,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, B, B, G, G, Y, Y],
      [P, P, W, W, R, R, B],
      [G, G, Y, Y, P, P, W, W],
      [B, R, G, Y, P, W, B],
      [Y, Y, G, G, B, B, R, R],
    ],
  },
  {
    levelNumber: 2,
    name: 'Prism Cascade',
    difficultyTier: 'Hard',
    maxFouls: 5,
    targetScore: 2600,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, Y, Y, R, R, G, G],
      [W, W, P, P, W, W, B],
      [G, R, B, Y, W, P, R, G],
      [Y, Y, B, B, G, G, R],
      [P, P, R, R, Y, Y, P, P],
      [_, W, W, B, B, W, _],
    ],
  },
  {
    levelNumber: 3,
    name: 'Emerald Ridge',
    difficultyTier: 'Hard',
    maxFouls: 5,
    targetScore: 2800,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [G, G, G, R, R, B, B, B],
      [Y, Y, P, P, W, W, G],
      [B, B, R, G, Y, P, R, R],
      [W, W, G, G, Y, Y, B],
      [P, P, Y, Y, R, R, P, P],
      [_, B, B, W, W, G, _],
    ],
  },
  {
    levelNumber: 4,
    name: 'Sapphire Gate',
    difficultyTier: 'Hard',
    maxFouls: 5,
    targetScore: 3000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, W, W, P, P, B, B],
      [R, R, G, G, Y, Y, R],
      [P, Y, B, W, R, G, P, Y],
      [W, W, B, B, G, G, W],
      [G, G, R, R, P, P, Y, Y],
      [_, Y, Y, R, R, P, _],
    ],
  },
  {
    levelNumber: 5,
    name: 'Ruby Vanguard',
    difficultyTier: 'Hard',
    maxFouls: 5,
    targetScore: 3200,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, R, Y, Y, P, P, P],
      [B, B, G, G, W, W, R],
      [W, P, Y, G, B, R, W, P],
      [G, G, R, R, B, B, Y],
      [Y, Y, W, W, G, G, R, R],
      [_, P, P, Y, Y, B, _],
      [_, _, R, R, W, _, _, _],
    ],
  },

  // -------------------------------------------------------------
  // TIER 2: HARD+ (Levels 6 - 10)
  // Deeper ceilings, color blocking, tricky bounce pockets
  // -------------------------------------------------------------
  {
    levelNumber: 6,
    name: 'Diamond Lattice',
    difficultyTier: 'Hard+',
    maxFouls: 5,
    targetScore: 3500,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [W, W, B, B, Y, Y, W, W],
      [G, G, P, P, R, R, G],
      [R, B, G, W, P, Y, R, B],
      [P, P, Y, Y, B, B, P],
      [B, B, W, W, G, G, Y, Y],
      [_, R, R, P, P, W, _],
      [_, _, B, B, G, _, _, _],
    ],
  },
  {
    levelNumber: 7,
    name: 'Amber Bastion',
    difficultyTier: 'Hard+',
    maxFouls: 5,
    targetScore: 3700,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [Y, Y, Y, R, R, B, B, B],
      [P, P, W, W, G, G, Y],
      [G, B, R, P, W, Y, G, B],
      [W, W, P, P, R, R, W],
      [B, B, G, G, Y, Y, P, P],
      [_, Y, Y, B, B, R, _],
      [_, _, W, W, P, _, _, _],
    ],
  },
  {
    levelNumber: 8,
    name: 'Cobalt Vortex',
    difficultyTier: 'Hard+',
    maxFouls: 4,
    targetScore: 3900,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, G, G, P, P, B, B],
      [R, R, Y, Y, W, W, R],
      [W, P, B, G, Y, R, W, P],
      [Y, Y, R, R, G, G, Y],
      [P, P, B, B, W, W, R, R],
      [_, G, G, Y, Y, B, _],
      [_, _, R, R, P, _, _, _],
    ],
  },
  {
    levelNumber: 9,
    name: 'Amethyst Vault',
    difficultyTier: 'Hard+',
    maxFouls: 4,
    targetScore: 4100,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [P, P, P, W, W, G, G, G],
      [Y, Y, B, B, R, R, P],
      [R, G, W, Y, P, B, R, G],
      [B, B, P, P, W, W, B],
      [W, W, R, R, Y, Y, G, G],
      [_, P, P, B, B, Y, _],
      [_, _, G, G, R, _, _, _],
    ],
  },
  {
    levelNumber: 10,
    name: 'Citrine Citadel',
    difficultyTier: 'Hard+',
    maxFouls: 4,
    targetScore: 4400,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [Y, Y, R, R, B, B, Y, Y],
      [W, W, G, G, P, P, W],
      [P, B, Y, R, W, G, P, B],
      [G, G, W, W, R, R, G],
      [R, R, P, P, B, B, Y, Y],
      [_, W, W, G, G, P, _],
      [_, _, B, B, R, _, _, _],
    ],
  },

  // -------------------------------------------------------------
  // TIER 3: ADVANCED (Levels 11 - 15)
  // Narrow corridors, large suspended islands, deceptive branches
  // -------------------------------------------------------------
  {
    levelNumber: 11,
    name: 'Narrow Canyon',
    difficultyTier: 'Advanced',
    maxFouls: 4,
    targetScore: 4700,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, B, _, _, G, Y, Y],
      [P, P, _, _, _, W, P],
      [W, W, Y, _, _, B, R, R],
      [G, G, _, _, _, Y, G],
      [B, B, P, P, R, R, W, W],
      [_, W, W, G, G, B, _],
      [_, _, Y, Y, P, _, _, _],
    ],
  },
  {
    levelNumber: 12,
    name: 'Suspended Arch',
    difficultyTier: 'Advanced',
    maxFouls: 4,
    targetScore: 5000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [G, G, _, R, R, _, B, B],
      [W, W, P, P, Y, Y, W],
      [_, Y, Y, _, _, G, G, _],
      [B, B, R, R, P, P, B],
      [P, P, W, W, B, B, R, R],
      [_, G, G, Y, Y, W, _],
      [_, _, P, P, R, _, _, _],
    ],
  },
  {
    levelNumber: 13,
    name: 'Twin Pillars',
    difficultyTier: 'Advanced',
    maxFouls: 4,
    targetScore: 5300,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, _, _, _, _, Y, Y],
      [R, R, _, _, _, _, P, P],
      [G, G, W, W, B, B, R, R],
      [P, P, Y, Y, G, G, W],
      [W, W, B, B, R, R, P, P],
      [_, R, R, G, G, Y, _],
      [_, _, W, W, B, _, _, _],
    ],
  },
  {
    levelNumber: 14,
    name: 'Mirror Chasm',
    difficultyTier: 'Advanced',
    maxFouls: 4,
    targetScore: 5600,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [P, P, Y, Y, Y, Y, P, P],
      [R, R, B, B, B, B, R],
      [G, G, W, _, _, W, G, G],
      [W, W, _, _, _, _, W, W],
      [B, B, R, R, P, P, Y, Y],
      [_, G, G, W, W, B, _],
      [_, _, P, P, R, _, _, _],
    ],
  },
  {
    levelNumber: 15,
    name: 'Echo Chamber',
    difficultyTier: 'Advanced',
    maxFouls: 4,
    targetScore: 5900,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [W, W, G, G, R, R, W, W],
      [P, P, B, B, Y, Y, P],
      [Y, Y, _, W, W, _, B, B],
      [R, R, G, G, P, P, R],
      [G, G, B, B, W, W, Y, Y],
      [_, P, P, R, R, G, _],
      [_, _, W, W, B, _, _, _],
    ],
  },

  // -------------------------------------------------------------
  // TIER 4: VERY HARD (Levels 16 - 20)
  // Heavy anchor dependencies, sharp bank-shot necessity
  // -------------------------------------------------------------
  {
    levelNumber: 16,
    name: 'Anchor Lock',
    difficultyTier: 'Very Hard',
    maxFouls: 4,
    targetScore: 6300,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, R, _, _, B, B, B],
      [W, W, _, G, G, _, Y, Y],
      [P, P, B, B, R, R, W, W],
      [G, G, Y, Y, P, P, G],
      [Y, Y, W, W, B, B, R, R],
      [_, P, P, G, G, W, _],
      [_, _, B, B, Y, _, _, _],
    ],
  },
  {
    levelNumber: 17,
    name: 'Serpentine Pass',
    difficultyTier: 'Very Hard',
    maxFouls: 4,
    targetScore: 6600,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, B, Y, Y, Y, G, G],
      [_, P, P, W, W, R, R],
      [W, W, _, _, B, B, Y, Y],
      [G, G, R, R, P, P, W],
      [P, P, Y, Y, G, G, B, B],
      [_, R, R, W, W, P, _],
      [_, _, G, G, Y, _, _, _],
    ],
  },
  {
    levelNumber: 18,
    name: 'Iron Fortress',
    difficultyTier: 'Very Hard',
    maxFouls: 4,
    targetScore: 7000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [G, G, R, R, P, P, G, G],
      [B, B, W, W, Y, Y, B],
      [Y, Y, B, _, _, R, P, P],
      [W, W, P, G, B, R, W],
      [R, R, G, G, Y, Y, B, B],
      [_, P, P, W, W, R, _],
      [_, _, Y, Y, G, _, _, _],
    ],
  },
  {
    levelNumber: 19,
    name: 'Obsidian Spire',
    difficultyTier: 'Very Hard',
    maxFouls: 4,
    targetScore: 7400,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [P, P, B, B, G, G, P, P],
      [Y, Y, R, R, W, W, Y],
      [W, W, _, P, P, _, R, R],
      [B, B, G, G, Y, Y, B],
      [G, G, W, W, R, R, P, P],
      [_, Y, Y, B, B, G, _],
      [_, _, W, W, R, _, _, _],
    ],
  },
  {
    levelNumber: 20,
    name: 'Colossus Crest',
    difficultyTier: 'Very Hard',
    maxFouls: 4,
    targetScore: 7800,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, Y, Y, W, W, R, R],
      [G, G, P, P, B, B, G],
      [B, B, R, _, _, Y, W, W],
      [P, P, W, B, G, R, P],
      [W, W, Y, Y, P, P, B, B],
      [_, G, G, R, R, W, _],
      [_, _, B, B, Y, _, _, _],
      [_, _, _, P, P, _, _, _],
    ],
  },

  // -------------------------------------------------------------
  // TIER 5: EXPERT (Levels 21 - 25)
  // Deep ceiling supports, isolated islands, shot order critical
  // -------------------------------------------------------------
  {
    levelNumber: 21,
    name: 'Vanguard Matrix',
    difficultyTier: 'Expert',
    maxFouls: 4,
    targetScore: 8200,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, G, G, Y, Y, B, B],
      [R, R, W, W, P, P, R],
      [P, P, _, R, R, _, G, G],
      [Y, Y, B, B, W, W, Y],
      [W, W, P, P, G, G, R, R],
      [_, B, B, Y, Y, P, _],
      [_, _, W, W, G, _, _, _],
    ],
  },
  {
    levelNumber: 22,
    name: 'Quantum Web',
    difficultyTier: 'Expert',
    maxFouls: 4,
    targetScore: 8600,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [W, W, P, P, B, B, W, W],
      [G, G, Y, Y, R, R, G],
      [R, R, _, W, W, _, P, P],
      [B, B, G, G, Y, Y, B],
      [Y, Y, R, R, P, P, W, W],
      [_, B, B, G, G, R, _],
      [_, _, P, P, Y, _, _, _],
    ],
  },
  {
    levelNumber: 23,
    name: 'Helix Trench',
    difficultyTier: 'Expert',
    maxFouls: 4,
    targetScore: 9000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [G, G, Y, Y, R, R, G, G],
      [B, B, P, P, W, W, B],
      [W, W, _, G, G, _, Y, Y],
      [P, P, R, R, B, B, P],
      [R, R, W, W, Y, Y, G, G],
      [_, B, B, P, P, W, _],
      [_, _, Y, Y, R, _, _, _],
    ],
  },
  {
    levelNumber: 24,
    name: 'Bastion Core',
    difficultyTier: 'Expert',
    maxFouls: 4,
    targetScore: 9500,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [Y, Y, B, B, P, P, Y, Y],
      [W, W, R, R, G, G, W],
      [R, R, _, Y, Y, _, B, B],
      [G, G, W, W, P, P, G],
      [P, P, B, B, R, R, Y, Y],
      [_, W, W, G, G, P, _],
      [_, _, B, B, R, _, _, _],
    ],
  },
  {
    levelNumber: 25,
    name: 'Apex Labyrinth',
    difficultyTier: 'Expert',
    maxFouls: 4,
    targetScore: 10000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [P, P, R, R, W, W, P, P],
      [G, G, B, B, Y, Y, G],
      [Y, Y, _, P, P, _, R, R],
      [W, W, G, G, B, B, W],
      [B, B, Y, Y, R, R, P, P],
      [_, G, G, W, W, B, _],
      [_, _, P, P, Y, _, _, _],
      [_, _, _, R, R, _, _, _],
    ],
  },

  // -------------------------------------------------------------
  // TIER 6: EXPERT+ (Levels 26 - 30)
  // Extreme density, trick bounce setups, high stakes
  // -------------------------------------------------------------
  {
    levelNumber: 26,
    name: 'Vortex Nexus',
    difficultyTier: 'Expert+',
    maxFouls: 4,
    targetScore: 10500,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, W, W, B, B, R, R],
      [Y, Y, G, G, P, P, Y],
      [B, B, _, R, R, _, W, W],
      [P, P, Y, Y, G, G, P],
      [G, G, B, B, W, W, R, R],
      [_, P, P, Y, Y, B, _],
      [_, _, W, W, G, _, _, _],
    ],
  },
  {
    levelNumber: 27,
    name: 'Titan Spine',
    difficultyTier: 'Expert+',
    maxFouls: 4,
    targetScore: 11000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, P, P, G, G, B, B],
      [W, W, R, R, Y, Y, W],
      [G, G, _, B, B, _, P, P],
      [R, R, W, W, Y, Y, R],
      [Y, Y, G, G, P, P, B, B],
      [_, R, R, W, W, G, _],
      [_, _, P, P, Y, _, _, _],
    ],
  },
  {
    levelNumber: 28,
    name: 'Nebula Veil',
    difficultyTier: 'Expert+',
    maxFouls: 4,
    targetScore: 11500,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [G, G, R, R, W, W, G, G],
      [P, P, B, B, Y, Y, P],
      [W, W, _, G, G, _, R, R],
      [Y, Y, P, P, B, B, Y],
      [B, B, W, W, R, R, G, G],
      [_, Y, Y, P, P, W, _],
      [_, _, R, R, B, _, _, _],
    ],
  },
  {
    levelNumber: 29,
    name: 'Eclipse Horizon',
    difficultyTier: 'Expert+',
    maxFouls: 4,
    targetScore: 12000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [Y, Y, W, W, P, P, Y, Y],
      [B, B, G, G, R, R, B],
      [R, R, _, Y, Y, _, W, W],
      [P, P, B, B, G, G, P],
      [W, W, R, R, Y, Y, B, B],
      [_, P, P, G, G, W, _],
      [_, _, Y, Y, R, _, _, _],
    ],
  },
  {
    levelNumber: 30,
    name: 'Chamber of Trials',
    difficultyTier: 'Expert+',
    maxFouls: 3,
    targetScore: 12500,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [W, W, B, B, R, R, W, W],
      [G, G, P, P, Y, Y, G],
      [P, P, _, W, W, _, B, B],
      [R, R, G, G, P, P, R],
      [B, B, Y, Y, W, W, G, G],
      [_, R, R, P, P, B, _],
      [_, _, W, W, Y, _, _, _],
      [_, _, _, G, G, _, _, _],
    ],
  },

  // -------------------------------------------------------------
  // TIER 7: EXTREME (Levels 31 - 35)
  // Asymmetric structures, deep hidden anchors, razor-thin paths
  // -------------------------------------------------------------
  {
    levelNumber: 31,
    name: 'Asymmetric Void',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 13200,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, R, _, _, _, B, B],
      [Y, Y, _, W, W, _, P, P],
      [G, G, B, B, R, R, W, W],
      [_, P, P, Y, Y, G, G],
      [W, W, R, R, B, B, P, P],
      [_, Y, Y, G, G, W, _],
      [_, _, B, B, R, _, _, _],
    ],
  },
  {
    levelNumber: 32,
    name: 'Shattered Monolith',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 13900,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, _, _, _, G, G, G],
      [P, P, W, W, _, Y, Y],
      [R, R, Y, Y, B, B, W, W],
      [G, G, P, P, R, R, G],
      [W, W, B, B, Y, Y, P, P],
      [_, R, R, G, G, B, _],
      [_, _, W, W, P, _, _, _],
    ],
  },
  {
    levelNumber: 33,
    name: 'Glacial Abyss',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 14600,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [W, W, W, B, B, G, G, G],
      [_, R, R, _, _, P, P],
      [Y, Y, P, P, W, W, R, R],
      [B, B, G, G, Y, Y, B],
      [P, P, W, W, R, R, G, G],
      [_, Y, Y, B, B, P, _],
      [_, _, R, R, W, _, _, _],
    ],
  },
  {
    levelNumber: 34,
    name: 'Solar Flare',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 15300,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [Y, Y, Y, R, R, W, W, W],
      [P, P, _, _, _, B, B],
      [G, G, B, B, Y, Y, R, R],
      [W, W, P, P, G, G, W],
      [R, R, Y, Y, B, B, P, P],
      [_, G, G, W, W, R, _],
      [_, _, P, P, Y, _, _, _],
    ],
  },
  {
    levelNumber: 35,
    name: 'Dragon Maw',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 16000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, B, B, G, G, R, R],
      [W, W, _, _, _, Y, Y],
      [P, P, Y, Y, W, W, P, P],
      [G, G, R, R, B, B, G],
      [B, B, P, P, Y, Y, R, R],
      [_, W, W, G, G, B, _],
      [_, _, P, P, W, _, _, _],
      [_, _, _, R, R, _, _, _],
    ],
  },

  // -------------------------------------------------------------
  // TIER 8: TOURNAMENT EXTREME & CHAMPIONSHIP (Levels 36 - 40)
  // Elite competitive puzzles with maximum cluster drop rewards
  // -------------------------------------------------------------
  {
    levelNumber: 36,
    name: 'Grandmaster Gambit',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 17000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [P, P, P, W, W, B, B, B],
      [R, R, G, G, Y, Y, R],
      [W, W, _, _, _, _, W, W],
      [Y, Y, B, B, P, P, Y],
      [G, G, R, R, W, W, G, G],
      [_, P, P, Y, Y, B, _],
      [_, _, R, R, W, _, _, _],
      [_, _, _, G, G, _, _, _],
    ],
  },
  {
    levelNumber: 37,
    name: 'Crown of Thorns',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 18000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [G, G, G, R, R, Y, Y, Y],
      [B, B, P, P, W, W, B],
      [W, W, _, B, B, _, W, W],
      [R, R, Y, Y, G, G, R],
      [P, P, W, W, B, B, P, P],
      [_, G, G, R, R, Y, _],
      [_, _, W, W, B, _, _, _],
      [_, _, _, P, P, _, _, _],
    ],
  },
  {
    levelNumber: 38,
    name: 'Imperial Bulwark',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 19000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [B, B, B, W, W, R, R, R],
      [Y, Y, G, G, P, P, Y],
      [P, P, _, _, _, _, P, P],
      [W, W, B, B, R, R, W],
      [G, G, Y, Y, P, P, G, G],
      [_, R, R, W, W, B, _],
      [_, _, G, G, Y, _, _, _],
      [_, _, _, P, P, _, _, _],
    ],
  },
  {
    levelNumber: 39,
    name: 'Summit of Champions',
    difficultyTier: 'Extreme',
    maxFouls: 3,
    targetScore: 20500,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [W, W, W, P, P, G, G, G],
      [R, R, B, B, Y, Y, R],
      [Y, Y, _, W, W, _, Y, Y],
      [P, P, G, G, B, B, P],
      [B, B, R, R, W, W, B, B],
      [_, Y, Y, P, P, G, _],
      [_, _, R, R, W, _, _, _],
      [_, _, _, B, B, _, _, _],
    ],
  },
  {
    levelNumber: 40,
    name: 'FINAL CHAMPIONSHIP: THE APEX OF LEGENDS',
    difficultyTier: 'Championship',
    maxFouls: 3,
    targetScore: 25000,
    availableColors: [R, B, G, Y, P, W],
    rows: [
      [R, R, B, B, G, G, Y, Y],
      [P, P, W, W, R, R, P],
      [B, B, Y, Y, G, G, W, W],
      [W, W, P, P, B, B, R],
      [G, G, R, R, Y, Y, P, P],
      [_, B, B, W, W, G, _],
      [_, _, P, P, R, _, _, _],
      [_, _, _, Y, Y, _, _, _],
    ],
  },
];
